### PR TITLE
moving updatePosData to GVRViewManager

### PR DESCRIPTION
**Pull request by roshanch**
GearVRf-DCO-1.0-Signed-off-by: Roshan Chaudhari roshan.c@samsung.com

### CODE REVIEW

**Comment by roshanch** [comment]
i think putting it on back-end side would be better. But there might be better place for it. @liaxim what do you think about it.

**Comment by liaxim** [comment]
I believe there should be a generic facility to query a backend adapter (backend_oculus, backend_daydream) for a specific model asset so the appropriate model can be shown if you use Oculus or Daydream. The actual assets will be bundled with the backend adapter (backend_oculus, backend_daydream).

So the backend_oculus adapter will bundle assets for the Oculus controller and the backend_daydream adapter for the Daydream controller. In that sense your pull request looks good to me.

**Comment by liaxim** [comment]
It means gear_vr_controller.obj and associated assets will have to move to the backend_oculus adapter.

**Comment by NolaDonato** [comment]
We should test it with a model coming from the back end. I am not sure if it will work.

**Comment by roshanch** [comment]
i have requested models from Mike. I will update PR once I get them.

**Comment by liaxim** [comment]
Looks good. Planning to merge on Thursday.

We can add the models in a subsequent pull request. Btw, I am not sure updatePosData is really needed. Will look into it as part of another pull request that is in progress.

**Pull request merged**
