### PR TITLE
Add  BulletPhysics for 64bits

### PR DESCRIPTION
**Pull request by ragner**
Add BulletPhysics for 64bits.

* The build of physics extension for both 32bits and 64bits is not working yet.
I need help with this issue.

GearVRf-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
I am seeing this crash in the 64bit build. Is this the problem you are talking about?

```
02-21 08:47:39.715 20397 20397 F DEBUG   : Build fingerprint: 'samsung/greatqltesq/greatqlte:7.1.1/NMF26X/N950USQU1AQIA:user/release-keys'
02-21 08:47:39.715 20397 20397 F DEBUG   : Revision: '11'
02-21 08:47:39.715 20397 20397 F DEBUG   : ABI: 'arm64'
02-21 08:47:39.715 20397 20397 F DEBUG   : pid: 20346, tid: 20392, name: gvrf-physics  >>> org.gearvrf.gvrbullet <<<
02-21 08:47:39.715 20397 20397 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa0a0a0a0a0b12
02-21 08:47:39.715 20397 20397 F DEBUG   :     x0   0a0a0a0a0a0a0a0a  x1   0000000000000000  x2   0000007f771e545c  x3   0000007f9f34d39b
02-21 08:47:39.715 20397 20397 F DEBUG   :     x4   0000007f75e9ecd0  x5   0000800000800000  x6   0000800000800000  x7   0000007f801f6057
02-21 08:47:39.715 20397 20397 F DEBUG   :     x8   0000007f9290b410  x9   0000000000000000  x10  000000000000003c  x11  89d28115296e45a6
02-21 08:47:39.715 20397 20397 F DEBUG   :     x12  0000000000000000  x13  89d28115296e45a6  x14  0000000000000000  x15  0000007f9f3fc7f0
02-21 08:47:39.715 20397 20397 F DEBUG   :     x16  0000007f7b882440  x17  0000007f7b84321c  x18  00000000000007ad  x19  0000007f928a3800
02-21 08:47:39.715 20397 20397 F DEBUG   :     x20  0000007f9ee4b5b0  x21  0000007f928a3800  x22  0000007f75e9f14c  x23  0000007f801d6c46
02-21 08:47:39.715 20397 20397 F DEBUG   :     x24  0000000000000008  x25  89d28115296e45a6  x26  0000007f928a3898  x27  0000007f9f4c2600
02-21 08:47:39.715 20397 20397 F DEBUG   :     x28  89d28115296e45a6  x29  0000007f75e9ece0  x30  0000007f7b843d1c
02-21 08:47:39.715 20397 20397 F DEBUG   :     sp   0000007f75e9ecd0  pc   0000007f7b843228  pstate 0000000080000000
02-21 08:47:39.717 20397 20397 F DEBUG   : 
02-21 08:47:39.717 20397 20397 F DEBUG   : backtrace:
02-21 08:47:39.717 20397 20397 F DEBUG   :     #00 pc 0000000000025228  /data/app/org.gearvrf.gvrbullet-1/lib/arm64/libgvrf-physics.so (_ZNK17btCollisionObject14getUserPointerEv+12)
02-21 08:47:39.717 20397 20397 F DEBUG   :     #01 pc 0000000000025d18  /data/app/org.gearvrf.gvrbullet-1/lib/arm64/libgvrf-physics.so (_ZN3gvr11BulletWorld14listCollisionsERSt4listINS_12ContactPointESaIS2_EE+220)
02-21 08:47:39.717 20397 20397 F DEBUG   :     #02 pc 000000000002e570  /data/app/org.gearvrf.gvrbullet-1/lib/arm64/libgvrf-physics.so (Java_org_gearvrf_physics_NativePhysics3DWorld_listCollisions+132)
02-21 08:47:39.717 20397 20397 F DEBUG   :     #03 pc 0000000000365da4  /data/app/org.gearvrf.gvrbullet-1/oat/arm64/base.odex (offset 0x31b000)
```

**Comment by liaxim** [comment]
Getting the same crash with armeabi-v7a
```
02-21 09:53:12.276   948   948 F DEBUG   : Build fingerprint: 'samsung/greatqltesq/greatqlte:7.1.1/NMF26X/N950USQU1AQIA:user/release-keys'
02-21 09:53:12.276   948   948 F DEBUG   : Revision: '11'
02-21 09:53:12.277   948   948 F DEBUG   : ABI: 'arm'
02-21 09:53:12.277   948   948 F DEBUG   : pid: 725, tid: 941, name: gvrf-physics  >>> org.gearvrf.gvrbullet <<<
02-21 09:53:12.277   948   948 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xf0
02-21 09:53:12.277   948   948 F DEBUG   :     r0 00000000  r1 00000000  r2 c1ea9000  r3 00000000
02-21 09:53:12.277   948   948 F DEBUG   :     r4 c69fa5d4  r5 00000002  r6 c69fa5d4  r7 c163c9d0
02-21 09:53:12.277   948   948 F DEBUG   :     r8 c163cc08  r9 de65be00  sl 00000000  fp c163cb8c
02-21 09:53:12.277   948   948 F DEBUG   :     ip c69faaec  sp c163c9d0  lr c69de72f  pc c69ddfb6  cpsr 800b0030
02-21 09:53:12.279   948   948 F DEBUG   : 
02-21 09:53:12.279   948   948 F DEBUG   : backtrace:
02-21 09:53:12.279   948   948 F DEBUG   :     #00 pc 0001afb6  /data/app/org.gearvrf.gvrbullet-2/lib/arm/libgvrf-physics.so (_ZNK17btCollisionObject14getUserPointerEv+9)
02-21 09:53:12.279   948   948 F DEBUG   :     #01 pc 0001b72b  /data/app/org.gearvrf.gvrbullet-2/lib/arm/libgvrf-physics.so (_ZN3gvr11BulletWorld14listCollisionsERSt4listINS_12ContactPointESaIS2_EE+142)
02-21 09:53:12.279   948   948 F DEBUG   :     #02 pc 00021e43  /data/app/org.gearvrf.gvrbullet-2/lib/arm/libgvrf-physics.so (Java_org_gearvrf_physics_NativePhysics3DWorld_listCollisions+94)
02-21 09:53:12.279   948   948 F DEBUG   :     #03 pc 0034e945  /data/app/org.gearvrf.gvrbullet-2/oat/arm/base.odex (offset 0x31b000)
```

What bullet source tree are you building? Can you point me at it so I can build it too?

**Comment by liaxim** [comment]
I think this requires debugging bullet itself. There are some random pointers showing up while iterating in BulletWorld::listCollisions.

**Comment by ragner** [comment]
@liaxim  sorry my dealy.
Please see my branch gvrf-version at: https://github.com/ragner/bullet3/tree/gvrf-version

That branch is at same level of version tag 2.87

**Comment by ragner** [comment]
@liaxim I may need update some header files ... I will check that issue.

**Comment by ragner** [comment]
@liaxim I have updated the header files. Should work now.

**Comment by liaxim** [comment]
Works fine, including the 64bit variant. A small patch to the gradle file is necessary but I can do that after merging. The tests pass too.

Patch: [diff.txt](https://github.com/Samsung/GearVRf/files/1782006/diff.txt)

Planning to merge on Tuesday.

**Pull request merged**
