### PR TITLE
Switch to Oculus Mobile SDK 1.0.4

### PR DESCRIPTION
**Pull request by liaxim**
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
- the oculus backend is not going to be backwards compatible with 1.0.3
- less dependencies to oculus is better; if we are ok with including libvrapi.so then we can simplify the build further
- updated the experimental gradle plugin project too
- libvrapi's Android.mk uses non-standard "BUILDTYPE" subdirectory which forces us to set it explicitly to "Release" in our build files

Test scenarios:
- long back key press
- short back key press
- running app without oculus signature
- multiview gvr-shadows

**Comment by thomasflynn** [comment]
so far, i have cherry-picked and tested with simplesample.  compiling against 1.0.4 will fail without this commit.  i should do a little more testing, but so far, this looks good.

**Comment by thomasflynn** [comment]
p.s. let me know what i need to change in our build instructions:
https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project/060_Gear_VRf_Developer_Guide/110_Build_Instructions

**Comment by liaxim** [comment]
No need to copy SystemUtils.jar and VrApi.jar anymore.

**Pull request merged**
