### PR TITLE
framework: animation: when animation is done, avoid looping over somewhere at the start

### PR DESCRIPTION
**Pull request by liaxim**
also don't print bogus warnings when the time is out of range

---
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@mwitchwilliams could you please run some of your animation tests with this change in? Or let me know which x3d tests you think would be suitable so I can run them myself. Thanks.

**Comment by mwitchwilliams** [comment]
https://github.com/gearvrf/GearVRf-Tests/tree/master/x3d/TouchSensors has single animations based on touching an object (usually the blue cone, there is a Word doc for each test).  A single touch sensor can invoke multiple animations running on different timers.
For continuous animations without interactivity, try https://github.com/gearvrf/GearVRf-Tests/tree/master/x3d/animation

I can run these tests later today.

**Comment by mwitchwilliams** [comment]
Tested with animation01 thru 06.x3d (6 total tests) at https://github.com/gearvrf/GearVRf-Tests/tree/master/x3d/animation with a variety of continuous animations, including parent objects rotated with child objects with unique rotatation (so child object had multiple rotatations), plus scenes with multiple animations with both shared and different timers.
Also tested with touchSensor1 thru 5.x3d (5 total tests) at https://github.com/gearvrf/GearVRf-Tests/tree/master/x3d/TouchSensors, which clicked on meshes (including child objects) for a single loop animation.  Some tests also had non-interactive objects with continuous rotations, translations and scaling animations.  Tests also had _isOver_ and _isTouch_ animations.  No animation restarted before it was completed as expected.

All tests ran just fine.  **Looks Good To Me (LGTM)**

**Comment by liaxim** [comment]
@mwitchwilliams Thank you. Planning to merge on Monday.

**Pull request merged**
