### PR TITLE
Copy libs by default

### PR DESCRIPTION
**Pull request by parthmehta209**
1. This change makes it easier to build the extensions by defining the LIBS_DIRECTORY by default
2. Changes permission on gradlew files to make commandline build easier.

### CODE REVIEW

**Comment by rahul27** [comment]
Should we just add prebuilt libraries for the extensions to the libs folder? It would be one less step to build the samples.

**Comment by parthmehta209** [comment]
Not sure if we want to checkin binaries.

**Comment by parthmehta209** [comment]
Not sure if we want to checkin binaries.

**Comment by rahul27** [comment]
Having to build and copy these files definitely does not make it easy for either the developer or the end user to build applications.

**Comment by parthmehta209** [comment]
Eventually we want all the binaries framework and extension aar to be
hosted on github, So as a user if you are only looking for samples you dont
need to build anything other than the sample itself.

**Comment by liaxim** [comment]
Yep. All the prebuilt binaries should be available either from an official release or the nightly build release. This is still work in progress; it will get better and easier with time.

**Comment by liaxim** [comment]
@parthmehta209 If the LIBS_DIRECTORY is defined but the directory doesn't really exist the build will fail. We need to make changes to the build.gradle files to just skip copying if the directory doesn't exist. What do you think?

**Comment by parthmehta209** [comment]
Oh yes. Thats probably better than failing. Will make that change.

**Comment by parthmehta209** [comment]
@liaxim changed the build.gradle file to not copy aar files if the directory does not exist.

**Pull request merged**
