### PR TITLE
Improvements to the IO Framework

### PR DESCRIPTION
**Pull request by rahul27**
* Fixed key and motion events in the Controller. Previously
all events between process cycles were skipped. Now the
controller returns all key and motion events processed.
* The controller returns the vendor, product and name of the
device that controls it.
* Corrected Javadocs
* Restored the invalidate() method for cases where the scene
graph changes but the controller data does not.
* Renamed GVRCursorType to GVRControllerType

GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Tried gvr-events. I don't see the blue dot for the gaze cursor with this change but I see it with the old code. Running on S7, developer mode, not docked and with a bluetooth mouse connected.

**Comment by rahul27** [comment]
There were some conflicts on rebase. I've fixed them, try now.

**Comment by liaxim** [comment]
Looks good to me. The sample works the same. If there are no objections will merge in the afternoon.

---
In the future, you might want to take a look at GVRSceneObject.getComponent and consider exposing the sensor as  a component through it.

**Comment by rahul27** [comment]
Sure. Will look into it.

**Pull request merged**
