### PR TITLE
Reconcile GVRCameraRig, GVRContext; start splitting into base and backend trees

### PR DESCRIPTION
**Pull request by liaxim**
Added backend-specific trees; for Java: ``./src/main/backends/oculus/``; for C++: ``src/main/jni/backends/oculus/``. For now it seems I will follow this pattern of introducing base classes so it made sense to isolate the backend-specific files somehow.

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
This can be reviewed and considered for merging now.

**Comment by liaxim** [comment]
@jason2kim Could you please have a look? Let me know what you think. Thanks.

**Comment by jason2kim** [comment]
I think this is a good step toward our goal for the moment. I promise I will get more deeply involved when preparing the next patch.

**Comment by liaxim** [comment]
Will merge tomorrow morning.

**Comment by liaxim** [comment]
Rebased; small change to X3Dobject and its use of the camera rig.

**Pull request merged**
