### PR TITLE
Possible fix for bug #801

### PR DESCRIPTION
**Pull request by thomasflynn**
In https://github.com/thomasflynn/GearVRf/tree/bug801, what is happening
is that a new future texture is asked to be loaded, meanwhile the
reference to the existing texture is released.  Since that reference is
released, it gets garbage collected, but the native side don't know
about it and is still trying to use the old texture.

This change holds onto the existing texture reference until the new texture is loaded.  I still haven't evaluated if there are any possibility for leaks with this change.  This change also now calls into question whether the setTexture(key, null) call is actually necessary at line 617.  Still evaluating this.

Putting this change up now to get comments.  Does this look like the
right fix?  Are there other / better ways?  Let me know.

GearVRf-DCO-1.0-Signed-off-by: Tom Flynn
tom.flynn@samsung.com

The bug: https://github.com/Samsung/GearVRf/issues/801

### CODE REVIEW

**Comment by NolaDonato** [comment]
Yes the setTexture(key, null) is necessary. It tells GearVRF that this material will have a texture in the future even though it does not have one now. When GVRShaderTemplate.bindShader is called, it will compile a shader that needs a texture instead of one that does not.


________________________________

**Comment by thomasflynn** [comment]
@NolaDonato thanks.  that explains that mystery then.  it let my sample app run for two hours with no change in memory usage, so i'm feeling a bit safer about this change.

**Comment by thomasflynn** [comment]
The more I think about this, the more I think this is probably the correct fix.

**Comment by liaxim** [comment]
Would it be a more general fix if the null was getting propagated down to the native code and have it deal with it properly instead of trying to guard the native pointer from the Java side? That would be the diff:

```
diff --git a/GVRf/Framework/framework/src/main/java/org/gearvrf/GVRMaterial.java b/GVRf/Framework/framework/src/main/java/org/gearvrf/GVRMaterial.java
index e97a95a..1e72b93 100644
--- a/GVRf/Framework/framework/src/main/java/org/gearvrf/GVRMaterial.java
+++ b/GVRf/Framework/framework/src/main/java/org/gearvrf/GVRMaterial.java
@@ -602,8 +602,9 @@ public class GVRMaterial extends GVRHybridObject implements
         {
             tinfo.Texture = texture;
         }
-        if (texture != null)
-            NativeMaterial.setTexture(getNative(), key, texture.getNative());
+
+        final long nativePtr = null != texture ? texture.getNative() : 0;
+        NativeMaterial.setTexture(getNative(), key, nativePtr);
     }
 
     public void setTexture(final String key, final Future<GVRTexture> texture) {
diff --git a/GVRf/Framework/framework/src/main/jni/objects/material.h b/GVRf/Framework/framework/src/main/jni/objects/material.h
index 0c56bce..d38b75c 100644
--- a/GVRf/Framework/framework/src/main/jni/objects/material.h
+++ b/GVRf/Framework/framework/src/main/jni/objects/material.h
@@ -113,7 +113,9 @@ public:
         textures_[key] = texture;
         //By the time the texture is being set to its attaching material, it is ready
         //This is guaranteed by upper java layer scheduling
-        texture->setReady(true);
+        if (nullptr != texture) {
+            texture->setReady(true);
+        }
         if (key == "main_texture") {
             main_texture = texture;
         }
```

**Comment by thomasflynn** [comment]
I would think texture->setReady(false) would need to be called at some point, right?

**Comment by liaxim** [comment]
If you have no texture instance, why would the ready flag matter?

**Comment by liaxim** [comment]
With this change in, gvr-360video shows a black screen. Cleaned and rebuilt couple of times but it is consistent on my Note 5.

**Comment by NolaDonato** [comment]
PR #1084 may fix this problem.

**Comment by thomasflynn** [comment]
Ok, so, I tried Mihail's suggestion above.  it works.  Though the texture being replaced goes black while the new texture is loaded.  

I went back and found the issue with my earlier pull-request.  the call to setTexture() should not have been in an 'else' statement.  It should just be called anyway.  With that change, gvr-360video, simplesample, and others seem to work.

haven't tried Nola's pull-request yet.

**Comment by thomasflynn** [comment]
ok, it looks like Nola's does the same thing plus a little extra.  If you wanna merge that go ahead and I'll close this.

**Comment by thomasflynn** [comment]
we'll take Nola's fix.

**Pull request closed without merging**
