### PR TITLE
New features for 3D Cursor

### PR DESCRIPTION
**Pull request by rahul27**
* Movable and Selectable objects can now be rotated and scaled
* Improved the performance of the Object Cursor
* Added a selectable group for better event handling
* Minor bug fixes

GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by rahul27** [comment]
Waiting for @salgubel to give the thumbs up before we can review and merge this change. 

I will update the scene-editor once this change is merged.

**Comment by rahul27** [comment]
@salgubel has given me the thumbs up. This PR is ready for review.

**Comment by liaxim** [comment]
gvr-3dcursor-simple; I used to be able to re-position and scale the rocket on left side but not anymore. Is the app in need of an update?

**Comment by rahul27** [comment]
@liaxim I was able to re position and scale the rocket in gvr-3dcursor-simple. Could you try again and let me know if it does not work for you?

**Comment by liaxim** [comment]
Sure. Will retest.

**Comment by liaxim** [comment]
Maybe I am using it incorrectly. Will show you after lunch.

**Comment by liaxim** [comment]
@rahul27 's build are fine. I need to find out why my builds are different.

**Comment by liaxim** [comment]
Built on a different machine. It still doesn't work for me.

@NolaDonato @roshanch Can one of you please try the gvr-3dcursor-simple with the framework built with this pull request in? Make sure you start from completely clean trees. Thanks.

**Comment by roshanch** [comment]
Sure.! I will try this.

**Comment by rahul27** [comment]
@liaxim @roshanch I managed to recreate the issue. There was an issue with the 3DCursorLibrary build and the new AndroidStudio build tools version. 

FYI we might have to get rid of the assembledebug.doLast tasks for all the extensions like the following PR:
https://github.com/Samsung/GearVRf/pull/983

**Comment by liaxim** [comment]
Since you are going to be changing the gradle files, please keep in mind https://github.com/Samsung/GearVRf/pull/1061. I am looking for your feedback on it and maybe something different needs to be done there too.

**Comment by rahul27** [comment]
Sure. Will take a look.

**Comment by rahul27** [comment]
@liaxim gvr-3dcursor-simple should be fixed now.

**Comment by liaxim** [comment]
Looks good. Planning to merge Monday morning.

**Pull request merged**
