### PR TITLE
Virtual keyboard GVRf sample.

### PR DESCRIPTION
**Pull request by Maginador**
Virtual GVRf keyboard sample created by Samsung SIDIA.

GearVRf-DCO-1.0-Signed-off-by: Ricardo Maginador
ricardo.cm@samsung.com

### CODE REVIEW

**Comment by thomasflynn** [comment]
Thanks for the pull-request!  I can't wait to try it.  However, with a change we merged in earlier today, your sample will no longer compile :(.  Sorry.  We've been trying to get rid of the need for getOwnerObject() from user-callable code.  Earlier today, we made that method protected.  Looking at your sample though, it looks as though you really just need getTransform() which is provided by the camera rig.  Could you update your code accordingly?

Also, the project.properties references a directory that doesn't exist.  Most of our samples use ../../Framework/ as the directory the framework is in since that matches the directory structure of GVRf when you do a git clone.

**Comment by Maginador** [comment]
Thanks for your answer, I made the asked changes.

**Comment by chenchao1407** [comment]
Hi. You may need to add file header to each source code file. And also sign the DCO signature in the pull request message. Thanks.

**Comment by chenchao1407** [comment]
Try to compile it, Eclipse reports that it requires a folder "vr-controls" which we don't have.

**Comment by Maginador** [comment]
Hello Chao. Thanks for your attention.
Added the header, fixed the folder dependency problem and added the DCO signature.

**Comment by thomasflynn** [comment]
wow, looks very nice!  though, question, if i click on the mic, should something happen?

**Comment by Maginador** [comment]
If you have access to internet it uses voice recognition to get what you're saying and set as the answer.

**Comment by thomasflynn** [comment]
hm, doesn't seem to be doing anything for me :(.

**Comment by dknaan** [comment]
Very nice sample application! Works well for me (including the mic and voice recognition) on my Mali Note4

**Comment by Maginador** [comment]
I'm sorry, my bad, something changed in the framework making this feature stop working, but it's working now. If you have internet it will use voice recognition other wise it will give a negative feedback.

**Comment by dknaan** [comment]
Works well also on my S6 Edge. Thanks!

**Comment by thomasflynn** [comment]
tested with the latest commit, the mic works now.  Nice sample guys!

**Pull request merged**
