### PR TITLE
Fix camera rig's reset while docked

### PR DESCRIPTION
**Pull request by liaxim**
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by imuli** [comment]
Certainly fixes #650, thank you!

**Comment by yjlintw** [comment]
The code would work without changing things in camera_rig.cpp

**Comment by liaxim** [comment]
Without this fix it would only work if you use developer mode and do not dock into a headset.

**Comment by yjlintw** [comment]
Weird, because it works fine with my app in non-developer mode and the phone is on the dock. Thanks for the timely fix anyway, it saves my life.

**Comment by liaxim** [comment]
@yjlintw Weird. It definitely didn't work for me and I can't see how it could have worked unless you are using the phone's internal sensors all the time. Please try the fix and let us know if it causes problems for you.

**Comment by liaxim** [comment]
I have confirmation this fixes the issue. Will merge tomorrow morning.

**Comment by yjlintw** [comment]
@liaxim Sorry that I was out of town the past week and didn't have the chance to test the code until now. Can you tell me that how can I tell if I am using the phone's internal sensors or not. I'm using the innovator version, does that matter?

**Comment by liaxim** [comment]
@yjlintw Hi. There is no direct way but the experience would be terrible if you were using the phone sensors while wearing the headset. There is a "handleOnDock" printout in logcat but this is pretty much it.

I said that as the camera rig's reset method could only possibly work previously if you were using the phone sensors. There is a different path in the code for that case.

**Pull request merged**
