### PR TITLE
framework, backend_oculus: ensure there is a renderer instance always

### PR DESCRIPTION
**Pull request by liaxim**
- fixes the gvr-blurfilter crash after pause/resume

+ fix formatting
+ some cleanup

The fix is adding gRenderer = Renderer::getInstance() to GVRActivity::onSurfaceChanged

---

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
Backend-specific fix so I will be coming back to this in the future.

A very good example why the renderer should not be a singleton. It is not even a true singleton since it is not the same instance during the process lifetime.

**Comment by NolaDonato** [comment]
I agree it should not b a singleton. We will address this in the next release.

**Comment by dnvasilev** [comment]
Conflicts with #1526

**Comment by liaxim** [comment]
Now includes #1526

**Comment by liaxim** [comment]
No longer includes #1526 since it introduces some problems. Merging this. #1526 needs updating anyways.

**Pull request merged**
