### PR TITLE
Mesh collider distance tweak

### PR DESCRIPTION
**Pull request by liaxim**
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
Just curious: if we have the distance in one coordinate space (mesh) why do we have to translate it to world? Isn't the distance going to be the same in both?

**Comment by NolaDonato** [comment]
Not if any of the transforms have scaling



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by liaxim** [comment]
I see. And is this fix good? Thanks.

**Comment by NolaDonato** [comment]
Can't get to it until I get home this evening,  laptop is in luggage storage.


Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by liaxim** [comment]
@NolaDonato Please let me know whether this can be merged. There is an internal app that is affected.

**Comment by NolaDonato** [comment]
Yes the fix is good, merge it.

**Pull request merged**
