### PR TITLE
updating assimp library to support layered textures

### PR DESCRIPTION
**Pull request by roshanch**
updating assimp library for:
1. Storing all the layered textures and blend mode.
2. Some of the FBX files has "SpecularFactor" with specular texture, adding support for that.

GearVRf-DCO-1.0-Signed-off-by: Roshan Chaudhari roshan.c@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
What samples have been verified with the updated assimp?

**Comment by roshanch** [comment]
I test with gvr-testmodels with assimp samples and with the model given by Mike, and modified framework to see whether all textures are imported or not.

**Comment by roshanch** [comment]
Test model is shared at \\corpdata_sj\SHARE FOLDER\Roshan\lightmap_test

**Comment by liaxim** [comment]
Looks good. Will merge after lunch.

**Comment by roshanch** [comment]
assimp needs more modification, which i will update today or tomorrow. I will upload the new patch here.

**Comment by liaxim** [comment]
Should be merged together with or prior to https://github.com/Samsung/GearVRf/pull/870

**Comment by liaxim** [comment]
@roshanch Whenever you get the chance, could you please add an so for arm64-v8a? Thanks.

**Comment by liaxim** [comment]
And again, when you have the time, please try to build with optimizations and no debug info. The so is 11MBs; after stripping it goes down to 7MBs. Every once in a while we get asked about binary sizes.. Are all changes made to assimp in our gerrit?

**Comment by liaxim** [comment]
No problems encountered with the samples. Will merge tomorrow morning if there are no comments.

**Comment by roshanch** [comment]
Do we need .so with target= "arm64-v8a" ? I tried with -O3 flag but still we are getting same size. I need to try more flags.

**Comment by liaxim** [comment]
An arm64 build is a nice-to-have. We can produce a 64 bit build with certain backends. The 64 bit assimp so in the repo is very old.

**Comment by roshanch** [comment]
I remember few months back I tried with the arm64 target and it crashed. That's the reason I built it with other. But I do have .so for arm64. 
And this code is not updated in gerrit yet.

**Pull request merged**
