### PR TITLE
Added function clearLights to remove all lights from scene

### PR DESCRIPTION
**Pull request by apjagdale**
This would remove the obsolete lights from scene.

### CODE REVIEW

**Comment by liaxim** [comment]
Looks good to me.

@NolaDonato Any comments?

**Comment by NolaDonato** [comment]
I will test today.

**Comment by liaxim** [comment]
@NolaDonato Is this change ok to go in? Thanks.

**Comment by NolaDonato** [comment]
Yes. I tested this one with gvr-multilight, gvr-jassimp, gvr-testmodels with x3d content and gvr-shadow and they all work.

**Pull request merged**
