### PR TITLE
x3d: make x3d its own extension

### PR DESCRIPTION
**Pull request by liaxim**
Makes X3D an extension; the only notable part is the addition of the X3DLoader class and its use by the AssetLoader.

Related change: https://github.com/gearvrf/GearVRf-Demos/pull/581

---

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by mwitchwilliams** [comment]
Won't impact any of my current development (on JavaScript interactivity for Text, Movies).

Can't come up with any issues. A few Pull Requests for maint_v3.x and not have been merged into Master v4.x (https://github.com/Samsung/GearVRf/pull/1298, https://github.com/Samsung/GearVRf/pull/1527, https://github.com/Samsung/GearVRf/pull/1425). I anticipated fixing these in Master anyway if they didn't get into v4.x. Easy fixes.

As long as it rebuilds, seems fine to me. May start using this new location as early as this week.

**Comment by liaxim** [comment]
@NolaDonato @thomasflynn Any objections? With the upcoming exoplayer dependency this change will help keep the core framework in check.

**Comment by NolaDonato** [comment]
The asset loader provides a number of ways to load an X3D model. You can put a scene object in the scene and then tell it to load under that scene object in a separate thread and notify you when it is done. You can ask it to load an X3D model and give you the root scene object so you can add it later yourself. I think some of our internal applications use these features.

I think it would be better if the asset loader could be provided with the X3D loader by the user if they want to use the extension. Then we keep all the capabilities but X3D can still be an extension. If you try to load something with ".x3d" and the asset loader doesn't have an X3D loader it can give an exception.

**Comment by liaxim** [comment]
It all boils down to loadX3DModel which has been dealt with. If the extension is not present, exception is thrown. The user provides the loader by including the extension in her build. If the x3d extension is not present the only capability lost is the capability to load x3d files. How does that sound?

**Comment by NolaDonato** [comment]
It sounds better than what I proposed. I didn't know how to check for the presence of an extension.

**Comment by liaxim** [comment]
If there are no objections, planning to merge this on Tuesday.

**Pull request merged**
