### PR TITLE
KSensor improvements

### PR DESCRIPTION
**Pull request by liaxim**
Can be reviewed.

### CODE REVIEW

**Comment by liaxim** [comment]
Testing is very time consuming; will keep on testing it over the next couple of days. 

JNI crash with the eyepicking sample when dynamically switching from internal to ksensor/oculus. I have seen it before, without this change, but it is still suspicious. I will keep looking at it.

The most heavy-weight app that can possibly be used for testing needs updating as recent changes have broken it (it didn't seem like a straightforward removal of getOwnerObject references). So I haven't been able to use it today.

The sensored scene in the GVRViewManager is a pain and it is still half-baked. Once I move the internal sensor to the native code I will be probably able to improve that part.

**Comment by liaxim** [comment]
Will test the mono renderer tomorrow; last time I broke it eventually as I forgot about it at the end.

**Comment by thomasflynn** [comment]
tested.  seems to have a pretty noticeable difference.  anyone else have any comments?

**Comment by dknaan** [comment]
I didn't see any difference on my S6 with the Eyepicking sample. 
@thomasflynn - which sample did you use to test?

**Comment by dknaan** [comment]
I didn't see a difference also with the virtaul keyboard on my Note4

**Pull request merged**
