### PR TITLE
Back key handling improvements

### PR DESCRIPTION
**Pull request by liaxim**
Demos change: https://github.com/gearvrf/GearVRf-Demos/pull/388

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
Adds an onBackPress method to GVRScript/GVRMain giving a chance to the app to go back a level or let the framework show the Oculus exit UI.

**Comment by liaxim** [comment]
Tested with both the black and white headsets. Ready for review.

**Comment by thomasflynn** [comment]
needs rebase

**Comment by liaxim** [comment]
Rebased

**Comment by thomasflynn** [comment]
looks good to me

**Comment by liaxim** [comment]
Will merge in the afternoon

**Pull request merged**
