### PR TITLE
Eliminate redundant assimp nodes

### PR DESCRIPTION
**Pull request by NolaDonato**
Assimp adds nodes UNDER the root model. Internal projects have requested to add the mesh directly to the root model if there is only one mesh to make it easier to access. This patch eliminates the extra root node.

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by NolaDonato** [comment]
I fixed the conflict

**Comment by liaxim** [comment]
I think this should be optional for now and has to be enabled explicitly. Or you need to check everything for side-effects. For example SelectableBehavior fails with (gvr-3dcursor-simple):

```
             System.err  W  java.lang.IllegalArgumentException: Num of children in model:0 does not match the states array:4
     GVRAndroidResource  D  Looking for compressed header
             System.err  W      at org.gearvrf.io.cursor3d.SelectableBehavior.onAttach(SelectableBehavior.java:196)
                         W      at org.gearvrf.GVRComponent.setOwnerObject(GVRComponent.java:98)
                         W      at org.gearvrf.GVRSceneObject.attachComponent(GVRSceneObject.java:355)
                         W      at org.gearvrf.io.cursorsimple.CursorMain.onInit(CursorMain.java:99)
                         W      at java.lang.reflect.Method.invoke(Native Method)
                         W      at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
                         W      at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:126)
                         W      at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
                         W      at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
                         W      at org.gearvrf.GVRViewManager$1$1.run(GVRViewManager.java:333)
                         W      at android.os.Handler.handleCallback(Handler.java:751)
                         W      at android.os.Handler.dispatchMessage(Handler.java:95)
                         W      at android.os.Looper.loop(Looper.java:154)
                         W      at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by liaxim** [comment]
gvr-lua - the model is missing

**Comment by liaxim** [comment]
gvr-multilight is affected too

**Comment by NolaDonato** [comment]
I have made the patch less aggressive. Now it leaves the top node in case of a hierarchy. This fixes all the demos. In the case of an asset with a single mesh, there is no top node. This is what our internal customers were asking for.

**Comment by liaxim** [comment]
Since this is also meant for Erik's app shouldn't there be a pull request for the maint_v3.x branch?

**Comment by liaxim** [comment]
gvr-3dcursor-simple still fails for me with
```
12-07 07:38:42.550  6520  6634 W System.err: java.lang.IllegalArgumentException: Num of children in model:0 does not match the states array:4
12-07 07:38:42.553  6520  6634 W System.err: 	at org.gearvrf.io.cursor3d.SelectableBehavior.onAttach(SelectableBehavior.java:196)
12-07 07:38:42.553  6520  6634 W System.err: 	at org.gearvrf.GVRComponent.setOwnerObject(GVRComponent.java:98)
12-07 07:38:42.554  6520  6634 W System.err: 	at org.gearvrf.GVRSceneObject.attachComponent(GVRSceneObject.java:355)
12-07 07:38:42.554  6520  6634 W System.err: 	at org.gearvrf.io.cursorsimple.CursorMain.onInit(CursorMain.java:99)
12-07 07:38:42.554  6520  6634 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
12-07 07:38:42.554  6520  6634 W System.err: 	at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
12-07 07:38:42.554  6520  6634 W System.err: 	at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:126)
12-07 07:38:42.554  6520  6634 W System.err: 	at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
12-07 07:38:42.554  6520  6634 W System.err: 	at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
12-07 07:38:42.554  6520  6634 W System.err: 	at org.gearvrf.GVRViewManager$1$1.run(GVRViewManager.java:333)
12-07 07:38:42.554  6520  6634 W System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
12-07 07:38:42.554  6520  6634 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-07 07:38:42.554  6520  6634 W System.err: 	at android.os.Looper.loop(Looper.java:154)
12-07 07:38:42.554  6520  6634 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by NolaDonato** [comment]
I have fixed the issue with gvr-lua by making the fix even less aggressive. I also made a pull request for maint_v3.x

**Comment by liaxim** [comment]
Looks good to me. No problems with the demos. Can be merged.

On a side note, with and without this change, canLoadX3DModelWithoutLights fails.

**Pull request closed without merging**
