### PR TITLE
Fix problem with some of the demos that have custom shaders that are using GLSL ES version 100.

### PR DESCRIPTION
**Pull request by liaxim**
For example gvr-inputsample has a problem without this fix.

---
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@roshanch Please review.

**Comment by roshanch** [comment]
looks good to me.

**Comment by liaxim** [comment]
@NolaDonato I think you were going to review this change. Please let us know when we can merge it.

**Comment by liaxim** [comment]
Last pull request for the release. Will kick off a build and upload the binaries.

**Pull request merged**
