### PR TITLE
Integrate full Jassimp and upgrade assimp headers

### PR DESCRIPTION
**Pull request by danke-sra**
This port of Jassimp supports full assimp functionality. In addition to what we had, it can now access lights, cameras, bones and animations from Java.

This patch set also provides a way to convert AiScene to GVRf scene graph in pure Java. This makes GVRf easier to maintain for assimp/jassimp changes. User-defined hooks can be added to instantiate classes during the conversion process.

Optimized assimp loader performance from O(N) to O(1).

### CODE REVIEW

**Comment by lokeshguddu** [comment]
Hi @danke-sra ,

All the changes looks good and was much needed improvement. I was working on something which required loading models from SD card and I see that you have taken care of those cases as well. The complexity improvement is really great. :+1:

**Comment by thomasflynn** [comment]
@vittal and @roshanch  still waiting for your reviews on this.

**Comment by Vittalbabu** [comment]
Changes look good. I haven’t run with this version of assimp locally – might get to that in a day.

**Comment by Vittalbabu** [comment]
@danke Will we be updating the importer to use the new jassimp functions?

**Comment by danke-sra** [comment]
@Vittalbabu Yes, we will be having one jassimp as you suggested. But maybe we can change it a bit later after the new one has been adequately tested.

**Pull request merged**
