### PR TITLE
Detect transparency in ASTC.

### PR DESCRIPTION
**Pull request by thomasflynn**
Detect transparency in ASTC.  ASTC files will scan their Color Endpoint
Modes to tell if the file has transparency or not.

GearVRf-DCO-1.0-Signed-off-by: Tom Flynn
tom.flynn@samsung.com

### CODE REVIEW

**Comment by thomasflynn** [comment]
need to write some tests before it's ready for review.

**Comment by thomasflynn** [comment]
i should also probably tone down the logging :)

**Comment by NolaDonato** [comment]
Transparency tests now have their own class and each test is a separate function.  This is different than your original test.

**Comment by mwitchwilliams** [comment]
I can build some quick tests in X3D with animations of texture maps with transparency moving in front of and behind opaque objects. What do we expect to see different after implementing this change?
Is this an additional fix to https://github.com/Samsung/GearVRf/issues/1203 ? (see screen shots captured in the PR)

**Comment by thomasflynn** [comment]
prior to this change anything with an ASTC texture was treated as transparent since there was no way to tell in the header information.  Now we parse through and read the block endpoint information so we can tell if even an individual block has transparency.

in other words, prior to this change, even opaque ASTC textures were reported as transparent.  with this change, they are recognized properly.

I'm looking to add some tests to GearVRf-Tests -> framework -> TextureTransparencyTests.java.

**Comment by thomasflynn** [comment]
Added tests in:  https://github.com/gearvrf/GearVRf-Tests/pull/224
I think this is ready for review now.

**Comment by liaxim** [comment]
Works as expected. Tested by using the automated tests and supplying few astc textures I encoded myself. Planning to merge on Wednesday.

**Pull request merged**
