### PR TITLE
Fix access to the native config manager

### PR DESCRIPTION
**Pull request by rahul27**
GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by rahul27** [comment]
@apjagdale let me know if this looks right to you.

**Comment by apjagdale** [comment]
Works on Note 4 with oculus.

**Comment by thomasflynn** [comment]
when this gets merged, can you make sure it is cherry picked over to 3.1.1?  thanks.

**Comment by rahul27** [comment]
Will do.

**Pull request merged**
