### PR TITLE
Remove EyePointee references and refactor EyePointeeHolder as GVRColliderGroup

### PR DESCRIPTION
**Pull request by J0Nreynolds**
This PR features the removal of the deprecated GVREyePointee class and replacement of any references with GVRCollider. 

Similarly, the GVREyePointeeHolder class has been refactored as a GVRColliderGroup, allowing multiple colliders to be attached to a single GVRSceneObject.

### CODE REVIEW

**Comment by liaxim** [comment]
Looks good to me. Planning to merge Thursday morning. Erik's app will require a minor update I will take care of.

**Comment by liaxim** [comment]
Actually these demo apps need to be update. Please take a look at them:
```
gvr-controls
gvr-keyboard
gvr-modelviewer2
```

**Comment by J0Nreynolds** [comment]
Demos have been updated. See [here.](https://github.com/gearvrf/GearVRf-Demos/pull/469)

**Comment by liaxim** [comment]
Looks good. Planning to merge on Monday.

**Pull request merged**
