### PR TITLE
Support for occulus 1.0.3

### PR DESCRIPTION
**Pull request by roshanch**
GearVRf-DCO-1.0-Signed-off-by: Roshan Chaudhari
roshan.c@samsung.com

### CODE REVIEW

**Comment by thomasflynn** [comment]
need DCO.
does the volume notifier work?

**Comment by roshanch** [comment]
Yes, tested with immersivepedia. Also tested with samples simplesample, modelviewer and complexscene.

**Comment by liaxim** [comment]
Then all you need is the DCO and we can merge it.

**Comment by liaxim** [comment]
Will merge in the afternoon

**Comment by rahul27** [comment]
This change is not backward compatible with 1.0.0.1:

```
jni/oculus/activity.cpp: In member function 'void gvr::GVRActivity::onSurfaceChanged(JNIEnv&)':
Error:error: 'struct ovrModeParms' has no member named 'Flags'
         parms.Flags |=AllowPowerSave;
               ^
Error:error: 'struct ovrModeParms' has no member named 'Flags'
         parms.Flags |=ResetWindowFullscreen;
               ^
[armeabi-v7a] Compile++ arm  : gvrf <= oes_shader.cpp
```

Does it mean that we are forcing everyone to update to 1.0.3?

**Comment by liaxim** [comment]
This is how we have always proceeded. Support the latest without backwards compatibility.

**Comment by thomasflynn** [comment]
We will probably need to do a 3.0.1 release to match.

**Pull request merged**
