### PR TITLE
Unbind buffers before calling into the external renderer

### PR DESCRIPTION
**Pull request by liaxim**
Philippe pointed out the problem. VRTop finally is working pretty well.

### CODE REVIEW

**Comment by liaxim** [comment]
The way it is, it is as close as possible to the place that has this special requirement. No other code in the framework cares about this thing. This is the reason I put it there.

**Comment by danke-sra** [comment]
Ok. It's ok to keep it here. However, I've heard from another developer @rahul27 that this two lines are code are also missing for what he is doing. We then need to keep an eye for anything that may break by this...

**Comment by liaxim** [comment]
@rahul27 should let us know what the problem is. What I do know is that without these two lines, the external renderer does not work on hybrid.

**Comment by rahul27** [comment]
@danke-sra @liaxim For some of the stuff I am working on I wanted to make straight OpenGL calls at the application level i.e. inside onInit() and onStep(). In my case the draw calls failed and the glReadPixels() call always returned 0s, adding the two lines from this patch fixed that issue. To me it seems like this call should be made once the Oculus renderer is done with its drawing so that the buffers are reset for the application or any other external renderer to start drawing outside the GVRf context. 

You will find very simplified example of my OpenGL application here:

https://github.com/rahul27/GearVRf/tree/opengl

**Comment by liaxim** [comment]
@rahul27 regardless of the issue, you shouldn't be making direct GL calls from the app. GVRF is supposed to suffice so let us know what GVRF doesn't do for you.

You can't assume anything about what is going on behind the scenes in GVRF so your GL calls may or may not work, the app might crash, etc.

**Comment by thomasflynn** [comment]
more importantly, an application trying to make its own OpenGL calls cannot make any assumption about OpenGL state.  i haven't gotten to testing the libgdx plugin, but the same would apply there.  (if i understand correctly, libgdx makes its own gl calls).

**Comment by thomasflynn** [comment]
ok, i've gotten a little lost in the discussion here.  merge or don't merge?

**Comment by danke-sra** [comment]
I am neutral -- would prefer it to limit the scope of the leaked buffer binding (from Oculus). let others speak.

**Comment by Vittalbabu** [comment]
It is not be good to allow an app. to dictate how the internal state should be modified. How do we arbitrate conflicting requests to set state?

I second Mihail's comment -- let's us know what is missing in GVRF and we will see if that can be added.

**Comment by thomasflynn** [comment]
this pull-request is dealing with the external renderer and external renderer only.  

unfortunately, no matter we say, there will always be app writers who will make their own OpenGL calls whenever they can get their hands on something executing in a GL thread.  I've been through this before in other scenegraph projects.  We just need to make sure it is clear that the app writers cannot assume any OpenGL state is in the state they expect when they make their calls.

**Comment by rahul27** [comment]
@thomasflynn @liaxim if developers aren't supposed to be making OpenGL calls at the app level then this fix works.

**Pull request merged**
