### PR TITLE
Fix addLight's return value

### PR DESCRIPTION
**Pull request by liaxim**
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@NolaDonato Please review

**Comment by NolaDonato** [comment]
This is fine but it is pretty much the same as in PR #701

**Comment by liaxim** [comment]
Didn't realize that. Had a problem with it in another branch. Will close this.

**Comment by NolaDonato** [comment]
I am working on synchronizing the light list and will commit that change soon

**Pull request closed without merging**
