### PR TITLE
Backend's setMain delegate returns result; call onUndock from onDestroy if requested

### PR DESCRIPTION
**Pull request by liaxim**
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@sukhwanyoon needs handleOnDock to be called from onCreate. It was a problem in the past. Will look into making it possible.

**Comment by sukhwanyoon** [comment]
By the way, regardless of the handleOnDock issue, backend setMain having a returning value should be there when it comes to how landscape/portrait apps are handled appropriately by android platform.

**Comment by sukhwanyoon** [comment]
Hi. Mihail,
It works for me now.
Thanks.
Sean,

**Comment by liaxim** [comment]
@sukhwanyoon Since you've given thumbs up, I am planning to merge this pull request Thursday afternoon.

**Pull request merged**
