### PR TITLE
backend_oculus: silence the "WARNING:...: non-system libraries in linker flags" for good

### PR DESCRIPTION
**Pull request by liaxim**
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by dnvasilev** [comment]
Something went wrong:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gvr-simplesample:transformNativeLibsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libgvrf.so
  	File1: /home/d.vasilev/GVRFCurrent/GearVRf/GVRf/Framework/backend_oculus/build/intermediates/bundles/release/jni
  	File2: /home/d.vasilev/GVRFCurrent/GearVRf/GVRf/Framework/framework/build/intermediates/bundles/release/jni

**Comment by liaxim** [comment]
Have you tried cleaning first?

**Comment by liaxim** [comment]
The clean should be a one-time thing

**Comment by dnvasilev** [comment]
Fails after git clean -dxf
Checked twice

**Comment by dnvasilev** [comment]
Config: Android Studio 2.3.3, Framework+gvr-simplesample using ../extra_settings.gradle, build and run from Android Studio

**Comment by liaxim** [comment]
Build error fixed

**Comment by liaxim** [comment]
Will merge on Thursday

**Pull request merged**
