### PR TITLE
3.1 NPE fix in GVRConfigurationManager

### PR DESCRIPTION
**Pull request by liaxim**

### CODE REVIEW

**Comment by liaxim** [comment]
Tom, this is the most innocent fix I could think of. This pull request is for the 3.1 branch so it can't be committed. If it works, we need to decide on having a 3.1.1 release and what goes into it.

**Comment by thomasflynn** [comment]
ok, this fixes the crash, but now i have a weird problem where it just goes to oculus home after i dock it.  i'm not seeing anything obvious in the logs.  i'll show you tomorrow.

**Comment by liaxim** [comment]
@thomasflynn vr_only is missing from your AndroidManifest.xml. It is very likely your original problem had something to do with it too. Reference manifest: https://github.com/gearvrf/GearVRf-Demos/blob/master/template/GVRFApplication/app/src/main/AndroidManifest.xml

**Comment by thomasflynn** [comment]
Do-oh!  that would likely explain it!  I'll verify later tonight...

**Comment by thomasflynn** [comment]
OK, the fix is still needed.  The manifest entries are necessary for it to launch correctly and not go to occlus home (how long have I been doing this and missed that?), but I still get the crash on dock from developer mode without your fix.

**Comment by liaxim** [comment]
Created https://github.com/Samsung/GearVRf/pull/1062 for the 3.1.1 release instead

**Pull request closed without merging**
