### PR TITLE
Fix problem with picking test "canPickMeshWithObject" 

### PR DESCRIPTION
**Pull request by NolaDonato**
This test creates a picker, starts listening for pick events and then attaches the picker to a scene object. This can cause false events to be generated between the time the picker starts listening and the time it is attached. This constructor eliminates the problem by attaching the picker first and then starting to listen for events.

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
How come false events can be generated in first place?

**Comment by liaxim** [comment]
Bundles the changes from the https://github.com/Samsung/GearVRf/pull/1122 pull request. Can't merge unless https://github.com/Samsung/GearVRf/pull/1122 is ready then.

**Comment by NolaDonato** [comment]
#1122 doesn't actually fix all the  physics crashes - one is actually due to shadow mapping. But it does implement some thread safety that was lacking and guards against a null pointer. So it does no harm and does prevent re-entrant calls to the physics solver.

**Comment by NolaDonato** [comment]
replaced by #1129

**Pull request closed without merging**
