### PR TITLE
Fix problem with picking test "canPickMeshWithObject"

### PR DESCRIPTION
**Pull request by NolaDonato**
This test creates a picker, starts listening for pick events and then attaches the picker to a scene object. This can cause false events to be generated between the time the picker starts listening and the time it is attached. This constructor eliminates the problem by attaching the picker first and then starting to listen for events.
Replaces PR #1124

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

This is for https://github.com/gearvrf/GearVRf-Tests/pull/78

### CODE REVIEW

**Comment by liaxim** [comment]
Pending verification with https://github.com/gearvrf/GearVRf-Tests/pull/78

**Comment by liaxim** [comment]
The updated test still doesn't pass for me.

**Comment by rahul27** [comment]
The test passes now.

**Comment by liaxim** [comment]
The test passes for me too.

**Pull request merged**
