### PR TITLE
Add Java math library for OpenGL rendering calculations (JOML)

### PR DESCRIPTION
**Pull request by danke-sra**
Add new API GVRTransform.setModelMatrix(Matrix4f) and getModelMatrix4f
to use the JOML matrix.

Add OpenGL-compatible vectors and matrix classes.

Fix for https://github.com/Samsung/GearVRf/issues/177

### CODE REVIEW

**Comment by liaxim** [comment]
Not sure about this dependency just to wrap the matrix.

**Comment by danke-sra** [comment]
This puts a convenient matrix library at GVRf developer's hands. As I tried to dogfood gvrf and write some app, I found it's still needed. I can't do anything with float[16]. This is probably why the original poster opened the issue. One thing to clarify is that it is *NOT* for the transform only or manipulate native-backed data structures. It's just standard tool for developers to avoid divergence.

**Comment by liaxim** [comment]
You can choose any external library you want to use with a float[16]. No need for GVRF to make this choice.

**Comment by thomasflynn** [comment]
there's also the apache commons library we include and Android has the android.opengl.Matrix classes as well.

**Comment by danke-sra** [comment]
OK, if it's not needed, it can be canceled for now. This library is optimized for OpenGL's mat 4x4, 4x3, etc. Apache commons are for more general math purposes.

**Pull request closed without merging**
