### PR TITLE
Bring up the VR volume ui automatically

### PR DESCRIPTION
**Pull request by liaxim**
Based off Rahul's code

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@rahul27 Please let me know what you think. Thanks.

**Comment by liaxim** [comment]
Reacting to action_down instead.

**Comment by rahul27** [comment]
:+1: Looks good.

**Comment by deepakrawat22** [comment]
@liaxim Why use AudioManager.STREAM_MUSIC, what if no music is playing in background ?

**Comment by liaxim** [comment]
@deepakrawat22 Good question; two reasons:
- that is what other people use (see ovr_mobile_sdk/VrAppFramework/java/com/oculus/vrappframework/VrActivity.java:adjustVolume
- if the app was to play music I'd imagine that would be the type of audio stream in use so this is the volume you want to change regardless of the current status

What do you think?

**Comment by liaxim** [comment]
Had a chat with @deepakrawat22 . This is better than what we had before. The standard volume UI shows up in addition if the phone is not docked (if docked everything works as expected). @deepakrawat22 will have a look and maybe fix that or create an issue so we don't lose track of this quirk.

**Comment by liaxim** [comment]
Will merge after lunch if there are no comments

**Pull request merged**
