### PR TITLE
Clear bounding volume before calculating bounds for mesh

### PR DESCRIPTION
**Pull request by liaxim**
Nola's fix; can't cherry-pick it

### CODE REVIEW

**Comment by thomasflynn** [comment]
we'll need to ensure frustum culling and hierarchical frustum culling are still working as precisely after this change.  that'd be the only thing i'm worried about this affecting.

**Comment by liaxim** [comment]
Tried immersivepedia with stats enabled. Collected information when looking at each individual dinosaur, when focused on the dinosaur menu in the menu scene. The number of draw calls and triangles looks to be the same with or without this change.

Any suggestions how to study the impact further?

**Comment by thomasflynn** [comment]
yeah, two things i can think of:
1) check the accuracy and draw calls for solar-system
2) ditto for the jassimp sample with AstroBoy

**Comment by liaxim** [comment]
With jassimp's AstroBoy I am getting the same number of draw calls and triangles when looking at the same parts of the model with and without this change.

**Comment by thomasflynn** [comment]
and i checked the solar-system sample.  awesome.  thanks for checking.

**Pull request merged**
