### PR TITLE
Fix issue with running immersivepedia 

### PR DESCRIPTION
**Pull request by Vittalbabu**
Fix issue with running immersivepedia -- in the non multiview case, extension GL_OES_EGL_image_external_essl3 is needed.

### CODE REVIEW

**Comment by roshanch** [comment]
GL_OES_EGL_image_external_essl3  only works for Adreno, for Mali, you need GL_OES_EGL_image_external.

**Comment by Vittalbabu** [comment]
Good point. Let's figure out a cleaner solution than this.

**Comment by Vittalbabu** [comment]
How about having two shaders -- instead of using #ifdef we pick the appropriate source. We use the old shader that worked for the non-multiview case.

**Comment by liaxim** [comment]
@Vittalbabu Should we close this?

**Comment by Vittalbabu** [comment]
Yes

**Pull request closed without merging**
