### PR TITLE
New gradle tasks for the GitHub releases

### PR DESCRIPTION
**Pull request by liaxim**
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
Added a releaseToGitHub build target that should produce the aar without files we can't re-distribute.

Added a eclipseReleaseForGitHub task that produces a zipped Android Library project for Eclipse users.

**Comment by liaxim** [comment]
Am not liking the scripts but they are functional. Prettifying can wait.

**Comment by liaxim** [comment]
Btw, this change will make it so that the Oculus dependencies will be automatically copied *if* the gradle.properties is modified according to the wiki. In any case we should stop relying on the PATH and the rest of the environment variables. This has been proven finicky for most people to get right.

Planning to merge this lunch-time. It is a stepping stone towards the nightly build release. I am pretty sure it will break the automated build but I need the change in to find out what else needs work.

**Comment by jason2kim** [comment]
If the team decides to go with no prebuilt binary for Eclipse users, I think it is time to drop the gvr video staticlib, too.

**Comment by liaxim** [comment]
Whatever the team decides we currently cannot have a single file prebuilt binary for Eclipse. It is just not possible.

Whether we want to make code changes to somehow achieve that and whether we should is a different topic altogether.

I personally think we shouldn't waste too much time with Eclipse.

**Comment by jason2kim** [comment]
Talked with team members on this. People agreed to go without libs-gvrf.zip for Eclipse. And thus, gvr-video-staticlib.

**Comment by liaxim** [comment]
Thank you. Will remove the staticlib sample.

**Pull request merged**
