### PR TITLE
Update the framework build tools to 2.3.1

### PR DESCRIPTION
**Pull request by rahul27**
GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Should the extensions build be updated too?

**Comment by liaxim** [comment]
Looks good. Worked in my tests.

**Comment by rahul27** [comment]
Will update extensions once https://github.com/Samsung/GearVRf/pull/1131 is merged.

**Comment by liaxim** [comment]
Looks good. Will merge in the afternoon.

**Pull request merged**
