### PR TITLE
Fixing shaders of OESVerticalStereo and OESHorizontalStereo #1671

### PR DESCRIPTION
**Pull request by apjagdale**
Shaders OESVerticalStereo and OESHorizontalStereo were not ported for the 4.0 changes.

GearVRF DCO signed off by: Abhijit Jagdale a.jagdale@samsung.com

### CODE REVIEW

**Comment by roshanch** [comment]
looks good.. we can merge this.

**Comment by thomasflynn** [comment]
how was this tested?  (what app / videos?)  and on what hardware?

**Comment by apjagdale** [comment]
@thomasflynn I had modified gvr-sceneobjects demo and had changed VideoTypes in it.

**Comment by thomasflynn** [comment]
was it tested on both Mali and Adreno?

**Comment by apjagdale** [comment]
@thomasflynn I tested on Adreno only.

**Comment by thomasflynn** [comment]
ok, tested on Mali.  can verify the shaders compile and do not produce errors.  however, i do see this output every frame:

12-29 11:52:01.229 30675 30751 V gvrf    : DataDescriptor: mat4 u_bone_matrix[60]

I don't think that was introduced by this check-in, i'll merge this anyway.  But we should squash any per-frame log output that isn't an error.

**Comment by thomasflynn** [comment]
Wait.  Maybe it _was_ introduced by this check-in.  I do not see this log output with a video type of MONO.

**Comment by thomasflynn** [comment]
ok, talked with @NolaDonato.  I'm going to go ahead and merge this and she's gonna figure out where that debug log is coming from and fix it.

**Comment by liaxim** [comment]
Debug log silenced in https://github.com/Samsung/GearVRf/pull/1696. What is concerning that a DataDescriptor is created continuously. Look like a particular RenderData instance is always dirty.

**Comment by NolaDonato** [comment]
PR #1679 silences this log by fixing the problem in GVRShader.java

**Pull request merged**
