### PR TITLE
Support Android gradle plugin v2.2.3

### PR DESCRIPTION
**Pull request by liaxim**
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
This version supports externalNativeBuild and other enhancements. externalNativeBuild means that after some updates to our gradle files we may no longer need the separate project files for the experimental plugin.

**Comment by liaxim** [comment]
@deepakrawat22 Please review.

**Comment by deepakrawat22** [comment]
Was able to build successfully and run the demo.

**Comment by liaxim** [comment]
The version is now up to 2.2.3. Updated the pull request.

**Comment by liaxim** [comment]
Will merge after lunch

**Comment by rahul27** [comment]
Can we merge this now? I can update my PR accordingly.

**Comment by liaxim** [comment]
Sure

**Pull request merged**
