### PR TITLE
Set MotionEvents in GearCursorController

### PR DESCRIPTION
**Pull request by J0Nreynolds**
This PR sets MotionEvents for the GearCursorController. It also enables one to query if the touchpad of the GearVR controller is being touched (not pressed down).

### CODE REVIEW

**Comment by J0Nreynolds** [comment]
GearVRf-DCO-1.0-Signed-off-by: Jonathan Reynolds j.reynolds@partner.samsung.com

**Comment by NolaDonato** [comment]
Upon inspection this pull request seems like it will add touchpad support. I cannot find a test program for it. I think we should go ahead and merge. It does not break the gvr-controller demo.

**Comment by liaxim** [comment]
I can see the motion events being sent to the ControllerEventListener.

**Comment by liaxim** [comment]
gvr-controller, prior to this pull request but must have happened in the last month or so:
- the controller model can just freeze somewhere
- the object selected by the controller can flash at the origin for a frame or two

**Pull request merged**
