### PR TITLE
Fix the daydream default FBO and UV values

### PR DESCRIPTION
**Pull request by rahul27**
GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Depends on https://github.com/Samsung/GearVRf/pull/1110 being merged

**Comment by liaxim** [comment]
Blocked by 1110. Not sure when I can get back to it.

**Comment by liaxim** [comment]
Needs rebase

**Comment by rahul27** [comment]
Done.

**Comment by liaxim** [comment]
Looks good. Will merge in the afternoon.

**Pull request merged**
