### PR TITLE
widgetplugin: ensure wp's surfaceview doesn't obscure the main one

### PR DESCRIPTION
**Pull request by liaxim**
Fix for https://github.com/Samsung/GearVRf/issues/1819
Will test and address for other backends separately

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@NolaDonato Please verify that this fix addresses the widgetplugin problem on your phone. Thanks.

**Comment by NolaDonato** [comment]
Do you mean the Android O phone or the Android N phone?

**Comment by liaxim** [comment]
Android O

**Comment by liaxim** [comment]
@NolaDonato Verified on your phone. Without this fix gvr-widgetviewer and gvr-modelviewer2 are mostly obscured by black. With this fix they work as expected. I guess something was off with your build.

**Comment by liaxim** [comment]
Since I verified the fix on Nola's phone I am planning to merge this on Wednesday.

**Pull request merged**
