### PR TITLE
Spheretexture

### PR DESCRIPTION
**Pull request by rongguodong**
GearVRf-DCO-1.0-Signed-off-by: Guodong Rong
rongguodong@hotmail.com

### CODE REVIEW

**Comment by chenchao1407** [comment]
Hi. guodong

It seems that this pull request overlaps with the previous request because both has commit " Fix the problem of missing cap of cylinder." If you don't mind I will close previous one.

**Comment by rongguodong** [comment]
Oh, yes. I created a new branch from that one. You can close that one, and just merge this one.

**Comment by chenchao1407** [comment]
Code looks good. Issues fixed.

**Comment by thomasflynn** [comment]
awesome.  code looked fine.  glad the fixes ended up being small.  if you've verified it, go ahead and merge it.

**Comment by phyuzion** [comment]
That exactly what I need! :)

**Pull request merged**
