### PR TITLE
adding support for egl_image for different vendors in oes shader

### PR DESCRIPTION
**Pull request by roshanch**
This is to support different vendors for GL_OES_EGL_image_external. 
If multiview is disabled, it will use GLSL 100. 
Simple gallery still has problem with multiview, we need to run it without multiview. However, other sample works with multiview + OES shader. 
Simple gallery is giving different errors on different vendors with multiview.

### CODE REVIEW

**Comment by liaxim** [comment]
Samples work. Will merge in the afternoon.

Shouldn't you enable multiview support for all the samples you know that work with it?

**Comment by roshanch** [comment]
do you mean by default in xml file ?

**Comment by liaxim** [comment]
yes

**Comment by roshanch** [comment]
Okay, I will add that.

**Pull request merged**
