### PR TITLE
Remove rigid body from physics world

### PR DESCRIPTION
**Pull request by NolaDonato**
Add GVRComponent.onRemoveFromScene which is called when the component's
owner is removed from the scene. GVRRigidBody overrides it to remove the
object from the physics world.

This pull request requires PR #880.

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by ragner** [comment]
Hi @NolaDonato,
I think we could make some GVRComponent.onOwnersParentChanged(GVRSceneObject parent).

So, I could implement a better logic to add/remove the RigidBody from the world.

I can follow your thoughts from this patch and implement that GVRComponent.onOwnersParentChanged().

**Comment by ragner** [comment]
I mean, when a SceneObject is added to the Scene we could  just àddToWorld()` function
and when it is removed just call `removeFromWorld()` function.

The attach/detach logic keeps just to onAttach/onDetach of the Component.

**Comment by liaxim** [comment]
Should we close this one?

**Comment by ragner** [comment]
Yes,
It already is in  #880

**Comment by NolaDonato** [comment]
yes

**Pull request closed without merging**
