### PR TITLE
Catch exceptions from "user" callbacks

### PR DESCRIPTION
**Pull request by liaxim**
Keep the branch up-to-date.

### CODE REVIEW

**Comment by rahul27** [comment]
@liaxim what is the reason behind this change? and was "onInit" left out intentionally?

**Comment by liaxim** [comment]
Not having random "user" exceptions escape uncontrollably on the rendering thread and inducing obscure crashes? In privileged apps it could lead to much weirder outcomes.

The onInit is an example how we should go about this - in that case finish the activity. Maybe we should do that too in other cases or bring up a common error dialog and shutdown gracefully. Before any of these, we can put up some defenses.

**Comment by rahul27** [comment]
I see. But wouldn't this change make it even more difficult for developers to know something is wrong?Assume that you have an NPE in onStep(), it would go unnoticed by the app which would resume like nothing is wrong.

Unless like you mentioned, you are planning on implementing a dialog to let the user know that there is an error followed by a subsequent finish().

**Comment by liaxim** [comment]
The exception is printed in logcat. I do agree with you but these exceptions if unhandled get into jni and can get harder to decipher.

I believe for now we should gracefully shutdown the app but something like this will require a discussion.

**Pull request merged**
