### PR TITLE
GVRConsole tweaks

### PR DESCRIPTION
**Pull request by liaxim**
- increase default text size
- update the fragment shader to mix so the overlay texture is
more of an overlay

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
Have to update couple of samples due to the different default text size. Left-only, right-only worked fine for me.

**Comment by thomasflynn** [comment]
the stats look like they need their fudge factor adjusted (so they are visible while inside the headset), but otherwise looks good.

**Comment by liaxim** [comment]
Adjusted the console x and y offsets used for the scene stats.

**Comment by liaxim** [comment]
Using the offsets @thomasflynn suggested

**Comment by thomasflynn** [comment]
ok, looks good.

**Pull request merged**
