### PR TITLE
Support for GVRExternalTexture in GVRVideoSceneObject

### PR DESCRIPTION
**Pull request by deepakrawat22**
A GVRExternalTexture can be provided to create a VideoScene object. This way a MediaPlayer can be shared among multiple GVRVideoSceneObject, also the GVRExternalTexture can be used by application.

GearVRf-DCO-1.0-Signed-off-by: Deepak Rawat
deepak.rawat@samsung.com

### CODE REVIEW

**Comment by thomasflynn** [comment]
@NolaDonato have you reviewed this yet?

**Comment by NolaDonato** [comment]
No, not yet. I will do it tonight.

**Comment by NolaDonato** [comment]
I tested it with gvr-immersivepedia and gvr-360video on the Note 4 and it works.

When I tested it with gvr-video the video does not show:
06-02 23:54:37.118: E/GLConsumer(5694): [unnamed-5694-0] checkAndUpdateEglState: invalid current EGLDisplay
06-02 23:54:37.118: E/GVRViewManager(5694): Exception from onStep: java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
06-02 23:54:37.118: W/System.err(5694): java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
06-02 23:54:37.118: W/System.err(5694): 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
06-02 23:54:37.118: W/System.err(5694): 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:169)
06-02 23:54:37.118: W/System.err(5694): 	at org.gearvrf.video.VideoMain.onStep(VideoMain.java:682)
06-02 23:54:37.118: W/System.err(5694): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-02 23:54:37.118: W/System.err(5694): 	at java.lang.reflect.Method.invoke(Method.java:515)
06-02 23:54:37.118: W/System.err(5694): 	at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:306)
06-02 23:54:37.118: W/System.err(5694): 	at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:125)
06-02 23:54:37.118: W/System.err(5694): 	at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:112)
06-02 23:54:37.118: W/System.err(5694): 	at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:107)
06-02 23:54:37.118: W/System.err(5694): 	at org.gearvrf.GVRViewManager$3$1.run(GVRViewManager.java:781)
06-02 23:54:37.118: W/System.err(5694): 	at android.os.Handler.handleCallback(Handler.java:733)
06-02 23:54:37.118: W/System.err(5694): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-02 23:54:37.118: W/System.err(5694): 	at android.os.Looper.loop(Looper.java:146)
06-02 23:54:37.118: W/System.err(5694): 	at android.os.HandlerThread.run(HandlerThread.java:61)
06-02 23:54:37.118: E/GLConsumer(5694): [unnamed-5694-0] checkAndUpdateEglState: invalid current EGLDisplay
06-02 23:54:37.118: E/GVRViewManager(5694): Exception from onStep: java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)

When I tested with gvr-simplegallery I get a crash:
06-02 23:50:13.598: V/MediaPlayer(5286): message received msg=5, ext1=1280, ext2=720
06-02 23:50:13.598: V/MediaPlayer(5286): New video size 1280 x 720
06-02 23:50:13.598: V/MediaPlayer(5286): callback application
06-02 23:50:13.598: V/MediaPlayer(5286): back from callback
06-02 23:50:13.598: V/MediaPlayer(5286): message received msg=1, ext1=0, ext2=0
06-02 23:50:13.598: V/MediaPlayer(5286): prepared
06-02 23:50:13.598: V/MediaPlayer(5286): signal application thread
06-02 23:50:13.598: V/MediaPlayer(5286): callback application
06-02 23:50:13.598: V/MediaPlayer(5286): prepare complete - status=0
06-02 23:50:13.598: V/MediaPlayer-JNI(5286): start
06-02 23:50:13.598: V/MediaPlayer(5286): start
06-02 23:50:13.598: V/MediaPlayer(5286): back from callback
06-02 23:50:13.608: I/Vsync(5286): Vsync 15279028: vsync_event  : 81 x 16.70 ms (59.99 Hz, at 254650.464)
06-02 23:50:13.618: V/MediaPlayer(5286): setVideoSurfaceTexture
06-02 23:50:13.618: I/OVR(5286): DeviceManagerThread - poll(fds,1,998) = 0 (Tid=5306)
06-02 23:50:13.628: D/gvrf(5286):   # 0: 0x76de038c  _Z15printStackTracej
06-02 23:50:13.628: D/gvrf(5286):   # 1: 0x76dda8b0  
06-02 23:50:13.628: D/gvrf(5286):   # 2: 0x76ddbc1c  _ZN3gvr22CustomPostEffectShaderC1ESsSs
06-02 23:50:13.628: D/gvrf(5286):   # 3: 0x76dc2198  Java_org_gearvrf_NativePostEffectShaderManager_addCustomPostEffectShader
06-02 23:50:13.628: D/gvrf(5286):   # 4: 0x417ef0d0  dvmPlatformInvoke
06-02 23:50:13.628: D/gvrf(5286):   # 5: 0x4181fdb2  _Z16dvmCallJNIMethodPKjP6JValuePK6MethodP6Thread
06-02 23:50:13.628: D/gvrf(5286):   # 6: 0x4182179a  _Z22dvmResolveNativeMethodPKjP6JValuePK6MethodP6Thread
06-02 23:50:13.628: D/gvrf(5286):   # 7: 0x417f8564  
06-02 23:50:13.628: D/gvrf(5286):   # 8: 0x417ffa48  _Z11dvmMterpStdP6Thread
06-02 23:50:13.628: D/gvrf(5286):   # 9: 0x417fd0e0  _Z12dvmInterpretP6ThreadPK6MethodP6JValue
06-02 23:50:13.628: E/gvrf(5286): fatal error: no deleter associated with this thread!
06-02 23:50:13.628: A/libc(5286): Fatal signal 6 (SIGABRT) at 0x000014a6 (code=-6), thread 5301 (gvrf-main)
06-02 23:50:13.668: V/MediaPlayer(5286): message received msg=6, ext1=0, ext2=0

**Comment by liaxim** [comment]
The gvr-video issue is a threading problem. gvr-video is not calling updateTexImage on the right thread. The sample needs to be updated so it makes the call on the GL thread. I will look into it.

The change itself is innocent enough. Looks good to me.

**Comment by deepakrawat22** [comment]
Hi All,

I have updated the gvr-video app as well. #176 is the pull request where GVRVideoSceneObject is used in gvr-video app.

**Comment by NolaDonato** [comment]
gvr-simplegallery also crashed. Is it the same problem as with gvr-vidoe?

**Comment by liaxim** [comment]
@NolaDonato It is still a threading issue but the cause is CustomPostEffectShader/GVRPostEffectShaderManager.addShader. It needs updating so it can be used off the GL thread.

**Pull request merged**
