### PR TITLE
X3D Parser: added define and use for most object types 

### PR DESCRIPTION
**Pull request by NolaDonato**
This pull request replaces #607 (X3D parser first cut). It addresses
some of the comments on that PR.

GearVRf-DCO-1.0-Signed-off-by: nola.donato@samsung.com Nola Donato and m1.williams@partner.samsung.com Mitch Williams

### CODE REVIEW

**Comment by rahul27** [comment]
Is this patch ready for review?

**Comment by NolaDonato** [comment]
Not yet, I tried to make it asynchronously load textures and broke it.

**Comment by NolaDonato** [comment]
This patch now depends on PR #658 to read textures correctly. It compiles, it runs and loads some X3D models but can't find textures on the SD card without PR #658.

**Comment by NolaDonato** [comment]
Rebased and cleaned up version is PR #675

**Pull request closed without merging**
