### PR TITLE
Daydream: fix for gvr-shadows showing black screen

### PR DESCRIPTION
**Pull request by liaxim**
daydream doesn't like changing the currently bound fbo on it

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@rahul27 I also disabled the daydream intro screen (setTransitionViewEnabled(false)). Do you think this would be a problem? The screen gets really annoying after a while..

**Comment by rahul27** [comment]
I always assumed that this was the call to prompt the user to place the phone into the headset. Somewhat like the screen shown to the user with the Oculus SDK.

We can add it back if it is required for Daydream apps.

**Comment by liaxim** [comment]
Yes, it is that prompt. But it sits there forever unless you start moving the phone..

**Comment by liaxim** [comment]
Will merge tomorrow after lunch if there are no comments.

**Pull request merged**
