### PR TITLE
Upgraded Assimp version

### PR DESCRIPTION
**Pull request by NolaDonato**
Adds libraries for the latest version of assimp, includes two bug fixes to assimp involving OBJ import.
Fixed a bug in TGA import.

Has been tested with unit tests and a few apps, could use more testing.

GearVRF DCO submitted by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Will go through the demos and some internal apps

**Comment by liaxim** [comment]
3/4 of the samples are affected adversely. Seems like the root cause is this:

```
02-01 09:00:17.711 12019 12050 E art     : No implementation found for long org.gearvrf.NativeImporter.readFromByteArray(byte[], java.lang.String, int) (tried Java_org_gearvrf_NativeImporter_readFromByteArray and Java_org_gearvrf_NativeImporter_readFromByteArray___3BLjava_lang_String_2I)
02-01 09:00:17.711 12019 12050 W System.err: java.lang.reflect.InvocationTargetException
02-01 09:00:17.711 12019 12050 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
02-01 09:00:17.711 12019 12050 W System.err: 	at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
02-01 09:00:17.711 12019 12050 W System.err: 	at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:126)
02-01 09:00:17.711 12019 12050 W System.err: 	at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
02-01 09:00:17.711 12019 12050 W System.err: 	at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
02-01 09:00:17.711 12019 12050 W System.err: 	at org.gearvrf.GVRViewManager$1$1.run(GVRViewManager.java:318)
02-01 09:00:17.711 12019 12050 W System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
02-01 09:00:17.711 12019 12050 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-01 09:00:17.711 12019 12050 W System.err: 	at android.os.Looper.loop(Looper.java:158)
02-01 09:00:17.711 12019 12050 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-01 09:00:17.711 12019 12050 W System.err: Caused by: java.lang.UnsatisfiedLinkError: No implementation found for long org.gearvrf.NativeImporter.readFromByteArray(byte[], java.lang.String, int) (tried Java_org_gearvrf_NativeImporter_readFromByteArray and Java_org_gearvrf_NativeImporter_readFromByteArray___3BLjava_lang_String_2I)
02-01 09:00:17.711 12019 12050 W System.err: 	at org.gearvrf.NativeImporter.readFromByteArray(Native Method)
02-01 09:00:17.711 12019 12050 W System.err: 	at org.gearvrf.GVRAssetLoader.readFileFromResources(GVRAssetLoader.java:842)
02-01 09:00:17.711 12019 12050 W System.err: 	at org.gearvrf.GVRContext.loadMesh(GVRContext.java:285)
02-01 09:00:17.711 12019 12050 W System.err: 	at org.gearvrf.GVRContext.loadMesh(GVRContext.java:256)
02-01 09:00:17.711 12019 12050 W System.err: 	at org.gearvrf.opacityanigallery.GalleryMain.onInit(GalleryMain.java:64)
02-01 09:00:17.711 12019 12050 W System.err: 	... 10 more
```

**Comment by liaxim** [comment]
For example:
gvr-immersevipedia: shows nothing
gvr-jassimp: the astroboy is missing

**Comment by liaxim** [comment]
gvr-3dcursor is stuck at the splash screen; fails to load a bunch of of its resources:
```
02-06 09:06:37.551 19621 19666 E GVRAssetLoader: Star_OnClick.obj exception loading asset from Star_OnClick.obj
02-06 09:06:37.551 19621 19665 E GVRAssetLoader: astronaut_default.obj exception loading asset from astronaut_default.obj
02-06 09:06:40.421 19621 19665 E GVRAssetLoader: ASSET: ERROR: model r_hand_close.obj did not load Unable to open file "r_hand_close.obj".
02-06 09:06:40.291 19621 19669 E GVRAssetLoader: ASSET: ERROR: model cursor_sphere.obj did not load Unable to open file "cursor_sphere.obj".
```
gvr-3dcursor-simple unsurprisingly exhibits the same behavior.

**Comment by liaxim** [comment]
gvr-accessibility exits soon after it shows the splash screen:
```
02-06 09:11:14.321 20073 20204 E GVRAssetLoader: circle_menu.obj exception loading asset from circle_menu.obj
02-06 09:11:14.321 20073 20204 E GVRAssetLoader: ASSET: ERROR: model circle_menu.obj did not load Unable to open file "circle_menu.obj".
```

**Comment by liaxim** [comment]
gvr-bullet has models missing; different exceptions in logcat:
```
02-06 09:13:25.931 21073 21125 W System.err: java.lang.UnsupportedOperationException: error creating shader template of class GVRPhongShadernull
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.GVRMaterialShaderManager.retrieveShaderTemplate(GVRMaterialShaderManager.java:100)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.GVRRenderData.setShaderTemplate(GVRRenderData.java:434)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.GVRJassimpAdapter.createSubSceneObject(GVRJassimpAdapter.java:502)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.GVRJassimpAdapter.recurseAssimpNodes(GVRJassimpAdapter.java:388)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.GVRJassimpAdapter.recurseAssimpNodes(GVRJassimpAdapter.java:404)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.GVRJassimpAdapter.processScene(GVRJassimpAdapter.java:320)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.GVRAssetLoader.loadJassimpModel(GVRAssetLoader.java:1201)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.GVRAssetLoader.loadModel(GVRAssetLoader.java:1148)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.GVRContext.loadMesh(GVRContext.java:301)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.GVRContext.loadMesh(GVRContext.java:256)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.asynchronous.AsyncMesh$AsyncLoadMesh.loadResource(AsyncMesh.java:101)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.asynchronous.AsyncMesh$AsyncLoadMesh.loadResource(AsyncMesh.java:85)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.asynchronous.Throttler$AsyncLoader.run(Throttler.java:184)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.asynchronous.Throttler$PendingRequests$PendingRequest.run(Throttler.java:507)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.utility.Threads$ThreadLimiter$ThreadManager.run(Threads.java:521)
02-06 09:13:25.941 21073 21125 W System.err: 	at org.gearvrf.utility.Threads$1.run(Threads.java:108)
02-06 09:13:25.941 21073 21125 W System.err: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
02-06 09:13:25.941 21073 21125 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-06 09:13:25.941 21073 21125 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-06 09:13:25.941 21073 21125 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-06 09:13:25.941 21073 21125 W System.err: 	at java.lang.Thread.run(Thread.java:818)


02-06 09:13:25.941 21073 21113 W System.err: java.lang.ClassCastException: org.gearvrf.GVRTransform cannot be cast to org.gearvrf.GVRRenderData
02-06 09:13:25.941 21073 21113 W System.err: 	at org.gearvrf.GVRContext$1MeshFinder.visit(GVRContext.java:290)
02-06 09:13:25.941 21073 21113 W System.err: 	at org.gearvrf.GVRSceneObject.forAllComponents(GVRSceneObject.java:913)
02-06 09:13:25.941 21073 21113 W System.err: 	at org.gearvrf.GVRContext.loadMesh(GVRContext.java:303)
02-06 09:13:25.941 21073 21113 W System.err: 	at org.gearvrf.GVRContext.loadMesh(GVRContext.java:256)
02-06 09:13:25.941 21073 21113 W System.err: 	at org.gearvrf.asynchronous.AsyncMesh$AsyncLoadMesh.loadResource(AsyncMesh.java:101)
02-06 09:13:25.941 21073 21113 W System.err: 	at org.gearvrf.asynchronous.AsyncMesh$AsyncLoadMesh.loadResource(AsyncMesh.java:85)
02-06 09:13:25.941 21073 21113 W System.err: 	at org.gearvrf.asynchronous.Throttler$AsyncLoader.run(Throttler.java:184)
02-06 09:13:25.941 21073 21113 W System.err: 	at org.gearvrf.asynchronous.Throttler$PendingRequests$PendingRequest.run(Throttler.java:507)
02-06 09:13:25.941 21073 21113 W System.err: 	at org.gearvrf.utility.Threads$ThreadLimiter$ThreadManager.run(Threads.java:521)
02-06 09:13:25.941 21073 21113 W System.err: 	at org.gearvrf.utility.Threads$1.run(Threads.java:108)
02-06 09:13:25.941 21073 21113 W System.err: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
02-06 09:13:25.941 21073 21113 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-06 09:13:25.941 21073 21113 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-06 09:13:25.941 21073 21113 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-06 09:13:25.941 21073 21113 W System.err: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by liaxim** [comment]
gvr-immersivepedia exhits after showing the splash screen:
```
02-06 09:16:25.771 22017 22045 E GVRAssetLoader: styracosaurus_mesh.fbx exception loading asset from styracosaurus_mesh.fbx
02-06 09:16:25.771 22017 22045 E GVRAssetLoader: ASSET: ERROR: model styracosaurus_mesh.fbx did not load Unable to open file "styracosaurus_mesh.fbx".
```
Will not go through all of the demos. Let me know how I can be of assistance.

**Comment by NolaDonato** [comment]
I fixed the problem with reading meshes using resource IDs which was causing the immersivepedia crash. I tested with modelviewer2 (all the jassimp assets) and immersivepedia. All the jassimp models work except bmw.FBX which seems to show misplaced geometry. I will compare with master to see if it works there.

**Comment by liaxim** [comment]
gvr-3dcursor now crashes with

```
02-07 13:31:46.511  7278  7315 W TimeWarp: VSync 22133116: eye=1,late=0.0ms,over=0.0ms,CPU=2.4ms,GPU>=5.9
02-07 13:31:46.621  7278  7325 D GVRAssetLoader: ASSET: loading astronaut_onbehind.obj ...
02-07 13:31:46.771  7278  7321 F art     : art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
02-07 13:31:46.771  7278  7321 F art     : art/runtime/java_vm_ext.cc:410]   at void org.gearvrf.GVRAndroidResource.closeStream() (GVRAndroidResource.java:312)
02-07 13:31:46.771  7278  7321 F art     : art/runtime/java_vm_ext.cc:410]   at byte[] org.gearvrf.GVRAssetLoader$ResourceVolumeIO.read(java.lang.String) (GVRAssetLoader.java:898)
02-07 13:31:46.771  7278  7321 F art     : art/runtime/java_vm_ext.cc:410]   at byte[] org.gearvrf.GVRAssetLoader$CachedVolumeIO.read(java.lang.String) (GVRAssetLoader.java:924)
02-07 13:31:46.771  7278  7321 F art     : art/runtime/java_vm_ext.cc:410]   at org.gearvrf.jassimp.AiScene org.gearvrf.jassimp.Jassimp.aiImportFileEx(java.lang.String, long, org.gearvrf.jassimp.JassimpFileIO) (Jassimp.java:-2)
02-07 13:31:46.771  7278  7321 F art     : art/runtime/java_vm_ext.cc:410]   at org.gearvrf.jassimp.AiScene org.gearvrf.jassimp.Jassimp.importFileEx(java.lang.String, java.util.Set, org.gearvrf.jassimp.JassimpFileIO) (Jassimp.java:123)
02-07 13:31:46.771  7278  7321 F art     : art/runtime/java_vm_ext.cc:410]   at org.gearvrf.GVRSceneObject org.gearvrf.GVRAssetLoader.loadJassimpModel(org.gearvrf.GVRAssetLoader$AssetRequest, org.gearvrf.GVRSceneObject, java.util.EnumSet, boolean, org.gearvrf.GVRScene) (GVRAssetLoader.java:1241)
```

**Comment by liaxim** [comment]
gvr-accessibility now works.

**Comment by liaxim** [comment]
gvr-bullet works too. Things are getting better.

**Comment by liaxim** [comment]
gvr-cockpit doesn't load some of its files:
```
2-07 13:42:15.521 12661 12696 D ResourceCacheBase: put resource CLOSED{filePath=null; resourceId=7f040006; assetPath=null, url=null, inputStreamName=null} to cache
02-07 13:42:15.541 12661 12696 E GVRAssetLoader: ASSET: ERROR: model gvrf_ship_mesh did not load No suitable reader found for the file format of file "gvrf_ship_mesh".
02-07 13:42:15.541 12661 12696 D GVRAssetLoader: ASSET: loading gvrf_space_mesh ...
02-07 13:42:15.541 12661 12696 D ResourceCacheBase: put resource CLOSED{filePath=null; resourceId=7f040007; assetPath=null, url=null, inputStreamName=null} to cache
02-07 13:42:15.571 12661 12696 E GVRAssetLoader: ASSET: ERROR: model gvrf_space_mesh did not load No suitable reader found for the file format of file "gvrf_space_mesh".
```

**Comment by NolaDonato** [comment]
The old GVRContext.loadMesh assumed that the meshes were OBJ files so you did not have to specify the extension as .obj. Some of our demos use asset filenames without extensions and then call loadMesh. This won't work anymore. I will change the demos to specify extensions on the meshes they are loading.

**Comment by liaxim** [comment]
Needs rebase

**Comment by NolaDonato** [comment]
I have rebased it.

**Comment by liaxim** [comment]
Still says "This branch cannot be rebased due to conflicts"

**Comment by NolaDonato** [comment]
I rebased again. Now it says it has no conflicts.

**Comment by liaxim** [comment]
Needs rebase because of the other asset loader changes.

**Comment by NolaDonato** [comment]
Yes, there was a conflict there that actually required some extra coding and testing. I have tested with gvr-immersivepedia, gvr-cockpit and gvr-accessibility since these use loadMesh and that was the source of the conflict. I also ran the asset unit tests.

**Comment by liaxim** [comment]
Still says "This branch cannot be rebased due to conflicts"

**Comment by NolaDonato** [comment]
Replaced by #1052

**Pull request closed without merging**
