### PR TITLE
Vulkan: Removing GVRContext content loading APis

### PR DESCRIPTION
**Pull request by dnvasilev**
Manual merge of
    Removing GVRContext content loading APis (#1220)

    This patch deprecates all the functions on GVRContext which load assets
    (models, meshes, textures). It also moves the functions which load
    meshes from GVRContext to GVRAssetLoader.
     Updated 3D cursor lib to not used deprecated asset APIs

_This PR shall be 'merged'_
- - -
GearVRf-DCO-1.0-Signed-off-by: Dmitriy Vasilev d.vasilev@samsung.com

### CODE REVIEW

**Comment by NolaDonato** [comment]
While I am reviewing I will modify the documentation. Some of it is out of date. I am also testing with the asset tests. Some of the demos will need modification because I noticed that, in the Vulkan branch, they still use GVRContext.loadMesh. I think we changed the demos in master to avoid that API.

**Comment by dnvasilev** [comment]
I updated the demos.

**Comment by NolaDonato** [comment]
Thanks! I can test both pull requests together.

**Comment by dnvasilev** [comment]
Updated GearVRf-Tests: https://github.com/gearvrf/GearVRf-Tests/pull/118

**Comment by dnvasilev** [comment]
Added Extensions to this pull request

**Comment by NolaDonato** [comment]
I have made some changes to the documentation and removed future mesh APIs. Dmitriy will merge these changes into the pull request. I have changed the demos also.

**Comment by dnvasilev** [comment]
vk_assetapi merged in. @NolaDonato @liaxim Please review

**Comment by NolaDonato** [comment]
Looks OK to me. All the demos build and the ones I tested worked.

**Pull request merged**
