### PR TITLE
BooleanToggle node

### PR DESCRIPTION
**Pull request by mwitchwilliams**
Added X3D BooleanToggle node.  Enables functionality such as turning lights on/off.  Tests available on the GearVRf_Testing repository -> X3D -> boolean_toggle.

GearVRf-DCO-1.0-Signed-off-by: Mitch Williams 
m1.williams@partner.samsung.com

### CODE REVIEW

**Comment by thomasflynn** [comment]
works as expected.  i saw a point in the code that had a bunch of commented out code.  that should be removed.  otherwise, seems to look good.

**Comment by mwitchwilliams** [comment]
Removed the commented out code in AnimationInteractivityManager.java

**Comment by thomasflynn** [comment]
looks good now

**Comment by liaxim** [comment]
Looks good to me too

**Pull request merged**
