### PR TITLE
Added generation of normals and normal index for x3d files without

### PR DESCRIPTION
**Pull request by mwitchwilliams**
Added a method to generate vertex normals when the x3d file does not include them.  It also sets the normal index to the same values as the coord index.

GearVRf-DCO-1.0-Signed-off-by: Mitch Williams 
m1.williams@partner.samsung.com

### CODE REVIEW

**Comment by mwitchwilliams** [comment]
GearVRf-DCO-1.0-Signed-off-by: Mitch Williams 
m1.williams@partner.samsung.com

**Comment by liaxim** [comment]
@mwitchwilliams Github says it needs a rebase.

**Comment by mwitchwilliams** [comment]
Fixed rebase issues.

**Comment by liaxim** [comment]
Still needs rebase

**Comment by mwitchwilliams** [comment]
rebased and tested

**Comment by liaxim** [comment]
Do we have somebody that plans to test this?

**Comment by mwitchwilliams** [comment]
I just posted a bunch of demo’s on GearVRf-Tests (https://github.com/gearvrf/GearVRf-Tests)
One way to test is to remove the normals and normalindex from the X3D files.  I can assist with that.

I don’t think the demo’s have been posted yet, but it’s only been since Friday.

Mitch

**Comment by thomasflynn** [comment]
testing this now

**Comment by mwitchwilliams** [comment]
Some additional testing.  This first image is teapot + torus WITHOUT Normals + normalIndex.  A partial red light to the left, partial green light above and partial blue light to the right were added. The new normal generation code performs as expected
normals_generated_by_new_code

Second image is with the new normal generation code commented out and shows a modified looking scene as expected.
normal_generation_code_commented_out

This final scene includes the original normals and normalIndex from 3DS Max with the same red, green and blue lights included.  As expected, it matches the first image where the X3D parser generates the normals.
original_image_with_normals_included

**Comment by thomasflynn** [comment]
tested with the torusandteapot.x3d from the gvr-x3d-demo.  viewed it in gvr-modelviewer2.  then stripped it of normals and viewed it again.  looks good.

**Pull request merged**
