### PR TITLE
Adding framework tests to experimental gradle build

### PR DESCRIPTION
**Pull request by NolaDonato**
This pull request adds GearVRf-Tests/framework-tests and GearVRf-Tests/gvr-unittestutils to the experimental gradle build in GVRf/tools/Framework

GearVRF DCO: signed off by Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
I think I have the tests executing. Whew.

To get the change on top of your branch ``git fetch git@github.com:liaxim/GearVRf.git exgradle-test&&git cherry-pick b205b006075eb31097d9053927833830563fca49``

Or here: https://github.com/liaxim/GearVRf/tree/exgradle-test

**Comment by NolaDonato** [comment]
Thanks so much



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by liaxim** [comment]
Planning to merge this so we can build upon it. I will add my fix afterwards. Will wait for comments until Tuesday morning.

**Comment by NolaDonato** [comment]
Is this checked in?



Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------

**Comment by liaxim** [comment]
Yes, merged.

**Pull request merged**
