### PR TITLE
Nola's fix for GVRScene.removeAllSceneObjects

### PR DESCRIPTION
**Pull request by liaxim**
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@NolaDonato There is a release_v3.0.1 branch. You can select it as a base when creating a pull request.

Technically we might have to create a 3.0.2 release.

**Comment by liaxim** [comment]
@NolaDonato @thomasflynn Is this needed? Or should I close it?

**Comment by thomasflynn** [comment]
@nola?

**Comment by NolaDonato** [comment]
Am I supposed to do this pull request against a different branch?

**Comment by liaxim** [comment]
I am just asking do we think it is necessary to merge this into the 3.0.1 branch (and then create a point release).

**Comment by NolaDonato** [comment]
I defer to Tom on this one. This fix is for Nathipha who is still trying to use Eclipse. If she has successfully migrated to AS we don’t have to do it. If she hasn’t gotten that working yet then we should make the point release.

**Comment by liaxim** [comment]
I will close this one tomorrow if there are no comments. We can always re-open it if deemed necessary.

**Pull request closed without merging**
