### PR TITLE
Use mavenCentral dependency for gson

### PR DESCRIPTION
**Pull request by liaxim**
+ update the gradle plugin version for the extension libraries

Fixes: https://github.com/gearvrf/GearVRf-Demos/issues/431
Depends on: https://github.com/gearvrf/GearVRf-Demos/pull/432

Will require documentation update to mention the new mavenCentral dependency
Will require a snapshot update for the maven repo

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
Might be useful to include this in the 3.2 release.

**Comment by liaxim** [comment]
The NPE observed when exiting gvr-javascript:
```
03-30 11:45:26.614 14111 14111 E AndroidRuntime: FATAL EXCEPTION: main
03-30 11:45:26.614 14111 14111 E AndroidRuntime: Process: org.gearvrf.sample.gvrjavascript, PID: 14111
03-30 11:45:26.614 14111 14111 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {org.gearvrf.sample.gvrjavascript/org.gearvrf.sample.gvrjavascript.GearVRJavascriptActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void javax.script.Bindings.clear()' on a null object reference
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5143)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5166)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:226)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1902)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7522)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void javax.script.Bindings.clear()' on a null object reference
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at org.gearvrf.script.GVRScriptManager$3.run(GVRScriptManager.java:143)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at org.gearvrf.script.GVRScriptManager.destroy(GVRScriptManager.java:391)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at org.gearvrf.GVRViewManager.onDestroy(GVRViewManager.java:74)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at org.gearvrf.DaydreamViewManager.onDestroy(DaydreamViewManager.java:94)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at org.gearvrf.GVRActivity.onDestroy(GVRActivity.java:210)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:7102)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1170)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5121)
03-30 11:45:26.614 14111 14111 E AndroidRuntime: 	... 9 more
```

The fix is included in this pull request.

**Comment by rahul27** [comment]
Sure. Will test this today.

**Comment by liaxim** [comment]
With this change in I modified the dependencies for gvr-simplesample to include:
```
compile 'com.squareup.retrofit2:retrofit:2.1.0'
compile 'com.squareup.retrofit2:converter-gson:2.1.0'
```
and the build produced successfully an apk that ran fine.

**Comment by rahul27** [comment]
`GVRf/tools/gvr-scene-editor` needs the gson dependency. It depends on the SceneSerializer.

**Comment by rahul27** [comment]
Looks good. I've tested using the retrofit gson library and it compiles and runs fine. Verified that the gvr-javascript and scene editor also work fine with this change.

**Pull request merged**
