### PR TITLE
GVRAssetLoader support reading MTL files from res/raw 

### PR DESCRIPTION
**Pull request by NolaDonato**
OBJ files from res/raw cannot load MTL files at all without this fix -
the asset loader assumes the MTL files are in the "assets" directory.
This patch allows textures and MTL files to be loaded from res/raw if
the 3D model comes from res/raw.

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
gvr-3dcursor crashes with this pull request in.

**Comment by NolaDonato** [comment]
Fixed the crash in gvr-3dcursor

**Comment by liaxim** [comment]
gvr-accessibility crashes

**Comment by NolaDonato** [comment]
I fixed the gvr-accessibility crash

**Comment by liaxim** [comment]
Looks good. Will merge Friday afternoon.

**Pull request merged**
