### PR TITLE
Implement visibility propagation

### PR DESCRIPTION
**Pull request by niusounds**
Issue https://github.com/Samsung/GearVRf/issues/156
I add `setOpacity` and `setVisible` to `GVRSceneObject` for visibility propagation.

---

GVRSceneObject.setOpacity changes opacity of object and its children.

Example:
```java
GVRSceneObject obj1 = new GVRSceneObject(context);
scene.addSceneObject(obj1);

GVRSceneObject obj2 = new GVRSceneObject(context);
obj1.addChildObject(obj2);

// now obj1 and obj2 are fully opaque (opacity = 1.0f)

obj1.setOpacity(0.5f); // now obj1.opacity is 0.5f, and obj2.opacity is also 0.5f (parent.opacty * this.opacity = 0.5f * 1.0f)
obj2.setOpacity(0.2f); // now obj2.opacity is 0.1f (parent.opacity * this.opacty = 0.5f * 0.2f)
```
---
GVRSceneObject.setVisible changes visibility of object and its children.

Example:
```java
GVRSceneObject obj1 = new GVRSceneObject(context);
scene.addSceneObject(obj1); // now obj1 is visible

GVRSceneObject obj2 = new GVRSceneObject(context);
obj1.addChildObject(obj2); // now obj2 is visible

obj2.setVisible(false); // now obj2 is hidden

obj2.setVisible(true); // now obj2 is visible
obj1.setVisible(false); // now obj2 is hidden because its parent is hidden
```
---
## Caution

This merge changes class inheritance hierarchy of `GVROpacityAnimation`.

### CODE REVIEW

**Comment by chenchao1407** [comment]
I am just thinking if we should add one more boolean parameter to ask developer to do the propagation or not.

**Comment by thomasflynn** [comment]
I'm not sure I'm following what is being done for opacity.  

But for visibility, it seems like it would be solved if we just obeyed the object hierarchy.  Currently, before rendering everything in renderCamera(), we get the scene objects as a vector by calling scene->getWholeSceneObjects().  The traversal of the graph in getWholeSceneObjects() ignores any operations we could possibly do per node/sub-graph.  

For example, if it was determined that a node was not visible, either because of the visibility flag or because it was not in the frustum, the entire sub-graph under that node would no longer need to be traversed.  Propagation of the visibility flag would not be necessary.  This is something we have in the plans, but haven't gotten to implementing yet.

**Comment by chenchao1407** [comment]
Hi @thomasflynn  Do you want to close it or keep it open?

**Comment by thomasflynn** [comment]
Let's keep it open until i finish https://github.com/Samsung/GearVRf/issues/89 .  Then let's revisit to see if this is still necessary.

**Pull request closed without merging**
