### PR TITLE
fixing camera_position for culling

### PR DESCRIPTION
**Pull request by roshanch**
this fixes issue #1203 .

### CODE REVIEW

**Comment by mwitchwilliams** [comment]
Verified this fixed Issue #1203.
This scene now renders (with animation) correctly.

**Comment by thomasflynn** [comment]
good find!

**Comment by liaxim** [comment]
Needs ``GearVRf-DCO-1.0-Signed-off-by``

**Comment by liaxim** [comment]
gvr-shadows crashes due to nullptr de-reference.

**Comment by liaxim** [comment]
Is the fix complicated?

**Comment by roshanch** [comment]
waiting for @NolaDonato

**Comment by NolaDonato** [comment]
The fix will fail if the camera does not have an owner object. If you are rendering a shadow map or render target, this will be the case.

**Comment by liaxim** [comment]
Should we close this?

**Pull request closed without merging**
