### PR TITLE
fix issue with mulitiview rendering 

### PR DESCRIPTION
**Pull request by roshanch**
This fixes issue #942. Removing interpolated parameter from vertex shader to fragment shader with gl_ViewID and glDrawInstanced with glDrawElements.

### CODE REVIEW

**Comment by liaxim** [comment]
gvr-3dcursor-simple

```
11-17 12:50:50.641 27532 27587 E gvrf    : Could not compile shader 35632:
11-17 12:50:50.641 27532 27587 E gvrf    : 0:12: S0032: no default precision defined for variable 'u_view'
11-17 12:50:50.641 27532 27587 E gvrf    : 
11-17 12:50:50.641 27532 27587 E gvrf    : Custom shader added program 0
11-17 12:50:50.641 27532 27587 V gvrf    : CustomShader::texture:location: variable: diffuseTexture location: -1
11-17 12:50:50.641 27532 27587 V gvrf    : CustomShader::uniform:location: variable: ambient_color
11-17 12:50:50.641 27532 27587 V gvrf    : CustomShader::uniform:location: location: -1
11-17 12:50:50.641 27532 27587 V gvrf    : CustomShader::uniform:location: variable: diffuse_color
11-17 12:50:50.641 27532 27587 V gvrf    : CustomShader::uniform:location: location: -1
11-17 12:50:50.641 27532 27587 V gvrf    : CustomShader::uniform:location: variable: emissive_color
11-17 12:50:50.641 27532 27587 V gvrf    : CustomShader::uniform:location: location: -1
11-17 12:50:50.641 27532 27587 V gvrf    : CustomShader::uniform:location: variable: specular_color
11-17 12:50:50.641 27532 27587 V gvrf    : CustomShader::uniform:location: location: -1
11-17 12:50:50.641 27532 27587 V gvrf    : CustomShader::uniform:location: variable: specular_exponent
11-17 12:50:50.641 27532 27587 V gvrf    : CustomShader::uniform:location: location: -1
11-17 12:50:50.641 27532 27587 I gvrf    : after CustomShader::render() glError (0x501)
11-17 12:50:50.641 27532 27587 E gvrf    : Looking up ؊�� failed 
11-17 12:50:50.641 27532 27587 E gvrf    : Looking up ؊�� failed 
11-17 12:50:50.641 27532 27587 E gvrf    : Looking up ؊�� failed 
11-17 12:50:50.641 27532 27587 E gvrf    : Looking up ؊�� failed 
11-17 12:50:50.641 27532 27587 E gvrf    : Looking up ؊�� failed 
11-17 12:50:50.641 27532 27587 E gvrf    : Looking up ؊�� failed 
11-17 12:50:50.641 27532 27587 E gvrf    : Looking up ؊�� failed 
```

**Comment by liaxim** [comment]
Please add a logcat trace when we decide that we will be using ovr_multiview. Thanks.

**Comment by roshanch** [comment]
for some of the devices precision needs to be declared first. I moved it at the top. I added log traces for multiview rendering.

**Comment by liaxim** [comment]
Initial tests pass. Looks good.

**Comment by liaxim** [comment]
Planning to merge after lunch

**Pull request merged**
