### PR TITLE
Fix action up dispatched twice

### PR DESCRIPTION
**Pull request by ragner**
* ACTION_UP event is dispatched at onTouchEnd() only

GearVRf-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
Where did you notice that?

**Comment by ragner** [comment]
You can see this logging `e.getAction()` at RootViewGroup::dispatchPickerInputEvent().

You should be able to reproduce with any touchable renderable view.

**Comment by ragner** [comment]
But there is other way to fix this bug at GVRPicker:generatePickEvents() but I am not sure:
See:
`
else
            {
                propagateOnInside(collision); 
                if (prevHit.touched && !mTouched)
                {
                    propagateOnNoTouch(collision);
                }
                else if (!prevHit.touched && mTouched)
                {
                    propagateOnTouch(collision);
                }
            }

`

**Comment by liaxim** [comment]
Looks good. Now gvr-keyboardview works well too - previously you had to click many and many times in the text field to bring up the keyboard.

**Comment by liaxim** [comment]
Planning to merge on Friday.

**Pull request merged**
