### PR TITLE
adding support to load multiple texture coordinates from assimp

### PR DESCRIPTION
**Pull request by roshanch**
this adds support to load multiple tex-cords from assimp and choose appropriate one based on index present in material.
Test Model:
\\corpdata_sj\MCL\Temp\Common\Roshan\lightmap

### CODE REVIEW

**Comment by roshanch** [comment]
@NolaDonato @thomasflynn @liaxim can you please review this.

**Comment by roshanch** [comment]
do not merge yet, fails for collada files as some of the exporters are using different indexing mechanism.

**Comment by roshanch** [comment]
added patch for the index reordering. ready for review.

**Comment by NolaDonato** [comment]
cube_normal_diffuse_arealight.fbx crashes with this log:

07-21 18:57:13.289 14533-14559/com.samsung.android.gvr.sample I/dalvikvm-heap: Grow heap (frag case) to 113.149MB for 42656397-byte allocation
07-21 18:57:13.309 14533-14559/com.samsung.android.gvr.sample D/ResourceCacheBase: put resource CLOSED{filePath=/storage/emulated/0/GearVRF/jassimp/cube/cube_normal_diffuse_arealight.fbx; resourceId=0; assetPath=null, url=null, inputStreamName=null} to cache
07-21 18:57:13.419 14533-14584/com.samsung.android.gvr.sample W/TimeWarp: VSync 15682780: Eye=1,late=0.0ms,over=0.1ms,CPU=0.5ms,GPU=12.5ms,Tot=13.1ms
07-21 18:57:13.429 14533-14584/com.samsung.android.gvr.sample W/TimeWarp: VSync 15682781: Eye=0,late=4.9ms,over=0.0ms,CPU=0.6ms,GPU=6.4ms,Tot=11.9ms
07-21 18:57:13.429 14533-14587/com.samsung.android.gvr.sample I/VrApi: FPS=46,Prd=25ms,Tear=3,Early=0,Stale=32,VSnc=1,Lat=0,CPU0/GPU=2/2,1497/389MHz,OC=F,TA=F/F/0/0,SP=F/F/N/N,Mem=556MHz,Free=767MB,PSM=0,PLS=0,Temp=28.0C/0.0C
07-21 18:57:13.449 1259-1259/? D/STATUSBAR-NetworkController: refreshSignalCluster - setNWBoosterIndicators(false)
07-21 18:57:13.449 1259-1259/? D/STATUSBAR-NetworkController: refreshSignalCluster: data=-1 bt=false
07-21 18:57:13.529 14533-14584/com.samsung.android.gvr.sample W/TimeWarp: VSync 15682787: Eye=0,late=0.0ms,over=0.0ms,CPU=0.8ms,GPU=16.8ms,Tot=17.6ms
07-21 18:57:13.539 14533-14584/com.samsung.android.gvr.sample W/TimeWarp: VSync 15682787: Eye=1,late=9.4ms,over=0.0ms,CPU=0.5ms,GPU=3.7ms,Tot=13.5ms
07-21 18:57:13.539 14533-14584/com.samsung.android.gvr.sample W/TimeWarp: VSync 15682788: Eye=0,late=5.3ms,over=0.0ms,CPU=0.6ms,GPU=2.5ms,Tot=8.4ms
07-21 18:57:13.729 14533-14584/com.samsung.android.gvr.sample W/TimeWarp: VSync 15682799: Eye=0,late=0.0ms,over=0.1ms,CPU=1.2ms,GPU=7.5ms,Tot=8.8ms
07-21 18:57:14.259 14533-14579/com.samsung.android.gvr.sample I/OVR: DeviceManagerThread - poll(fds,1,1000) = 0 (Tid=14579)
07-21 18:57:14.269 14533-14584/com.samsung.android.gvr.sample W/TimeWarp: VSync 15682831: Eye=0,late=0.0ms,over=0.0ms,CPU=10.3ms,GPU=2.1ms,Tot=12.5ms
07-21 18:57:14.269 14533-14584/com.samsung.android.gvr.sample W/TimeWarp: VSync 15682831: Eye=1,late=4.2ms,over=0.0ms,CPU=0.2ms,GPU=5.0ms,Tot=9.4ms
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample W/dalvikvm: Invalid indirect reference 0x43ab1cb0 in decodeIndirectRef
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm: "gvrf-main" prio=5 tid=13 RUNNABLE
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x43563708 self=0x77b72a90
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:   | sysTid=14559 nice=0 sched=0/0 cgrp=apps handle=2008510472
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:   | state=R schedstat=( 12230068384 4255699164 74951 ) utm=794 stm=429 core=1
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.jassimp2.Jassimp.wrapSceneNode(Jassimp.java:-1)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.jassimp2.Jassimp.aiImportFileEx(Native Method)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.jassimp2.Jassimp.importFileEx(Jassimp.java:125)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.GVRAssetLoader.loadJassimpModel(GVRAssetLoader.java:627)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.GVRAssetLoader.loadModel(GVRAssetLoader.java:557)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.testmodels.MainView.loadModel(MainView.java:111)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.testmodels.MainView.switchModel(MainView.java:175)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.testmodels.MainView.onStep(MainView.java:156)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:515)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:126)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at org.gearvrf.GVRViewManager$5$1.run(GVRViewManager.java:798)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at android.os.Handler.handleCallback(Handler.java:733)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at android.os.Looper.loop(Looper.java:146)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample I/dalvikvm:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample E/dalvikvm: VM aborting
07-21 18:57:14.279 14533-14559/com.samsung.android.gvr.sample A/libc: Fatal signal 6 (SIGABRT) at 0x000038c5 (code=-6), thread 14559 (gvrf-main)

**Comment by NolaDonato** [comment]
Most of the X3D models fail to load. This might be due to the interleave changes because some of these failed before (but not all of them). Here are the logs for the failures:


07-21 21:06:50.216 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: loading sd:GearVRF/x3d/boxesspheres.x3d ...
07-21 21:06:50.476 25737-25776/com.samsung.android.gvr.sample E/gvrf: SHADER: end added custom shader 1001
07-21 21:06:50.476 25737-25776/com.samsung.android.gvr.sample D/gvrf: SHADER: Generated shader #1001 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight1:GVRPointLight1
07-21 21:06:50.506 25737-25776/com.samsung.android.gvr.sample E/gvrf: Custom shader added program 21
07-21 21:06:50.506 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6

07-21 21:06:50.526 25737-25843/com.samsung.android.gvr.sample D/gvrf: SHADER: Reuse shader #1001 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight1:GVRPointLight1
07-21 21:06:50.526 25737-25843/com.samsung.android.gvr.sample D/gvrf: SHADER: Reuse shader #1001 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight1:GVRPointLight1
07-21 21:06:50.526 25737-25843/com.samsung.android.gvr.sample D/gvrf: SHADER: Reuse shader #1001 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight1:GVRPointLight1
07-21 21:06:50.526 25737-25776/com.samsung.android.gvr.sample E/gvrf: SHADER: end added custom shader 1002
07-21 21:06:50.526 25737-25776/com.samsung.android.gvr.sample D/gvrf: SHADER: Generated shader #1002 GVRPhongShader::a_texcoord:a_normal:GVRDirectLight1:GVRPointLight1
07-21 21:06:50.536 25737-25776/com.samsung.android.gvr.sample E/gvrf:  texture is null for doggie
07-21 21:06:50.536 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6


07-21 21:06:51.486 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: loading sd:GearVRF/x3d/conered.x3d ...
07-21 21:06:51.526 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: successfully loaded model conered.x3d
07-21 21:06:51.566 25737-25776/com.samsung.android.gvr.sample E/gvrf: SHADER: end added custom shader 1004
07-21 21:06:51.566 25737-25776/com.samsung.android.gvr.sample D/gvrf: SHADER: Generated shader #1004 GVRPhongShader::a_texcoord:a_normal:GVRDirectLight2
07-21 21:06:51.636 25737-25780/com.samsung.android.gvr.sample I/OVR: DeviceManagerThread - poll(fds,1,1000) = 0 (Tid=25780)
07-21 21:06:51.656 25737-25776/com.samsung.android.gvr.sample E/gvrf: Custom shader added program 30
07-21 21:06:51.656 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 2268 vs 1548


07-21 21:06:52.806 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: loading sd:GearVRF/x3d/directionallight1.x3d ...
07-21 21:06:53.076 25737-25776/com.samsung.android.gvr.sample E/gvrf: SHADER: end added custom shader 1007
07-21 21:06:53.076 25737-25776/com.samsung.android.gvr.sample D/gvrf: SHADER: Generated shader #1007 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight2
07-21 21:06:53.096 25737-25776/com.samsung.android.gvr.sample E/gvrf: Custom shader added program 39
07-21 21:06:53.096 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6
07-21 21:06:53.096 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6
07-21 21:06:53.096 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6
07-21 21:06:53.096 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6

07-21 21:06:53.436 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: successfully loaded model pointlighttest.x3d
07-21 21:06:53.476 25737-25776/com.samsung.android.gvr.sample E/gvrf: SHADER: end added custom shader 1008
07-21 21:06:53.476 25737-25776/com.samsung.android.gvr.sample D/gvrf: SHADER: Generated shader #1008 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRPointLight1:GVRDirectLight1
07-21 21:06:53.506 25737-25776/com.samsung.android.gvr.sample E/gvrf: Custom shader added program 42
07-21 21:06:53.506 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6
07-21 21:06:53.506 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6

07-21 21:06:53.986 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: successfully loaded model spotlighttest1.x3d
07-21 21:06:54.006 25737-25776/com.samsung.android.gvr.sample E/gvrf: SHADER: end added custom shader 1009
07-21 21:06:54.016 25737-25776/com.samsung.android.gvr.sample D/gvrf: SHADER: Generated shader #1009 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight1:GVRSpotLight1
07-21 21:06:54.096 25737-25776/com.samsung.android.gvr.sample E/gvrf: Custom shader added program 45
07-21 21:06:54.096 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6
07-21 21:06:54.096 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6
07-21 21:06:54.096 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6
07-21 21:06:54.096 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6


07-21 21:06:54.506 25737-25775/com.samsung.android.gvr.sample E/X3DObject: ambientIntensity currently not implemented.
07-21 21:06:57.826 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: successfully loaded model teapottorus.x3d
07-21 21:06:57.826 25737-25841/com.samsung.android.gvr.sample D/GVRHybridObject: Finish loading and setting texture org.gearvrf.GVRBitmapTexture@7c050078
07-21 21:06:57.846 25737-25776/com.samsung.android.gvr.sample E/gvrf: SHADER: end added custom shader 1010
07-21 21:06:57.846 25737-25776/com.samsung.android.gvr.sample D/gvrf: SHADER: Generated shader #1010 GVRPhongShader::a_texcoord:diffuseTexture:a_normal
07-21 21:06:57.866 25737-25776/com.samsung.android.gvr.sample E/gvrf: Custom shader added program 48
07-21 21:06:57.876 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 1440 vs 8640
07-21 21:06:57.876 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 530 vs 3072

07-21 21:06:58.366 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: loading sd:GearVRF/x3d/teapottorusdirlights.x3d ...
07-21 21:06:58.396 25737-25775/com.samsung.android.gvr.sample E/X3DObject: X3D node SpottLight not implemented.
07-21 21:06:58.416 25737-25775/com.samsung.android.gvr.sample E/X3DObject: ambientIntensity currently not implemented.
07-21 21:06:58.436 25737-25846/com.samsung.android.gvr.sample D/GVRHybridObject: Finish loading and setting texture org.gearvrf.GVRBitmapTexture@7cf5bf80
07-21 21:07:02.106 25737-25841/com.samsung.android.gvr.sample D/GVRHybridObject: Finish loading and setting texture org.gearvrf.GVRBitmapTexture@7c050078
07-21 21:07:02.116 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: successfully loaded model teapottorusdirlights.x3d
07-21 21:07:02.146 25737-25776/com.samsung.android.gvr.sample E/gvrf: SHADER: end added custom shader 1011
07-21 21:07:02.146 25737-25776/com.samsung.android.gvr.sample D/gvrf: SHADER: Generated shader #1011 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight4:GVRPointLight3:GVRSpotLight3
07-21 21:07:02.426 25737-25776/com.samsung.android.gvr.sample E/gvrf: Custom shader added program 51
07-21 21:07:02.426 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 1440 vs 8640
07-21 21:07:02.436 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 530 vs 3072

-21 21:07:02.806 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: loading sd:GearVRF/x3d/usedef01.x3d ...
07-21 21:07:02.846 25737-25845/com.samsung.android.gvr.sample D/GVRHybridObject: Finish loading and setting texture org.gearvrf.GVRBitmapTexture@7cf5bf80
07-21 21:07:02.846 25737-25846/com.samsung.android.gvr.sample D/GVRHybridObject: Finish loading and setting texture org.gearvrf.GVRBitmapTexture@7cf5bf80
07-21 21:07:02.846 25737-25840/com.samsung.android.gvr.sample D/GVRHybridObject: Finish loading and setting texture org.gearvrf.GVRBitmapTexture@7c01a510
07-21 21:07:02.866 25737-25842/com.samsung.android.gvr.sample D/GVRHybridObject: Finish loading and setting texture org.gearvrf.GVRBitmapTexture@7c01a510
07-21 21:07:02.866 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: successfully loaded model usedef01.x3d
07-21 21:07:02.966 25737-25776/com.samsung.android.gvr.sample E/gvrf: SHADER: end added custom shader 1012
07-21 21:07:02.966 25737-25776/com.samsung.android.gvr.sample D/gvrf: SHADER: Generated shader #1012 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight2:GVRSpotLight2
07-21 21:07:03.096 25737-25776/com.samsung.android.gvr.sample E/gvrf: Custom shader added program 54
07-21 21:07:03.096 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6

07-21 21:07:03.596 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: successfully loaded model usedef02.x3d
07-21 21:07:03.706 25737-25776/com.samsung.android.gvr.sample E/gvrf: SHADER: end added custom shader 1013
07-21 21:07:03.706 25737-25776/com.samsung.android.gvr.sample D/gvrf: SHADER: Generated shader #1013 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight2:GVRSpotLight4
07-21 21:07:03.706 25737-25846/com.samsung.android.gvr.sample D/gvrf: SHADER: Reuse shader #1013 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight2:GVRSpotLight4
07-21 21:07:03.706 25737-25846/com.samsung.android.gvr.sample D/gvrf: SHADER: Reuse shader #1013 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight2:GVRSpotLight4
07-21 21:07:03.876 25737-25776/com.samsung.android.gvr.sample E/gvrf: Custom shader added program 57
07-21 21:07:03.876 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6
07-21 21:07:03.886 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6
07-21 21:07:03.886 25737-25776/com.samsung.android.gvr.sample E/gvrf: SHADER: end added custom shader 1014
07-21 21:07:03.886 25737-25776/com.samsung.android.gvr.sample D/gvrf: SHADER: Generated shader #1014 GVRPhongShader::a_texcoord:a_normal:GVRDirectLight2:GVRSpotLight4
07-21 21:07:04.056 25737-25776/com.samsung.android.gvr.sample E/gvrf: Custom shader added program 60
07-21 21:07:04.056 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 2268 vs 1548

07-21 21:07:04.486 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: loading sd:GearVRF/x3d/usedef03.x3d ...
07-21 21:07:04.496 25737-25841/com.samsung.android.gvr.sample D/GVRHybridObject: Finish loading and setting texture org.gearvrf.GVRBitmapTexture@7cf5bf80
07-21 21:07:04.506 25737-25843/com.samsung.android.gvr.sample D/GVRHybridObject: Finish loading and setting texture org.gearvrf.GVRBitmapTexture@7cf5bf80
07-21 21:07:04.506 25737-25844/com.samsung.android.gvr.sample D/GVRHybridObject: Finish loading and setting texture org.gearvrf.GVRBitmapTexture@7bfbd5b8
07-21 21:07:04.506 25737-25844/com.samsung.android.gvr.sample D/GVRHybridObject: Finish loading and setting texture org.gearvrf.GVRBitmapTexture@7bfbd5b8
07-21 21:07:04.516 25737-25775/com.samsung.android.gvr.sample D/GVRAssetLoader: ASSET: successfully loaded model usedef03.x3d
07-21 21:07:04.526 25737-25775/com.samsung.android.gvr.sample D/gvrf: SHADER: Reuse shader #1013 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight2:GVRSpotLight4
07-21 21:07:04.526 25737-25775/com.samsung.android.gvr.sample D/gvrf: SHADER: Reuse shader #1013 GVRPhongShader::a_texcoord:diffuseTexture:a_normal:GVRDirectLight2:GVRSpotLight4
07-21 21:07:04.526 25737-25775/com.samsung.android.gvr.sample D/gvrf: SHADER: Reuse shader #1014 GVRPhongShader::a_texcoord:a_normal:GVRDirectLight2:GVRSpotLight4
07-21 21:07:04.526 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6
07-21 21:07:04.526 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6
07-21 21:07:04.526 25737-25775/com.samsung.android.gvr.sample D/gvrf: SHADER: Reuse shader #1014 GVRPhongShader::a_texcoord:a_normal:GVRDirectLight2:GVRSpotLight4
07-21 21:07:04.526 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6
07-21 21:07:04.526 25737-25776/com.samsung.android.gvr.sample E/gvrf:  $$$$*** Attib length does not match 4 vs 6

**Comment by roshanch** [comment]
I tried this model without my changes, still same error.. I am looking into it..

**Comment by roshanch** [comment]
this model file has arealight and assimp sets the light type to 0 which is enum {undefined) and GVRf enums starts from 1. so it throws exception when it queries type.RawValue().

**Comment by NolaDonato** [comment]
Can we fix it?

**Comment by roshanch** [comment]
I changed assimp code to change light type. Now we have a crash in aiImportFileEx(). Looks like issue is related to reading file with callbacks which are newly introduced in GVRf. @deepakrawat22  is looking into it.

**Comment by liaxim** [comment]
Needs rebase

**Comment by roshanch** [comment]
added fix for arealight.fbx file. works for all models now

**Comment by liaxim** [comment]
Has anybody other than @roshanch tried this?

**Comment by thomasflynn** [comment]
Mike should have several models which can test this.

**Comment by NolaDonato** [comment]
I tried this and it works for assimp models. I got Mike to send me a new model with lightmaps. I will try it with that today.

**Comment by roshanch** [comment]
i will test it today with new models from Mike.

**Comment by NolaDonato** [comment]
I tried to test this and I get merge conflicts now.

**Comment by liaxim** [comment]
@NolaDonato Your local branch that you are trying to apply the changes to is not quite up to date with master. I tried and the git pull went through without problems.

**Comment by liaxim** [comment]
My understanding is that this is still subject to additional tests. Is that so?

**Comment by roshanch** [comment]
did testing with some samples from Mike and found that we need to add some more functionality.

**Comment by NolaDonato** [comment]
Yes, we should make a bunch of assets that test the various combinations.

**Comment by liaxim** [comment]
Needs rebase

**Comment by liaxim** [comment]
So what do we do with this pull request? It has been a month since it was opened.

**Comment by roshanch** [comment]
we got the models from Mike yesterday. We will test it and rebase it soon.

**Comment by NolaDonato** [comment]
Roshan is working on rebasing it.

**Comment by liaxim** [comment]
Should we close this?

**Comment by NolaDonato** [comment]
I think so



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Pull request closed without merging**
