### PR TITLE
Add default gvr.xml; add overloads for setMain and setScript

### PR DESCRIPTION
**Pull request by liaxim**
that omit the configuration file

Making the change per Tom.

Accompanying Demos pull request: https://github.com/gearvrf/GearVRf-Demos/pull/390

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@parthmehta209 Do you think you could help me review this change? Thanks.

**Comment by thomasflynn** [comment]
needs rebase

**Comment by liaxim** [comment]
Rebased

**Comment by thomasflynn** [comment]
looks good to me.

**Comment by liaxim** [comment]
Will merge in the afternoon

**Pull request merged**
