### PR TITLE
Add Javascript to script framework

### PR DESCRIPTION
**Pull request by danke-sra**
Add Rhino JS engine 1.7R2, a ScriptEngine-compatibility layer, and updates in script framework

### CODE REVIEW

**Comment by danke-sra** [comment]
Added missing jar files and updated javadoc. Please find the demo app here: https://github.com/gearvrf/GearVRf-Demos/pull/13

**Comment by thomasflynn** [comment]
needs rebase

**Comment by danke-sra** [comment]
Rebased. Thanks.

**Comment by danke-sra** [comment]
Any review comments?

**Comment by thomasflynn** [comment]
cherry-picked, runs without problem with the associated sample.

**Pull request merged**
