### PR TITLE
Remove two warnings.

### PR DESCRIPTION
**Pull request by JonShemitz**
Source code is warning-free, again.

Change-Id: I53613c481dff66d7012188857f1560206a593ff3

GearVRf-DCO-1.0-Signed-off-by: Jon Shemitz
j.shemitz@samsung.com

### CODE REVIEW

**Comment by chenchao1407** [comment]
Hi Jon.

In my case I still can see one more Warning in org.gearvrf.debug.GVRConsole

There is one unused import "import org.gearvrf.debug.GVRConsole.EyeMode;"

Can you help check this?

Thanks in advance.

**Comment by JonShemitz** [comment]
This is why I wanted to amend the checkin ...

**Comment by chenchao1407** [comment]
Hi Jon.

I think you can amend the check-in(or do a rebase and then modify the check-in) and push to your repo and then the pull request will be automatically updated.

Thanks

**Comment by JonShemitz** [comment]
I do not know what I did that closed this ...

**Pull request closed without merging**
