### PR TITLE
Fixes camera flickering with Gear controller

### PR DESCRIPTION
**Pull request by NolaDonato**
PR #1731 as a single commit

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
There is no gaze controller in any of the apps that use it.

**Comment by liaxim** [comment]
Picking is not quite right. See screenshots:

**Comment by liaxim** [comment]
Disconnecting and reconnecting the controller while the app is running doesn't work as well as before.

**Comment by NolaDonato** [comment]
I fixed the regressions with the gaze controller and removing the gear controller.

**Comment by NolaDonato** [comment]
it has been rebased

**Comment by liaxim** [comment]
Without controller the demo apps check out.

With controller gvr-3dcursor crashed for me with:
```
03-02 10:13:53.839 24885 24907 E AndroidRuntime: FATAL EXCEPTION: GLThread 17258
03-02 10:13:53.839 24885 24907 E AndroidRuntime: Process: org.gearvrf.io.cursor, PID: 24885
03-02 10:13:53.839 24885 24907 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'org.gearvrf.GVRTransform org.gearvrf.GVRSceneObject.getTransform()' on a null object reference
03-02 10:13:53.839 24885 24907 E AndroidRuntime: 	at org.gearvrf.io.GVRCursorController$1.run(GVRCursorController.java:443)
03-02 10:13:53.839 24885 24907 E AndroidRuntime: 	at org.gearvrf.GVRViewManager.afterDrawEyes(GVRViewManager.java:513)
03-02 10:13:53.839 24885 24907 E AndroidRuntime: 	at org.gearvrf.OvrViewManager.afterDrawEyes(OvrViewManager.java:314)
03-02 10:13:53.839 24885 24907 E AndroidRuntime: 	at org.gearvrf.OvrViewManager.onDrawFrame(OvrViewManager.java:304)
03-02 10:13:53.839 24885 24907 E AndroidRuntime: 	at org.gearvrf.OvrVrapiActivityHandler$8.onDrawFrame(OvrVrapiActivityHandler.java:451)
03-02 10:13:53.839 24885 24907 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1562)
03-02 10:13:53.839 24885 24907 E AndroidRuntime: 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1262)
```
Just launched, looked weird, seemed I had controller and gaze, then froze and closed. On subsequent launches the crash didn't reproduce but I do get both controller and gaze.

**Comment by liaxim** [comment]
Planning to merge on Monday anyway. There are also some lingering problems we'll get back to in the future (picking).

**Pull request merged**
