### PR TITLE
Allow shader version to be specified 

### PR DESCRIPTION
**Pull request by NolaDonato**
Added GVRShaderTemplate constructor variant which lets the user pass the
GLSL version to use. Previously all custom shaders were restricted to be
GLSL 300. This change permits old custom shaders to be used as input to
GVRShaderTemplate without modification.

GearVRf-DCO-1.0-Signed-off-by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Looks good. Will merge after lunch if there are no comments.

**Comment by roshanch** [comment]
There is bug with driver when it uses "samplerExternalOES" sampler with the video and GLSL 300. It throws some glErrors on some of the drivers. But using GLSL 100 works well with Mali and Adreno.

**Comment by liaxim** [comment]
@roshanch This bug affects the oes_* shaders. This change is for the generated shaders so it shouldn't matter.. What do you think?

**Comment by roshanch** [comment]
Yes this change is not going to affect it. I just mentioned as it is relevant. The intent was to keep this in mind when we develop any video sample.

**Comment by NolaDonato** [comment]
It matters if a user subclasses GVRShaderTemplate to make their own shader. If they use OES extensions it won’t work now because we hardcode version 300 into our shaders.

I ran into this when I tried to make gvr-video use GVRShaderTemplate to make the shader and it didn’t work. The version 300 shader produces incorrect colors due to a driver bug.

**Pull request merged**
