### PR TITLE
backend_oculus: leave vrapi initialized after onPause

### PR DESCRIPTION
**Pull request by liaxim**
Enables taking screenshots and recording videos from the Oculus global menu
Addresses https://github.com/Samsung/GearVRf/issues/1235

---
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by roshanch** [comment]
do we need the changes on other backend as well ?

**Comment by liaxim** [comment]
This is Oculus-specific. The rest of changes are a little bit of a cleanup.

**Comment by pdiaz** [comment]
It's a great start. Unfortunately if crashes when launching the app from Oculus Home a second time.

**Comment by liaxim** [comment]
Could you please share the logcat output when the app crashes?

**Comment by liaxim** [comment]
@pdiaz Tried launching from Oculus Home. Can't reproduce the crash. Please provide more information.

**Comment by pdiaz** [comment]
Launching the app from Oculus Home works when you start to work on publishing the app on it.

A way to work around to this crash is to add System.exit(0) to the VRActivity onDestroy method:

[crashlog.txt](https://github.com/Samsung/GearVRf/files/1552549/crashlog.txt)

**Comment by liaxim** [comment]
Looks like the exception causing it is a NPE in GVRShaderTemplate. Not immediately obvious what can cause that.
```
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.gearvrf.utility.VrAppSettings.isMultiviewSet()' on a null object reference
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at java.util.HashMap org.gearvrf.GVRShaderTemplate.getRenderDefines(org.gearvrf.IRenderable, org.gearvrf.GVRScene) (GVRShaderTemplate.java:554)
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at java.util.HashMap org.gearvrf.GVRTextureShader.getRenderDefines(org.gearvrf.IRenderable, org.gearvrf.GVRScene) (GVRTextureShader.java:64)
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at int org.gearvrf.GVRShaderTemplate.bindShader(org.gearvrf.GVRContext, org.gearvrf.IRenderable, org.gearvrf.GVRScene, boolean) (GVRShaderTemplate.java:441)
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at void org.gearvrf.GVRRenderData.bindShader(org.gearvrf.GVRScene, boolean) (GVRRenderData.java:300)
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at void org.gearvrf.GVRRenderData.bindShaderNative(org.gearvrf.GVRScene, boolean) (GVRRenderData.java:356)
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at void org.gearvrf.NativeRenderTarget.cullFromCamera(long, long, long, long) (GVRRenderTarget.java:-2)
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at void org.gearvrf.GVRRenderTarget.cullFromCamera(org.gearvrf.GVRScene, org.gearvrf.GVRCamera, org.gearvrf.GVRShaderManager) (GVRRenderTarget.java:98)
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at void org.gearvrf.OvrViewManager.onDrawEye(int, int, boolean) (OvrViewManager.java:277)
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at void org.gearvrf.OvrViewManager.drawEyes(long) (OvrViewManager.java:-2)
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at void org.gearvrf.OvrViewManager.onDrawFrame() (OvrViewManager.java:294)
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at void org.gearvrf.OvrVrapiActivityHandler$8.onDrawFrame(javax.microedition.khronos.opengles.GL10) (OvrVrapiActivityHandler.java:443)
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at void android.opengl.GLSurfaceView$GLThread.guardedRun() (GLSurfaceView.java:1562)
12-12 17:49:31.764 19195-20488/com.package A/art: art/runtime/java_vm_ext.cc:470]   at void android.opengl.GLSurfaceView$GLThread.run() (GLSurfaceView.java:1262)
```

@pdiaz So what to do to reproduce? I have an app in Oculus Home but it is not crashing. How should I go about putting the app in Oculus Home to reproduce? Can you reproduce by using one of our sample apps? If you can, we will be able to address this quicker. I'd like to see the complete logcat output.

**Comment by liaxim** [comment]
I believe this could be merged. If @pdiaz comes back with extra information then we should investigate but in all my tests this worked and enabled the recording feature.

**Comment by pdiaz** [comment]
I made some fast hacks to the shaders and multiview on my end. They do not seem to be directly related to the crash but when disabling them I can't reproduce the crash. I haven't managed to spend that much time on it. Please, go ahead and merge the changes.

**Comment by thomasflynn** [comment]
I'm with @pdiaz.  I cherry-picked an ran it with complexscene inside the headset with developer mode off.  When I do a long back press, select capture, then video, it gives me a toast saying complescene has crashed, but still re-runs complexscene.  I do not see the red recording dot that would be indicating that video was being captured.  So, this still isn't quite working.

**Comment by liaxim** [comment]
Reproducing. Works with gvr-simplesample but not with gvr-complexscene.

**Comment by liaxim** [comment]
New activity getting created in the case of complexscene. New activity was trying to initialize the vrapi again. Fixed by maintaining a global count of vrapi activities and making vrapi initialization/un-initialization decisions based on that.

Tested with gvr-simplesample, gvr-complexscene.

**Comment by thomasflynn** [comment]
ok, this is working better for me.  @pdiaz wanna give it a try?

**Comment by thomasflynn** [comment]
if there's no further comments, I'll merge this tomorrow.

**Comment by ragner** [comment]
@liaxim,
After this merge I am getting the following FATAL EXCEPTION:


```

01-15 15:06:43.070 25098-25098/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.gearvrf.keyboardview, PID: 25098
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{org.gearvrf.keyboardview/org.gearvrf.keyboardview.MainActivity}: java.lang.IllegalStateException: Fatal error: no backend available
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                    Caused by: java.lang.IllegalStateException: Fatal error: no backend available
                                                       at org.gearvrf.GVRActivity.onCreate(GVRActivity.java:111)
                                                       at org.gearvrf.keyboardview.MainActivity.onCreate(MainActivity.java:28)
                                                       at android.app.Activity.performCreate(Activity.java:6955)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045) 
                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
```

**Comment by liaxim** [comment]
@ragner This change by itself is unlikely the cause a "backend not available" error. Could you please ``git clean -fdx`` all the repos you use for this build and try again? If still occurring you could send me an apk to examine, thanks.

**Comment by ragner** [comment]
Hi @liaxim, 
`git clean ` works. Everything ok.

**Pull request merged**
