### PR TITLE
Fixed picking bug (fixes issue #800)

### PR DESCRIPTION
**Pull request by NolaDonato**
The wrong matrix was being used for transforming the picking ray causing
it to pick the wrong thing.
Now the picker actually looks at the object it is attached to and gets
its position and orientation from that. Before it was incorrectly always
using the camera view matrix no matter what it was attached to. Some of
the demos have bugs because they attach the picker to the wrong object
and that used to work. I am doing a pull request for these demos.
Removed logging and exposed GVRCameraRigBase.getHeadTransformObject.

GearVRf-DCO-1.0-Signed-off-by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by roshanch** [comment]
tested with planetarium, and works fine.

**Comment by roshanch** [comment]
tetsted with gvr-tutorial6 sample, works fine.

**Comment by liaxim** [comment]
Does not fix a crash on launch of gvr-immersivepedia. I think the same reason is why gvr-video and gvr-accessibility crash on tap.

The crash was introduced in the pick visible pull request. It was my mistake to merge it early but please do mark pull requests not meant for merging in the future. How can we tell otherwise?

**Comment by deepakrawat22** [comment]
In new video I received crash at:

_ZN3gvr9Transform14getModelMatrixEv
/home/deepak.rawat/Documents/GearVRf/GearVRf/GVRf/Framework/framework/src/main/jni/objects/components/transform.cpp:69


will check in more details.

**Comment by deepakrawat22** [comment]
@NolaDonato Even with this new pull request both gvr-accessibility and gvr-immersivepedia are crashing at startup. I was wrong earlier regarding gvr-immersivepedia, forgot to rebuild it.

**Comment by NolaDonato** [comment]
gvr-accessibility crashes on startup for me with master too. It runs out of memory during initialization.

**Comment by NolaDonato** [comment]
I found out what the crash on startup was in gvr-accessibility and gvr-immersivepedia and fixed it

**Comment by NolaDonato** [comment]
I updated pull request #812 to fix this problem

**Comment by liaxim** [comment]
Looks good to me. Went through all the samples and the picker works and the crash due to the null matrix is gone. Will merge after lunch if there are no comments.

**Pull request merged**
