### PR TITLE
Fixes to the IO framework

### PR DESCRIPTION
**Pull request by rahul27**
1) Stop the event thread when no devices are found
2) Ability to set near and far depth
3) Cursor can now be attached to the camera rig
4) Fixed a bug when multple cursor controllers are
   returned for a given device
5) Fix NPE on SensorEvent.getCursorController()
6) Setting the initial position using setPosition() is fixed

GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
rahuldevan@gmail.com

### CODE REVIEW

**Comment by thomasflynn** [comment]
@liaxim, could you look this over?  Thanks.

**Comment by liaxim** [comment]
How does "3) Cursor can now be attached to the camera rig" work? How do I do that?

**Comment by rahul27** [comment]
@liaxim in the input-sample add the scene object to the camera rig instead of the main scene. 

[Here](https://github.com/gearvrf/GearVRf-Demos/blob/master/input-sample/src/org/gearvrf/io/InputScript.java#L282) is a link to the line in the input-sample.

Before, the cursor used to only use its position and not the hierarchical position which caused issues when it was attached to the camera rig.

**Comment by liaxim** [comment]
Ok, got it.

Code looks good and the sample works fine. From my perspective it can be merged.

**Pull request merged**
