### PR TITLE
Updated GLM to version 0.9.7.5. 

### PR DESCRIPTION
**Pull request by apjagdale**
Changed respective files since GLM has all angles in Radians.

### CODE REVIEW

**Comment by NolaDonato** [comment]
I tested with gvr-jassimp, gvr-cockpit and gvr-multilight and it works fine.

**Comment by liaxim** [comment]
@dknaan Could you please take a quick look whenever you have time?

**Comment by NolaDonato** [comment]
I also tested with my picking reform code and the matrix inverse is correctly computed now

**Comment by liaxim** [comment]
Ok

**Pull request merged**
