### PR TITLE
Call handleOnDock immediately for devices that do not require a docking event listener

### PR DESCRIPTION
**Pull request by liaxim**
Supersedes https://github.com/Samsung/GearVRf/pull/1019

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@sivapenke Please confirm it works as expected for you.

**Comment by sivapenke** [comment]
@liaxim not working. Looks like the issue is with the sequence of calls. isDockListenerRequired() is not updated yet by the time it is called.

**Comment by liaxim** [comment]
@sivapenke Should work now. Sending the event from onCreate requires bigger refactoring.

**Comment by sivapenke** [comment]
@liaxim Ok, works now.

**Comment by liaxim** [comment]
Will merge Thursday morning if there are no other comments.

**Comment by sivaboggala** [comment]
isDockListenerRequired() depends on compile time isStandAloneVR(). There is no guarantee that Build.DEVICE.endsWith("_vr"). This is weird flag set by my team to distinguish regular builds from standalone build. Framework should query runtime for the capability.

**Pull request merged**
