### PR TITLE
Fixed bug in X3D vertex attribute construction

### PR DESCRIPTION
**Pull request by NolaDonato**
Modified the X3D parser to reconstruct the vertex, texcoord and normals lists so they are all the same length. The X3DObject.organizeVertices function maintains a list of all the unique vertices (unique combinations of position, normal, texcoord). It constructs this list by iterating thru the faces and finding the position, normal and texcoord for each one. The vertex array made by this process bears little resemblance to the original X3D data - vertex order is NOT preserved. FYI Unity does the same thing.

GearVRf-DCO-1.0-Signed-off-by: nola.donato@samsung.com Nola Donato

### CODE REVIEW

**Comment by Vittalbabu** [comment]
This fixes the error message from the Mesh code for cylinnder.x3d. 

4 other x3d files throw an exception

07-26 11:58:46.126: E/X3DObject(26169): Parse call: Exception = java.lang.IllegalArgumentException: The input array of vertices should be an array of 3-component elements whose length is non-zero and divisible by 3. But current data length is 0.
07-26 11:58:46.746: E/MainActivity(26169): ** Load model: GearVRF/usedef1Normal.x3d
07-26 11:58:46.776: E/gvrf(26169): SHADER: end added custom shader 1006
07-26 11:58:46.786: E/gvrf(26169): SHADER: end added custom shader 1007
07-26 11:58:46.786: E/gvrf(26169): Custom shader added program 36
07-26 11:58:46.786: E/gvrf(26169): Custom shader added program 39
07-26 11:58:47.346: E/MainActivity(26169): ** Load model: GearVRF/usedef02.x3d
07-26 11:58:47.366: E/X3DObject(26169): Parse call: Exception = java.lang.IllegalArgumentException: The input array of vertices should be an array of 3-component elements whose length is non-zero and divisible by 3. But current data length is 0.
07-26 11:58:47.986: E/MainActivity(26169): ** Load model: GearVRF/usedef03.x3d
07-26 11:58:48.006: E/X3DObject(26169): Parse call: Exception = java.lang.IllegalArgumentException: The input array of vertices should be an array of 3-component elements whose length is non-zero and divisible by 3. But current data length is 0.
07-26 11:58:48.636: E/MainActivity(26169): ** Load model: GearVRF/usedef04.x3d
07-26 11:58:48.656: E/X3DObject(26169): Parse call: Exception = java.lang.IllegalArgumentException: The input array of vertices should be an array of 3-component elements whose length is non-zero and divisible by 3. But current data length is 0.
07-26 11:58:49.286: E/MainActivity(26169): ** Load model: GearVRF/usedef05.x3d
07-26 11:58:49.306: E/X3DObject(26169): Parse call: Exception = java.lang.IllegalArgumentException: The input array of vertices should be an array of 3-component elements whose length is non-zero and divisible by 3. But current data length is 0.

**Comment by liaxim** [comment]
@NolaDonato @Vittalbabu Should we merge?

**Comment by Vittalbabu** [comment]
Needs a bit more testing -- the test program that @roshanch and I have been using doesn't display the models on screen larger than a few pixels wide. We can't judge if the import is working correctly. We are working on testing this better.

**Comment by Vittalbabu** [comment]
@NolaDonato  Make the following change to startElement() -- set reorganizeVerts = false if this is the USE attribute case for IndexedFaceSet. Gets rid of the issue of setting zero vertices for the Mesh.

Still needs more testing.

       else if (qName.equalsIgnoreCase("IndexedFaceSet"))
      {
        attributeValue = attributes.getValue("USE");
        if (attributeValue != null)
        { // shared GVRMesh
          DefinedItem useItem = null;
          for (DefinedItem definedItem : mDefinedItems)
          {
            if (attributeValue.equals(definedItem.getName()))
            {
              useItem = definedItem;
              break;
            }
          }
          if (useItem != null)
          {
            gvrMesh = useItem.getGVRMesh();
            reorganizeVerts = false;
          }
        }

**Comment by NolaDonato** [comment]
I put in a pull request to fix the scaling in gvrtestmodels



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by NolaDonato** [comment]
I  did this at 2am so I  must have skipped one of the use/definitely cases



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by liaxim** [comment]
Will merge this in couple of hours

**Pull request merged**
