### PR TITLE
Simple fix for a problem when the transform hierarchy is concurrently

### PR DESCRIPTION
**Pull request by liaxim**
validated and invalidated.

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@saurabhlalwani This addresses the problem in your app. Probably the best that can be done without redesigning the whole threading model.

**Comment by saurabhlalwani** [comment]
@liaxim my app seems to be working fine with this change.

**Comment by liaxim** [comment]
There a small overhead and it is more of a hack but will have to do for now.

**Comment by liaxim** [comment]
Planning to merge Tuesday after lunch if there are no comments.

**Pull request merged**
