### PR TITLE
Gvrwidget

### PR DESCRIPTION
**Pull request by dattanand**
New implementation which provides a way to add 2D interactive widgets in GVRF as a plugin, widgets are libgdx (game engine) scene2d widgets. sample is also provided (widget-model-viewer)

As recommended we have broken down the earlier pull request #326 in distinguishable commits.

### CODE REVIEW

**Comment by liaxim** [comment]
Isn't gdx-natives.jar desktop-only?

**Comment by dattanand** [comment]
actually it may not be required, the .so file is included from the sample, I can see them included in gdx.jar as well.

**Comment by liaxim** [comment]
I had trouble having my apk find libgdx.so. Had to make manual tweaks.

**Comment by dattanand** [comment]
not sure what caused this issue, since the .so is included in the sample app, it should get copied correctly, worked for me in different devices without having to manually copy the .so file

**Comment by dattanand** [comment]
i guess git ignore has ignored .so extensions, it may not have got commited

**Comment by liaxim** [comment]
Few initial thoughts:

- GVRWidgetPluginActivity; do you think it is possible to have the integration with gdx done in a different way that doesn't involve introducing a new base activity? The new activity adds a lot of complexities of its own - getTextureId, setCurrentScript, setPickedObject to name a few. Seems rather invasive.
- exposing the EGLContext as a public getter; it looks like it can be retrieved without api additions
- can you describe a bit what to expect out of the sample? I get a watch that I can rotate but clearly there is more in there.
- formatting; I see tabs-only files

**Comment by dattanand** [comment]
GVRWidgetPluginActivity is not a base activity, it is particular to libgdx widgets only, it is required to be an activity due to libgdx design constraints, so it may not be possible to avoid it as such, I have made sure the gvractivity is untouched, the other changes seemed inevitable

if EGLContext of GVRF is required by libgdx, so the method was introduced, if it can be avoided, sure I wil make that change.

In sample, u should see the UI panel on left side of models which allows you to switch between different 
models, change color of car, zoom the models etc.

for all the modifies files, I have changed them to spaces, if missed, will correct it

**Comment by ragner** [comment]
Hi @dattanand 
I am trying to launch the sample but I am getting the following error:

12-03 20:17:32.459: E/AndroidRuntime(28538): FATAL EXCEPTION: main
12-03 20:17:32.459: E/AndroidRuntime(28538): Process: org.gearvrf.modelviewer2, PID: 28538
12-03 20:17:32.459: E/AndroidRuntime(28538): java.lang.ExceptionInInitializerError
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at java.lang.reflect.Constructor.newInstance(Native Method)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at java.lang.Class.newInstance(Class.java:1690)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1080)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2983)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at android.os.Looper.loop(Looper.java:145)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at android.app.ActivityThread.main(ActivityThread.java:6872)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at java.lang.reflect.Method.invoke(Native Method)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at java.lang.reflect.Method.invoke(Method.java:372)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
12-03 20:17:32.459: E/AndroidRuntime(28538): Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx' for target: Linux, 32-bit
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:117)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:34)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at org.gearvrf.plugins.widget.GVRWidgetPluginActivity.<clinit>(GVRWidgetPluginActivity.java:77)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	... 14 more
12-03 20:17:32.459: E/AndroidRuntime(28538): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.gearvrf.modelviewer2-2/base.apk"],nativeLibraryDirectories=[/data/app/org.gearvrf.modelviewer2-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libgdx.so"
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at java.lang.System.loadLibrary(System.java:988)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:113)
12-03 20:17:32.459: E/AndroidRuntime(28538): 	... 16 more

**Comment by liaxim** [comment]
@ragner for a quick fix copy libgdx.so to GVRf/Sample/widget-model-viewer/libs/; you can find the .so inside GVRf/Framework/libs/gdx.jar.

**Comment by ragner** [comment]
Thank you,
most of the time it is working well but some times I am getting a NullPointerException
at  the line 338, boolean isContinuous = graphics.isContinuousRendering(), in GVRWidgetPluginActivity::onPause()

Anyway, I can test it and looks nice ...

**Comment by thomasflynn** [comment]
Hi guys.  My comments are the same as on the last pull-request.  Let's merge in smaller, more isolated pull-requests first.  Let's try this:  let's leave this pull-request open and just rebase it as we merge in the other pull-requests.  So lets start by creating a pull-request for the unlit fbo shader support.  That looked pretty small, isolated, and likely to be merged in quickly.  Thanks.

**Comment by dattanand** [comment]
Hi @thomasflynn 
I have created two new pull requests #332  and #333 for the same

**Comment by ragner** [comment]
I am not sure if is possible to use Android fragments with GVRActivity, but regarding GVRWidgetPluginActivity maybe we could add the support to libgdx throught of some specialisation of com.badlogic.gdx.backends.android.AndroidFragmentApplication. We could avoid to maintain the code duplicated from com.badlogic.gdx.backends.android.AndroidApplication.java to GVRWidgetPluginActivity.

In my opinion the new implementation will be simpler that the current GVRWidgetPluginActivity.

So we could keep GVRActivity as the main activity.

**Comment by dattanand** [comment]
@ragner 
I did toil a lot to avoid creating activity and code duplication for this plugin, but it kept breaking somewhere down the line as I mentioned due to design being as such by libgdx. but again, this will serve only for widget plugin and GVRActivity will always be main activity.

**Pull request closed without merging**
