### PR TITLE
Fixed material transparency in phong shader

### PR DESCRIPTION
**Pull request by NolaDonato**
The Phong shader was ignoring the alpha in the diffuse color of the
material. Now it is correctly applying it.

### CODE REVIEW

**Comment by liaxim** [comment]
@roshanch ?

**Comment by roshanch** [comment]
@NolaDonato I think we should have support for the opacity component of material and not just a opacity texture. We have opacity component in material coming from the assimp, just need to add it into shader.

**Comment by NolaDonato** [comment]
This pull request adds support for material opacity. It is in the alpha component of the diffuse material color.

**Comment by NolaDonato** [comment]
Pull request #624 addresses Roshan's comment about exporting opacity.

**Comment by liaxim** [comment]
Will merge lunch time.

**Pull request merged**
