### PR TITLE
Fix for the texture shader when its light support and batching are en…

### PR DESCRIPTION
**Pull request by liaxim**
…abled

fixes the crash in gvr-cardboard-audio on launch

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@roshanch Please review

**Comment by roshanch** [comment]
with this fix, how does it get mv (modelView) matrix when light and batching enabled?

**Comment by liaxim** [comment]
@roshanch Updated according to your comment; in case both BATCHING and LIGHT are enabled mv is ``"mv = u_view * model_matrix;\n"``

The litshader sample works because LIGHT and BATCHING are not enabled together when it runs. For whatever reasons in cardboard-audio they are both enabled hence we were creating a shader without u_model defined but were trying to refer to it. The shader compilation failure is handled less than gracefully so we crash some time later.

--

Noticed that if batching and lighting are both enabled on startup, trying to disable the light on the renderData has no effect (the light stays enabled always). Can you look into that?

It would be really nice if you build a test app that goes through the various scenarios possible with batching and allows for quick and focused verification. It will be a must for the custom shader batching so the sooner you think about this for the texture shader the better.

**Comment by roshanch** [comment]
so the fix should be replace u_model with model_matrix so 
```
"#else\n"
        "mv = u_view * model_matrix ;\n
  "#endif\n"
```

**Comment by roshanch** [comment]
And i will look into other issue you mentioned.

**Comment by liaxim** [comment]
Yes, the fix in case both BATCHING and LIGHT are defined is to do "mv = u_view * model_matrix;\n"

**Comment by liaxim** [comment]
Will merge in the afternoon if there are no further comments.

**Comment by liaxim** [comment]
@roshanch  Made the update you requested.

**Comment by roshanch** [comment]
thanks. good to go.

**Comment by NolaDonato** [comment]
Disabling the light on the renderdata works with the custom shader if batching is off. The gvr-multilight sample tests this.

**Comment by roshanch** [comment]
@NolaDonato  problem is with texture shader. I found the fix, will push it today afternoon.

**Pull request merged**
