### PR TITLE
Update Android.mk

### PR DESCRIPTION
**Pull request by samsungax**
GearVRf-DCO-1.0-Signed-off-by: Adam Xu
bing2.xu@samsung.com

### CODE REVIEW

**Comment by chenchao1407** [comment]
After Patrick modified the web page content of build instruction, I will merge this pull request

**Comment by thomasflynn** [comment]
Chao, have you tested this modification?

**Comment by thomasflynn** [comment]
FYI, the documentation change has been made.

**Comment by chenchao1407** [comment]
Hi.

I think this patch doesn't work since for the purpose to change reference's path, one more change on Framework's project.properties is necessary.

**Comment by chenchao1407** [comment]
Per discussion with Adam, I am going to close this pull request and he'll create another one which is correct.

**Pull request closed without merging**
