### PR TITLE
Account for rotations while calculating BV

### PR DESCRIPTION
**Pull request by rahul27**
Updated the BV transform function.

GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by rahul27** [comment]
Should fix https://github.com/Samsung/GearVRf/issues/886

**Comment by rahul27** [comment]
Lets wait for a response in 886. In the meantime I will write up some tests.

**Comment by rahul27** [comment]
This one is good to go. Unless there are review comments?

Here are the tests for the change, that should probably catch future regressions:

https://github.com/gearvrf/GearVRf-Tests/pull/23

**Comment by liaxim** [comment]
Nice job. No issues in immersivepedia. Tests pass.

Fixes a subtle bug I noticed in the tutorial app. The score has been off-centered for some time. Now we know why. Will merge in the afternoon.

**Pull request merged**
