### PR TITLE
Call handleOnDock explicitly for devices that doesn't listen for dock …

### PR DESCRIPTION
**Pull request by sivapenke**
…events

Signed-off-by: Siva Penke <siva.penke@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
I don't think we can call handleOnDock() unconditionally. What if the device is in developer mode?

**Comment by liaxim** [comment]
Looked at it closer. Unfortunately the polling check I believe is still needed since we had problems with the listener not getting events on some devices. Based on your idea, I have come up with https://github.com/liaxim/GearVRf/tree/alwaysdock which should work both for your and the general case.

**Comment by liaxim** [comment]
@sivapenke What do you think the commit in https://github.com/liaxim/GearVRf/tree/alwaysdock?

**Comment by sivapenke** [comment]
Do you think this is more appropriate? Though it adds an extra 'if' statement it makes readable and does extra check of isMonoscopic Mode for SAVR. Rest looks good.

if(!isMonoscopicMode) {
	if (null != mDockEventReceiver && localConfigurationManager.isDockListenerRequired()) {
		//drop-in
	} else {
		//savr
		handleOnDock();
	}
}

**Comment by liaxim** [comment]
@sivapenke Yes. Will make the change.

**Comment by liaxim** [comment]
@sivapenke Should we close this?

**Comment by sivapenke** [comment]
@liaxim Yes.

**Pull request closed without merging**
