### PR TITLE
framework: fix gvrmesh.getvertices

### PR DESCRIPTION
**Pull request by liaxim**
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov m.marinov@samsung.com

### CODE REVIEW

**Comment by NolaDonato** [comment]
If we are going to add getVerticesDirect, what about indices, texcoords, normals? We have accessors for those too. Personally I think these one-liners make the API kinda messy. Maybe just documenting in getVertices how you would access them as a buffer might cover the issue? In any case, if we are going to add a Direct option for vertices, we should add it for the others as well. I think the same bug also exists for getNormals and getTexCoords. I obviously did not understand the nuances of Java Direct buffers when I wrote that code :-)

**Comment by liaxim** [comment]
It is not just a one liner. It allows you avoiding yet another copy, hence direct. Not that there is no copying already on the native side. To be honest there is no need for the direct buffers since the consumers are almost guaranteed to be Java consumers.

The other needs that too. When I get to them after creating a test and exercising them all.

**Comment by NolaDonato** [comment]
The direct buffers on input are for assimp. If we take in direct buffers we can avoid a copy because we can directly use the C++ arrays.  If you don't think we need them on output then we can remove these methods. I figured if we took them in we should output them as well but I am OK if we remove them. Simple is better.

**Comment by liaxim** [comment]
For output we can let the users decide. Hence two methods for user convenience. It is likely they need Java friendly output but we can't assume. If you prefer to fix it, let me know and I will close. The user has already figured out a workaround.

**Comment by NolaDonato** [comment]
Are you going to fix normals and texcoords too?

**Comment by liaxim** [comment]
Yes, but I want to add a simple test case together with those changes.

**Comment by liaxim** [comment]
Update few more APIs, fixed a problem with getIndices. Added a simple test in https://github.com/gearvrf/GearVRf-Tests/pull/214.

**Comment by liaxim** [comment]
@NolaDonato Please review

**Comment by NolaDonato** [comment]
You can just call GVRVertexBuffer.getFloatArray in GVRMesh.getVertices. It is a native function which returns a Java array directly.

**Comment by liaxim** [comment]
Using getFloatArray instead

**Comment by liaxim** [comment]
Planning to merge on Wednesday

**Pull request merged**
