### PR TITLE
Made GVRAnchor, GVRPlane components, simplified hit testing

### PR DESCRIPTION
**Pull request by NolaDonato**
1. GVRAnchor & GVRPlane are now components, since they are both attached to scene objects. (This is why we did components in the first place).
2. Simplified AR hit testing, eliminating the need to know about the pass thru object.
    If not hit testing against the pass thru, use collision hit location directly
3. Fixed box collider hit testing

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

A pull request for the AR avatar demo will follow shortly

### CODE REVIEW

**Comment by ragner** [comment]
Hi @NolaDonato,
ARCoreAnchor is going to change the model matrix of sceneObject at every frame step.
It is a problem, for example, if the scene object is a 3d model loaded and it was scaled by the application.  So the 3d model will loose its scale after it has been attached to the anchor.

In my opinion, ARCoreAnchor could have a internal sceneObject and be attached to it. So we could add the sceneObject from the application as child of the  ARCoreAnchor's scene object. 

The same comment to ARCorePlane.

My point is: ARCoreAnchor and ARCorePlane don't change the model matrix of the scene object "attached" to them. Otherwise the application will have to create a sceneObject just to attach the ancho to it and then add the "visible 3d model" as child of this sceneObject to avoid changes at model matrix of the "visible 3d model"

**Comment by NolaDonato** [comment]
The asset loader already puts an extra scene object on most models. The only case for which this is not true is a single mesh with no children (your "andy" model falls in this category). If the application has to add a scene object anyway, why make it internal to MixedReality? I agree that if we could keep it totally internal and hidden from the application we should do this. But we can't actually do that because the application chooses where it wants the model to go in the scene.

**Comment by ragner** [comment]
@dsazulay Could you test this PR with gvr-arcore demo, doing the proper adjusts to the demo?

**Comment by NolaDonato** [comment]
?I have already done this work. I just made a pull request for GearVRf-Demos.


________________________________

**Comment by NolaDonato** [comment]
I will try to merge them

**Comment by NolaDonato** [comment]
Merge PR #2016 with this PR

**Comment by NolaDonato** [comment]
Verified working with gvr-arcore, gvr-avatar from PR #648 from GearVRf-Demos

**Comment by NolaDonato** [comment]
@ragner, @dsazulay please check my work. I tried to add you as reviewers and failed miserably.

**Comment by liaxim** [comment]
Should we close?

**Comment by ragner** [comment]
We have some fix for this. 
But we are going to make it at sxrsdk.
The issue is related to the update of plane's size

**Comment by liaxim** [comment]
Closing then

**Pull request closed without merging**
