### PR TITLE
Widget plugin modified according to GVRCollider and Picking changes

### PR DESCRIPTION
**Pull request by apjagdale**

### CODE REVIEW

**Comment by liaxim** [comment]
Depends on https://github.com/gearvrf/GearVRf-Demos/pull/419

**Comment by NolaDonato** [comment]
I have reviewed and tested this change. If no-one else has feedback we can merge tomorrow.

**Comment by liaxim** [comment]
We can't merge until https://github.com/gearvrf/GearVRf-Demos/pull/419 is merged - otherwise apps using libgdx would not compile.

I found a problem with gvr-bullet in https://github.com/gearvrf/GearVRf-Demos/pull/419 and couple of other minor things.

**Comment by liaxim** [comment]
Adding this to the 3.2 milestone since we need it for the demos api cleanup.

**Comment by liaxim** [comment]
Looks good. Will merge Tuesday morning.

**Pull request merged**
