### PR TITLE
[GearVRf] Sample application: how to handle input from a gamepad (related to #74)

### PR DESCRIPTION
**Pull request by dknaan**
A new sample application to demonstrate how to handle input from a gamepad. Fire keys change background colors. Left motion key translates the scene.

### CODE REVIEW

**Comment by jason2kim** [comment]
Thanks Dotan, let me review your gamepad sample shortly. I’ve got a device now^^

**Comment by chenchao1407** [comment]
One concern I found which is not related to input event(or maybe any kind of event not from GL Thread) is like, it can't handle change which directly calls GL commands. So you can't do something like Texture.update() or GVRConsole.writeLine() with these kinds of events.

Codes look good to me. However I may need to find a gamepad to do the verification.

**Comment by dknaan** [comment]
OK, please let me know if you have any concern regarding this pull request or regarding the performance of this sample. Thanks

**Comment by jason2kim** [comment]
Sdk settings in the manifest, need to be aligned with:
    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="21" 

Handlers never return false, either consumed or not: dispatchKeyEvent() and dispatchGenericMotionEvent()
   
Need to decide to catch on which key event, UP or DOWN, but should not be both: e.g.  public boolean dispatchKeyEvent(android.view.KeyEvent event) {
        if (event.getAction()== KeyEvent.ACTION_UP) {. . .

In code files,
Can remove unused lines of  “import . . .” in the .java files
Avoid unnecessary blank lines, especially at the beginning and end of each method. I assume this is your personal coding style, but...

**Comment by dknaan** [comment]
Thanks for your comments. I will take care of it when I'm back from PTO.

**Comment by dknaan** [comment]
Small corrections to the code:
- dispatchGenericMotionEvent and dispatchKeyEvent call super if the event is no$
- in dispatchKeyEvent only ACTION_DOWN is handled
- unused imports and empty lines were removed
- Android minSdkVersion and targetSdkVersion were changed

**Comment by jason2kim** [comment]
It looks good to me.

**Comment by thomasflynn** [comment]
looks good to me as well.

**Comment by thomasflynn** [comment]
i'll probably add some additional code this weekend so people can see how to track the other axes and buttons.

**Comment by dknaan** [comment]
Other buttons can be added, but I implemented only a very basic sample assuming we just want to demonstrate how to handle key events from the gamepad.

**Comment by jason2kim** [comment]
I think adding additional features to this basic sample would be a good idea. GearVRf users also will do that based on this sample.
I saw Android documents specific to this topic, including code examples for various controller actions

**Pull request merged**
