### PR TITLE
Fixed problm specifying GLSL shader version

### PR DESCRIPTION
**Pull request by NolaDonato**
This fix applies only to shaders derived from GVRShaderTemplate using the constructor that specifies the GLSL version.
 GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by thomasflynn** [comment]
@deepakrawat22 ?

**Comment by liaxim** [comment]
The "es" part is required for 300. Shader compilation will fail for those shaders. I'd say just omit the version if 100 is needed.

**Comment by NolaDonato** [comment]
I changed the default version to 100.  GVRPhongShader now explicitly specifies 300.

**Comment by liaxim** [comment]
Looks good.

**Comment by liaxim** [comment]
@deepakrawat22 Does this solve your problem?

**Pull request merged**
