### PR TITLE
ovractivity correct default settings + signalled vulkan fence

### PR DESCRIPTION
**Pull request by sushantojal**
gvr-simplesample runs with these changes for vulkan.

setting fence flag to signaled state.
setting default fbo resolution from OvrActivityDelegate.

### CODE REVIEW

**Comment by liaxim** [comment]
Yep, now gvr-simplesample shows something. @sushantojal Are you going to address the flickering as part of this pull request or subsequently?

**Comment by sushantojal** [comment]
I'm working on it, would like to have it as a part of this pull request.

**Comment by sushantojal** [comment]
There was a misplaced brace in OVRViewManager.java from a previous commit. 
Also, removed the check for render target in copyVulkanTexture since  render targets are now created in onSurfaceChanged.

**Comment by liaxim** [comment]
Awesome. Planning to merge on Friday.

**Pull request merged**
