### PR TITLE
Add a convenience getGVRContext method to GVRScript and GVRMain

### PR DESCRIPTION
**Pull request by liaxim**
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@rahul27 What do you think about this? We can eliminate redundant code from pretty much all of the apps.

**Comment by rahul27** [comment]
What is the redundant code that this helps with?

**Comment by liaxim** [comment]
Everybody creates a member variable in their GVRScript/GVRMain to store the context in, for example.

**Comment by rahul27** [comment]
Ahh, I see. Looks good :+1:

**Pull request merged**
