### PR TITLE
Add event handler to GVRExternalScene

### PR DESCRIPTION
**Pull request by NolaDonato**
Since GVRExternalScene loads the asset in another thread, an event handler is needed if the caller wants to know when the asset has loaded. This is to support X3D loading FBX, OBJ and other models.

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
No actual file changes associated with this pull request

**Comment by NolaDonato** [comment]
oops I pushed but didn't commit

**Comment by mwitchwilliams** [comment]
Tested code using X3D _Inline_ embedding various .FBX and .OBJ meshes including: textured FBX penguin, and textured FBX teapot with animation invoked by X3D _TouchSensor_.  All worked well.   Code looks good too - no commented out code, all proper indenting.

**Comment by liaxim** [comment]
If rebased or merged leads to a compilation error in a new loadModel overload added by the assimp change:

```
 public GVRModelSceneObject loadModel(GVRAndroidResource resource,
                                         EnumSet<GVRImportSettings> settings,
                                         boolean cacheEnabled,
                                         GVRScene scene) throws IOException
```

The error:
```
GearVRf/GVRf/Framework/framework/src/main/java/org/gearvrf/GVRAssetLoader.java:1230: error: no suitable constructor found for AssetRequest(GVRModelSceneObject,GVRResourceVolume,GVRScene,boolean)
        AssetRequest assetRequest = new AssetRequest(model, volume, scene, false);
                                    ^
    constructor AssetRequest.AssetRequest(GVRContext,GVRResourceVolume) is not applicable
      (actual and formal argument lists differ in length)
    constructor AssetRequest.AssetRequest(GVRContext,GVRAndroidResource,GVRScene) is not applicable
      (actual and formal argument lists differ in length)
    constructor AssetRequest.AssetRequest(GVRSceneObject,GVRResourceVolume,GVRScene,IAssetEvents,boolean) is not applicable
      (actual and formal argument lists differ in length)
```

It *can* be rebased or merged but will produce non-compilable code which is better corrected by you. I can build and try your branch directly but we should be testing the change on top of the latest master. Please rebase.

**Comment by NolaDonato** [comment]
I have fixed the merge conflict and added a small fix for the issue where inline content loads lights and they don't take effect.

**Comment by liaxim** [comment]
Looks good. Will merge Friday morning.

**Pull request merged**
