### PR TITLE
Add surface normals to picking information

### PR DESCRIPTION
**Pull request by J0Nreynolds**
A small PR to add surface normals to picking information. Note that the normals are calculated in model coordinates just as the hit coordinates are.

### CODE REVIEW

**Comment by NolaDonato** [comment]
If we are going to add so many arguments to the pick object, lets figure out a way to not do it in the case where it is not needed. We should only pass all this stuff if it is a mesh collider that has enabled the option.

**Comment by J0Nreynolds** [comment]
@NolaDonato Another pull request is coming soon to address this - I just needed this PR so people can review #1288.

**Comment by liaxim** [comment]
Will merge on Wednesday.

**Comment by liaxim** [comment]
Needs DCO per https://resources.samsungdevelopers.com/Gear_VR_and_Gear_360/GearVR_Framework_Project/040_Get_Involved/GearVRf_Developer_Certificate_of_Origin

**Comment by J0Nreynolds** [comment]
GearVRf-DCO-1.0-Signed-off-by: Jonathan Reynolds j.reynolds@partner.samsung.com

**Comment by NolaDonato** [comment]
Looks good to me too. Are there unit tests for this feature?

**Pull request merged**
