### PR TITLE
Enables changing Texture maps in X3D.

### PR DESCRIPTION
**Pull request by mwitchwilliams**
Using JavaScript &lt;SCRIPT&gt; nodes, we can change texture maps on objects.

Test cases are located in Pull Request https://github.com/gearvrf/GearVRf-Tests/pull/223

This Pull Request supersedes https://github.com/Samsung/GearVRf/pull/1675, which was originally built on work-in-progress Pull Request.
This new Pull Request is instead built upon Master.

GearVRF DCO signed off by: Mitch Williams
m1.williams@partner.samsung.com

### CODE REVIEW

**Comment by mwitchwilliams** [comment]
Made suggested changes from Nola, and retested.

**Comment by liaxim** [comment]
Got this and the corresponding test pull requests, ``git clean -fdx``-ed all repos, copied all the assets from "x3d/texture map changes", built and installed gvr-x3d-demo with JSChgTexture-SimpleDemo.x3d and then with JSChgTexture-InteractiveTextureChg.x3d. What I am seeing doesn't match the document. I don't see any changes happening when I roll over per the document's instructions.

jschgtexture-interactivetexturechg x3d

x3djschgtexture-simpledemo x3d

Is the scripting at fault here?

**Comment by mwitchwilliams** [comment]
In the top image, the red box must be **clicked on,** not just rolled over, to change to a blue box.
But I am wondering if the Sensors are not working at all.  In December, Master had sensors broken.
Could you test the x3d -> TouchSensors demo(s), such as touchSensor1.x3d, to validate that sensors did not break again?

**Comment by liaxim** [comment]
Tested SimpleDemo_diffuseChangeOnly.x3d you sent me. It has to be the sensors. If you could add couple of tests that do not rely on the sensors we can move along with this change. And deal with the sensors separately.

**Comment by mwitchwilliams** [comment]
Thanks for the confirmation.
**JSChg-OneSecPerFrame.x3d** is not invoked by sensors, but instead is called every second by 'onDrawFrameListener'. It changes the texture map displaying 1 thru 5 every second.

I can confirm if this is indeed a sensor issue - is this with the latest version of Master?

**Comment by liaxim** [comment]
Ok, will test with JSChg-OneSecPerFrame.x3d. Yes, latest master.

**Comment by mwitchwilliams** [comment]
Tested against Master.
Procedural animations called by 'onDrawFrame()' with **no Sensors** for interactivity from the tests repo-> x3d->Scripting_Per_Frame -> _JavaScript_PerFrame_01_ProceduralAnim.x3d_ and _JavaScript_PerFrame_03_TimeStamp.x3d_ work fine.

However, those interactive demo's from test repo-> x3d -> TouchSensors -> _touchSensor4.x3d_ and _touchSensor5.x3d_, plus other TouchSensor/interactive demo's, do not work.
Seems like the call backs from Sensors is broken, similar to late December.

Advise if you want me to do any more testing in X3D -> AnimationInterctivityManager.java

**Comment by liaxim** [comment]
JSChg-OneSecPerFrame.x3d works. The change looks good. The sensor stuff is a separate issue. Planning to merge on Friday.

**Pull request merged**
