### PR TITLE
Throttler must inform in case of failure

### PR DESCRIPTION
**Pull request by deepakrawat22**
Also added all the type of texture name supported by Assimp

GearVRf-DCO-1.0-Signed-off-by: 
Deepak Rawat deepak.rawat@samsung.com

### CODE REVIEW

**Comment by NolaDonato** [comment]
Please test this with cube_wrongtex.fbx and let me know if it handles the missing texture properly. I will email you this file.

**Comment by liaxim** [comment]
@deepakrawat22 What were the results of the test? Thanks.

**Comment by deepakrawat22** [comment]
@liaxim There was a crash after I commented return statement. Will investigate more the reason behind the carsh.

**Comment by deepakrawat22** [comment]
@NolaDonato With cube_wrongtex.fbx it gave file not found exception as the png file was not there.

**Comment by NolaDonato** [comment]
Yes, the asset is missing a texture intentionally to test this case. GVRAssetLoader.loadModel should refuse to put this asset in the scene if the file not found exception is thrown. Is that what it does now?

**Comment by liaxim** [comment]
@deepakrawat22 What is the status of this? Thanks.

**Comment by deepakrawat22** [comment]
This pull request was to refactor Throttler code that it must inform in case its not able to load a resource file, earlier it used to throw exception. I didn't made any changes to GVRAssetLoader.loadModel.

Another change was I added all the types of texture supported by assimp, in the textureMap

**Comment by liaxim** [comment]
Ok. So from your point of view there is no more work left for this pull request?

**Comment by deepakrawat22** [comment]
Earlier TextureRequest failed() method was not getting called, now it will be called in case a texture file is not supported.

**Comment by deepakrawat22** [comment]
@liaxim yes no more work on this pull request.

**Comment by liaxim** [comment]
Looks good. Will merge after lunch.

--
Not sure the callbacks copying is necessary. Adding a callback happens only if the thread owns the pendingRequests monitor so just clearing the callbacks member should have been enough. Also not so sure new threads will not be spawned; at least theoretically seems possible to me and inevitable since we remove the pendingRequest from the requests array.

Hopefully we will get to streamline and simplify this code; it is doing most likely more than what we actually need.

**Pull request merged**
