### PR TITLE
Fix a crash due to a mesh without normals

### PR DESCRIPTION
**Pull request by liaxim**
gvr-controls known to be affected

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
@roshanch Please review

**Comment by Vittalbabu** [comment]
What happens if tex_cords are empty? Do we need to pull that out of the vertices loop like normals or will that never occur?

**Comment by roshanch** [comment]
@liaxim  I added this check in #775 .

**Comment by roshanch** [comment]
@Vittalbabu We are batching only with texture shader. I would add again error message if texCords are not present.

**Comment by thomasflynn** [comment]
the change looks sane.

**Comment by liaxim** [comment]
Will merge after lunch.

**Comment by Vittalbabu** [comment]
More of an FYI -- the normal size and vertices size have to match else the Mesh::generateVAO code will not generate a mesh in some circumstances. Adding a LOG stmt if the sizes do not match might help.

**Comment by liaxim** [comment]
@Vittalbabu Added the requested log trace to mesh.cpp. Let me know whether this is ok.

**Comment by Vittalbabu** [comment]
Leave aLooks good. comment

**Comment by liaxim** [comment]
Thanks. Will merge in the evening.

**Pull request merged**
