### PR TITLE
Remove GLES2.0 from shaders

### PR DESCRIPTION
**Pull request by ragner**
Shaders cleanup removing GLES2.0

GearVRf-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>

### CODE REVIEW

**Comment by thomasflynn** [comment]
seems as though you could remove the ifdefs for USE_GLES3 as well

**Comment by ragner** [comment]
Should I also remove the line <code> #define _GVRF_USE_GLES3_  1</code> from <code>jni/util/gvr_gl.h</code>?

**Comment by thomasflynn** [comment]
theoretically, that define would no longer be necessary so it could be removed.

**Comment by ragner** [comment]
Done.

**Comment by thomasflynn** [comment]
ok, code looks like what i would expect now.  just needs testing.

**Comment by thomasflynn** [comment]
builds.  tested with several samples.  things look fine.  nothing blew up :).

**Pull request merged**
