### PR TITLE
Add a sample using Vuforia.

### PR DESCRIPTION
**Pull request by rongguodong**
Use Vuforia image target to rotate and translate the bunny.

GearVRf-DCO-1.0-Signed-off-by: Guodong Rong
rongguodong@hotmail.com

### CODE REVIEW

**Comment by rongguodong** [comment]
User can printer out "target_stones_USLetter.pdf" and "target_chips_USLetter.pdf" for image targets.

**Comment by thomasflynn** [comment]
tried to import and build it, got the following error:

BUILD FAILED
/home/flynnt/trees/gearvrf/GearVRf/GVRf/Sample/gvr-vuforia/CopyVuforiaFiles.xml:4: /home/flynnt/trees/gearvrf/GearVRf/GVRf/Sample/gvr-vuforia/src/armeabi-v7a does not exist.

**Comment by rongguodong** [comment]
Hmm, it seems the folder "armeabi-v7a" (which contains the necessary .so file) is not checked in. I will add it tomorrow morning.

**Comment by rongguodong** [comment]
The file libVuforia.so is not checked in because .gitignore ignored all .so files. I have edited .gitignore and added libVuforia.so.

Also rebased with top of master.

**Comment by thomasflynn** [comment]
ok, it compiles and works as expected now.

**Pull request merged**
