### PR TITLE
backend_oculus: try to fix #1355, "Scene blinks after back key pressed"

### LINKED ISSUE #1355: Scene blinks after back key pressed
Hi all,
The scene is blinking after back key pressed.
You can see this issue easily on gvr-keyboard demo but it happens at other demos also.

To reproduce you just need launch the application wait for it be ready
so press back key twice.

We are facing this issue at our "Look To The Sky" application also.

Does anybody could help me with this?

### PR DESCRIPTION
**Pull request by liaxim**
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by ragner** [comment]
@liaxim yes,
it works for me.

**Comment by dnvasilev** [comment]
@liaxim , what work needs to be completed on this pull request?

**Comment by liaxim** [comment]
Test it on various phones and Android versions.

**Comment by liaxim** [comment]
Planning to merge on Tuesday.

**Comment by liaxim** [comment]
@dnvasilev Can't cherry-pick due to a lot of unnecessary whitespace differences in ovr_activity.cpp.

**Pull request merged**
