### PR TITLE
vulkan: Adding the latest code 

### PR DESCRIPTION
**Pull request by rahul27**
GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by rahul27** [comment]
@NolaDonato @Vittalbabu Could you confirm everything looks good with the pull request?

If it checks out then we can go ahead and merge it.

**Comment by NolaDonato** [comment]
The experimental gradle build fails like this for me:

Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':backend_oculus'.
> Exception thrown while executing model rule: BaseComponentModelPlugin.Rules#createVariantData(ModelMap<AndroidBinaryInternal>, ModelMap<AndroidComponentSpec>, TaskManager) > afterEach()
   > Could not resolve all dependencies for configuration ':backend_oculus:_debugPublish'.
      > Exception thrown while executing model rule: BaseComponentModelPlugin.Rules#createAndroidComponents(ModelMap<AndroidComponentSpec>, ServiceRegistry, AndroidConfig, AndroidConfig, ModelMap<BuildType>, ModelMap<ProductFlavor>, ModelMap<SigningConfig>, VariantFactory, TaskManager, Project, AndroidBuilder, SdkHandler, ExtraModelInfo, Boolean)
         > Failed to find target with hash string 'android-25' in: C:\sdk\android

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 29.029 secs

**Comment by NolaDonato** [comment]
I get this build failure:

Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':backend_oculus'.
> Exception thrown while executing model rule: BaseComponentModelPlugin.Rules#createVariantData(ModelMap<AndroidBinaryInternal>, ModelMap<AndroidComponentSpec>, TaskManager) > afterEach()
   > Could not resolve all dependencies for configuration ':backend_oculus:_debugPublish'.
      > Exception thrown while executing model rule: BaseComponentModelPlugin.Rules#createAndroidComponents(ModelMap<AndroidComponentSpec>, ServiceRegistry, AndroidConfig, AndroidConfig, ModelMap<BuildType>, ModelMap<ProductFlavor>, ModelMap<SigningConfig>, VariantFactory, TaskManager, Project, AndroidBuilder, SdkHandler, ExtraModelInfo, Boolean)
         > Failed to find target with hash string 'android-25' in: C:\sdk\android

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 29.029 secs

**Comment by rahul27** [comment]
All the backends on master have been updated to use android version 25. 

Downloading android 25 using your SDK manager should fix your issue.

**Comment by NolaDonato** [comment]
After updating to Androi 25 I get this:
External Native Build Issues
    Build command failed.
    Error while executing 'C:\sdk\android\ndk-bundle\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\projects\android\GearVRf\GVRf\Framework\framework\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\projects\android\GearVRf\GVRf\Framework\framework\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDEBUG=1 APP_PLATFORM=android-19 NDK_OUT=C:/projects/android/GearVRf/GVRf/tools/Framework/framework/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\projects\android\GearVRf\GVRf\tools\Framework\framework\build\intermediates\ndkBuild\debug\lib -j4 NDK_DEBUG=1 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -n}
    process_begin: CreateProcess(NULL, "", ...) failed.
    Error:Error:executing external native build for ndkBuild C:\projects\android\GearVRf\GVRf\Framework\framework\src\main\jni\Android.mk
    Build command failed.
    Error while executing 'C:\sdk\android\ndk-bundle\ndk-build.cmd' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\projects\android\GearVRf\GVRf\Framework\framework\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\projects\android\GearVRf\GVRf\Framework\framework\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDEBUG=0 APP_PLATFORM=android-19 NDK_OUT=C:/projects/android/GearVRf/GVRf/tools/Framework/framework/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=C:\projects\android\GearVRf\GVRf\tools\Framework\framework\build\intermediates\ndkBuild\release\lib -j4 NDK_DEBUG=1 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -n}
    process_begin: CreateProcess(NULL, "", ...) failed.
    Error:Error:executing external native build for ndkBuild C:\projects\android\GearVRf\GVRf\Framework\framework\src\main\jni\Android.mk
C:\sdk\Android\ndk-bundle\sources\third_party\shaderc\third_party\Android.mk
    Error:Error:line (123)*** target pattern contains no `%'.  Stop.
<a href="openFile:C:/sdk/Android/ndk-bundle/sources/third_party/shaderc/third_party/Android.mk">Open File</a>
    Error:Error:line (123)*** target pattern contains no `%'.  Stop.
<a href="openFile:C:/sdk/Android/ndk-bundle/sources/third_party/shaderc/third_party/Android.mk">Open File</a>

**Comment by liaxim** [comment]
The vulkan branch with @rahul27 's changes builds just fine for me.

**Comment by rahul27** [comment]
There seems to be an issue with building it on windows.

**Comment by liaxim** [comment]
What is the relationship of this pull request to https://github.com/Samsung/GearVRf/pull/997?

**Comment by rahul27** [comment]
@liaxim I am not sure.

@NolaDonato do you still need this pull request?

**Comment by NolaDonato** [comment]
No, this code has been merged into 997.

**Pull request closed without merging**
