### PR TITLE
Updated the google vr libraries to v1

### PR DESCRIPTION
**Pull request by rahul27**
GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by rahul27** [comment]
Updated the demos here:

https://github.com/gearvrf/GearVRf-Demos/pull/341

**Comment by liaxim** [comment]
gvr-cardboard-audio requires some work

**Comment by liaxim** [comment]
gvr-cardboard-audio works with the default configuration and with only_daydream=true.

Crashes though with no_oculus=true; ``./gradlew -Pno_oculus=true clean installDebug``

**Comment by rahul27** [comment]
I added a commit to fix the build with no_oculus=true.

Do you still see it with master?

**Comment by liaxim** [comment]
No problems; all combinations work.

**Pull request merged**
