### PR TITLE
Port to the Oculus 0.5.0 sdk.

### PR DESCRIPTION
**Pull request by thomasflynn**
The 0.5.0 sdk has some minor API changes.  Mostly adding some extra
arguments to some methods.  This change addresses that.  (rebased edition)

GearVRf-DCO-1.0-Signed-off-by: Tom Flynn
tom.flynn@samsung.com

### CODE REVIEW

**Comment by thomasflynn** [comment]
Ok, this is rebased and the spacing should be fixed.  Once this goes in, we'll need to update the build instructions in the Dev Guide.  I can take care of that.

**Comment by JonShemitz** [comment]
The code looks fine - will switch to new VRLib and verify, after lunch. (If I verify now, there may be no food by the time I get down there.)

**Comment by JonShemitz** [comment]
Verified. We can pull the change as soon as we've updated the Developer's Guide.

**Comment by chenchao1407** [comment]
Verified + 1. Code Review + 2 :-)

**Comment by thomasflynn** [comment]
ok, changed the build instructions on the wiki.  The pdf of the Dev Guide still needs to be updated, re-generated and uploaded to the wiki, but that's a lengthy process that can be done tomorrow.

**Pull request merged**
