### PR TITLE
Optimize animation data structures

### PR DESCRIPTION
**Pull request by NolaDonato**
Use an array of floats for key data instead of separate vectors and quaternions. Update importer to use new APIs.

Tested with animation tests, gvr-meshanimation, gvr-javascript

GearVRf DCO signed off by: Sahithi Podila s.pod@samsung.com Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by NolaDonato** [comment]
I have tested this code with the framework tests, asset tests, gvr-meshanimation, gvr-javascript, gvr-morph and gvr-immersivepedia.

**Comment by apjagdale** [comment]
Tested with demos. It works.

**Comment by NolaDonato** [comment]
I will merge this PR tonight if there are no objections.

**Comment by liaxim** [comment]
Looks good. X3D needs a minor update and verification and we can merge.

**Pull request merged**
