### PR TITLE
X3D Texture Change, Sprite Anim

### PR DESCRIPTION
**Pull request by mwitchwilliams**
Enables Texture Maps to be changed via JavaScript

Dependent on merge of PullReq https://github.com/Samsung/GearVRf/pull/1646 since this fixed Touch Sensors.

Only 5 files in this Pull Req: x3d/AnimationInteractivityManager.java, x3d/X3Dobject.java, x3d/data_types/MFString.java, x3d/data_types/MFVec3f.java and x3d/data_types/MField.java

GearVRF DCO signed off by: Mitch Williams
m1.williams@partner.samsung.com

### CODE REVIEW

**Comment by mwitchwilliams** [comment]
Test Cases:
[JavaScript Change Textures Demos.zip](https://github.com/Samsung/GearVRf/files/1583372/JavaScript.Change.Textures.Demos.zip)

**JSChgTexture-SimpleDemo.x3d**
Change texture and diffuseColor
jschgtexture-simpledemo01
jschgtexture-simpledemo02

**JSChgTexture-InteractiveTextureChg.x3d**
Rollover numbers changes textures on the left.  Click changes textures with colors on the right
jschgtexture-interactivetexturechg

**JSChg-OneSecPerFrame.x3d**
changes each number every second.  Sphere is not a texture change, but is rotated within the same JavaScript &lt;SCRIPT&gt; node.
jschg-onesecperframe

**JSChg-SpriteAnimation.x3d**
Dog walking animation. Sphere is same as above
jschg-spriteanimation

**JSChg-TwoSpriteAnimations**
Present rotating and Dog walking. Sphere is same as above.
jschg-twospriteanimations

**Comment by thomasflynn** [comment]
has conflicts

**Comment by mwitchwilliams** [comment]
When I started working on this feature, master v4.x was broken - interactivity wasn't working, no callback's for touch sensors - so I built on top of Nola's cursor code which had interactivity/touch sensors working.
Master's callback's for touch sensors are ok now.  So I will rebuild and test this against the latest master.

**Comment by mwitchwilliams** [comment]
This Pull Request, which was built upon https://github.com/Samsung/GearVRf/pull/1646,  is superseded by Pull Request https://github.com/Samsung/GearVRf/pull/1699, which was built upon Master.

**Pull request closed without merging**
