### PR TITLE
backend_oculus: fix controller reader npe

### PR DESCRIPTION
**Pull request by liaxim**
Looks like the NPE caused by the recent controller change is easy enough to fix. @roshanch Please review and verify though.

GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by roshanch** [comment]
if ovrControllerReader is instantiated in constructor, it will cause timing issues. I think @NolaDonato or @dnvasilev can comment here. I would say adding null check in viewManager would be proper fix, though i couldn't reproduce the timing issue now.

**Comment by liaxim** [comment]
Let's identify the timing issues. Null check in ViewManager may not be enough since onSurfaceCreated and onResume can happen in different order; so you may never call the reader from onResume.

**Comment by liaxim** [comment]
Now for all backends the reader is instantiated from the ctor; oculus was the exception for unknown reason. Also whatever OvrControllerReader's ctor does is pretty innocent allocation and initialization. I will deal with these timing issues if they are there.

**Comment by liaxim** [comment]
Looked back at the history. Looks like whatever race there is, it is about when a reader is attachReader-ed to the controller and not when the reader is instantiated.

**Pull request merged**
