### PR TITLE
Have GVRContextProxy derive from GVRContext

### PR DESCRIPTION
**Pull request by liaxim**
Fixes what was broken for the live scripting scenario

---
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by liaxim** [comment]
Verified I can telnet into gvr-remote-scripting and execute the sample scripts it includes.

**Comment by thomasflynn** [comment]
since i can now run the scripts, i did a little more testing.  I used to be able to do a print() on a sceneobject and it would print out info like its transform, who its parent(s) are, etc.  Now it just crashes.  To repro, execute the space_trex.js and then issue:  print(trex);

**Comment by liaxim** [comment]
Crashes in GVRBone.getFinalTransformMatrix; joml expects a direct floatbuffer but this is not what we give it. I might just eliminate the buffer altogether and construct the matrix out of the float[].

**Comment by liaxim** [comment]
Planning to merge Monday morning.

**Pull request merged**
