### PR TITLE
Picker and Controller reform

### PR DESCRIPTION
**Pull request by NolaDonato**
1. Added GVRBoundsPicker to implement object cursor hit testing
2. Added hit testing against sphere for all colliders
3. Added ITouchEvents interface for touch events
4. GVRKeyboardSceneObject listens for touch events
5. GVRPicker (GVRCursorController integration)
- setController to attach controller to picker
- added setEventOptions to allow more flexible event routing
- generate ITouchEvents when controller attached
- implement GVREventReceiver to allow multiple listeners
- onPick and onNoPick now called every frame instead of when pick list changes
6. GVRCursorController (GVRPicker integration)
- cursor controller has its own picker to control the ray & emit events
- controller drivers picker to supply touch information
- controller listens for pick events to move cursor
- GVRGazeCursorController sets cursor depth
7. GVRBaseSensor changes
- it is now a component
- it listens for touch events instead of controller events
- sensor handler looks upwards in hierarchy for closest sensor
- eliminated SensorManager class
8. 3D Cursor extension
- CursorManager listens for ITouchEvents, generates ICursorEvents
- Cursor is now a component
- eliminated CursorSceneObject, CursorEvent, CursorEventListener
- added ICursorEvents (like ITouchEvent with a cursor)
- simplified event handling internally

This pull request has companion patches for GearVRf-Demos and GearVRf-Tests
GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
gvr-controller: choose an object, press and hold and start moving it around; quite often as you pass over other objects whatever you have currently selected is swapped with whatever else you are passing over. For example, if I move a bunny it always gets replaced by a cube if I pass over one. Tested on S8.

**Comment by liaxim** [comment]
gvr-events: selecting something in the list view is challenging; it seems to me like I have to click above the item to select it. Would be nice if it was possible to scroll the listview somehow.

**Comment by liaxim** [comment]
gvr-immersivepedia: controller just doesn't work that well for me; doesn't seem like clicks are always registered; activating the gallery totem brings up 6 quads, most flicker if the controller is over them; I remember at least of them being selectable but can't do it with the controller; if selected it should become bigger.

**Comment by liaxim** [comment]
Overall the demos have less code but I am pretty sure in the future our APIs can be simplified further. For example I find it unnecessary complication having to create an activityTouchHandler and manage it on the app side (gvr-immersivepedia).

**Comment by liaxim** [comment]
Ok, so this is a good milestone that we can merge as-is and continue ironing out the problems. They don't seem to be that many. @NolaDonato let me know whether you want to have this merged in this intermediate state or whether you'd like to have it completed first. I could help you with the bug fixing too.

**Comment by NolaDonato** [comment]
You can merge it. I have another bunch of changes to get the scene editor and widget viewer working with the controller but these can be part of another patch. Yes, I need help with the bug fixing. This is what happens when a graphics person takes over IO :(

**Comment by liaxim** [comment]
Ok. Planning to merge on Tuesday. Will look into the bugs.

**Pull request merged**
