### PR TITLE
framework: have bitmap textures created by the asset loader tested for alpha too

### PR DESCRIPTION
**Pull request by liaxim**
Related to https://github.com/gearvrf/GearVRf-Tests/issues/126 and https://github.com/Samsung/GearVRf/pull/1433

---
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by dnvasilev** [comment]
Can we check for transparency in GVRBitMapTexture.update() ? On the other hand, this will not be easy with the whole class being a bit messy with mBitmap fairly useless and update() method with a thread switch. Anyway, this is fixed in the Vulkan branch.

**Comment by liaxim** [comment]
Will wait and see what's the situation in the vulkan branch.

**Comment by dnvasilev** [comment]
#1370 is the Vulkan implementation.
In Vulkan, bitmap updates are routed through GVRBitmapTexture.setBitmap() to the native code. In the native code, BitmapImage::update(JNIEnv*, jobject, bool) checks for bitmap transparency.

**Comment by liaxim** [comment]
Planning to merge on Friday

**Pull request merged**
