### PR TITLE
Keyboard input event

### PR DESCRIPTION
**Pull request by jason2kim**
GearVRf-DCO-1.0-Signed-off-by: Jason Kim
jason2.kim@samsung.com

### CODE REVIEW

**Comment by thomasflynn** [comment]
ok, looks good.

**Comment by thomasflynn** [comment]
haven't tested.

**Comment by chenchao1407** [comment]
Codes look good to me. But I currently don't have an input device to do the test. Maybe later I will verify if I can find one.

**Comment by thomasflynn** [comment]
i can give you a BT keyboard.  standby...

**Comment by chenchao1407** [comment]
Works fine with the keyboard.

**Pull request merged**
