### PR TITLE
fixed problem with shader transparency 

### PR DESCRIPTION
**Pull request by NolaDonato**
This fixes a regression introduced by the transparency fix. The multilight and eyepicking samples should be fixed by this.

### CODE REVIEW

**Comment by liaxim** [comment]
Please if possible remove the unnecessary commits. The history is difficult enough to deal with as is.

**Comment by NolaDonato** [comment]
I reverted one commit from another branch that didn't belong. The rest is from rebasing. I only changed three files.

**Comment by liaxim** [comment]
If you were rebasing there would not be merge commits.

**Comment by NolaDonato** [comment]
I am using GitHub desktop and doing “Sync”. I thought that did a rebase but I am not really sure.

**Pull request closed without merging**
