### PR TITLE
X3d sensor

### PR DESCRIPTION
**Pull request by mwitchwilliams**
New AnimationInteractiveManager and InteractiveObject files.  Add interactivity and animation functionality for X3D <TOUCHSENSOR> node

GearVRf-DCO-1.0-Signed-off-by: Mitch Williams 
m1.williams@partner.samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Please consider squashing the commits.

**Comment by liaxim** [comment]
Ran the demo with this pull request. The cone base radius is much smaller than without this change in. Is it supposed to be like this?

**Comment by mwitchwilliams** [comment]
There was a fix to parsing the “bottomRadius” parameter of the Cone discovered during testing of the Touch Sensor.  So, that is good if there is a difference.

Mitch

**Comment by thomasflynn** [comment]
i'm sorry, i missed it, how do i test this?

**Comment by mwitchwilliams** [comment]
There is a folder of tests “TouchSensors” in the GearVR-Testing repository.

I found a few outside demo’s:
http://x3dgraphics.com/examples/X3dForWebAuthors/Chapter08-UserInteractivity/_pages/page07.html

http://www.web3d.org/x3d-resources/content/examples/Basic/X3dSpecifications/_pages/page05.html

Mitch

**Comment by thomasflynn** [comment]
needs rebase now

**Comment by mwitchwilliams** [comment]
OK, investigating a potential bug first, before rebase/resubmission.
Makes sense it needs a rebase due to merge of #790 which modified the same x3dobject.java file.

Mitch

**Comment by thomasflynn** [comment]
still reporting it has conflicts.  rebase?

**Comment by liaxim** [comment]
Rebased

**Comment by thomasflynn** [comment]
how do i test this?

**Comment by liaxim** [comment]
Needs rebase

**Comment by thomasflynn** [comment]
yes, but thankfully, i cherry-picked this before the latest commits that required this to be rebased.  i can still test, but need to know how to go about doing so.

**Comment by mwitchwilliams** [comment]
Attached is the documentation on the TouchSensor demo on GVR-Testing > X3d > TouchSensor.
There is a pull request to add this to GVR-Testing

Mitch

**Comment by thomasflynn** [comment]
once this is rebased, this can probably go in.  i tested.  i think it's doing the right thing.  i'll double check with Mitch on Tuesday.

**Comment by liaxim** [comment]
Trying touchSensor1.x3d from the tests repository yields this:

```
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err: java.io.FileNotFoundException: touchSensor1.x3d
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:363)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:337)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVRAndroidResource.openStream(GVRAndroidResource.java:338)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVRAndroidResource.getStream(GVRAndroidResource.java:298)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVRAssetLoader.loadX3DModel(GVRAssetLoader.java:959)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVRAssetLoader.loadModel(GVRAssetLoader.java:526)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.x3ddemo.X3DparserScript.onInit(X3DparserScript.java:85)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:126)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrViewManager$3$1.run(OvrViewManager.java:678)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVRContext.runOnTheFrameworkThread(GVRContext.java:2773)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrViewManager$3.beforeDrawEyes(OvrViewManager.java:670)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrViewManager.beforeDrawEyes(OvrViewManager.java:325)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrActivityDelegate$1.onBeforeDrawEyes(OvrActivityDelegate.java:191)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrVrapiActivityHandler$7.onDrawFrame(OvrVrapiActivityHandler.java:411)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1649)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1354)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo E/GVRAssetLoader: ASSET: ERROR: model touchSensor1.x3d did not load touchSensor1.x3d not found
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.gearvrf.GVRCameraRig.getChildrenCount()' on a null object reference
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.x3ddemo.X3DparserScript.onInit(X3DparserScript.java:100)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:126)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrViewManager$3$1.run(OvrViewManager.java:678)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVRContext.runOnTheFrameworkThread(GVRContext.java:2773)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrViewManager$3.beforeDrawEyes(OvrViewManager.java:670)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrViewManager.beforeDrawEyes(OvrViewManager.java:325)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrActivityDelegate$1.onBeforeDrawEyes(OvrActivityDelegate.java:191)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrVrapiActivityHandler$7.onDrawFrame(OvrVrapiActivityHandler.java:411)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1649)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1354)
```

The other test x3d files work well. Codewise, in the future you may consider making package private as many classes as possible and applying the Android Studio's auto-formatter.

Once we have a solution for touchSensor1.x3d I will merge.

**Comment by mwitchwilliams** [comment]
The error messages seem to indicate the file, touchSensor1.x3d, was not found.
It runs ok for me.  In fact, it is a simpler version of touchSensor2 through 5.
It uses no texture maps either.

I see it is in the repository.  Are you testing by modifying X3DparserScript.java or another way?

Mitch

**Comment by liaxim** [comment]
Isn't this the actual error:
```
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.gearvrf.GVRCameraRig.getChildrenCount()' on a null object reference
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.x3ddemo.X3DparserScript.onInit(X3DparserScript.java:100)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:126)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrViewManager$3$1.run(OvrViewManager.java:678)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.GVRContext.runOnTheFrameworkThread(GVRContext.java:2773)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrViewManager$3.beforeDrawEyes(OvrViewManager.java:670)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrViewManager.beforeDrawEyes(OvrViewManager.java:325)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrActivityDelegate$1.onBeforeDrawEyes(OvrActivityDelegate.java:191)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at org.gearvrf.OvrVrapiActivityHandler$7.onDrawFrame(OvrVrapiActivityHandler.java:411)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1649)
09-07 08:43:41.745 1183-1247/org.gearvrf.x3ddemo W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1354)
```

I used this pull requested and got the test x3d files from the tests repo. Will try once more.

**Comment by liaxim** [comment]
Ok, my bad. Rebuilding everything again yields the results I expected.

In X3DparserScript you should check for null the result of ``model.getCameraRig()`` and skip the headlight. It skips it now too but because a NPE is thrown. A NPE that gets logged and can be confusing.

**Comment by liaxim** [comment]
Most likely in my previous tests not all the resources I copied to the assets folder were picked by the incremental build AS performs. I should have cleaned and rebuilt the sample.

**Pull request merged**
