### PR TITLE
Eliminate GVRScene.bindShaders

### PR DESCRIPTION
**Pull request by NolaDonato**
t is no longer necessary to call bindShaders when objects are added to the scene. This function is called individually for each RenderData if the shader is not valid. It is better to defer binding the shader until it is known what type of RenderTarget it will be used with.

GearVRf DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Needs rebase

**Comment by NolaDonato** [comment]
I rebased this one

**Comment by liaxim** [comment]
Please include only the necessary files in the pull request. I can't quite guess what the actual change is. @dnvasilev was kind enough to create a git guide for us - please peruse it.

**Comment by NolaDonato** [comment]
Replaced by #1654. I tried to clean this one up in place but it didn't go as I would have liked so I am opening a new PR.

**Pull request closed without merging**
