### PR TITLE
Support rendering a scene to a texture

### PR DESCRIPTION
**Pull request by liaxim**
Demos pull request: https://github.com/gearvrf/GearVRf-Demos/pull/399

### CODE REVIEW

**Comment by liaxim** [comment]
Ready for review

**Comment by NolaDonato** [comment]
Is there some way we can implement this as a component that you attach to a scene object that will cause it to render from the camera component attached to that scene object? If we did this the feature could be used for shadow mapping and environment mapping too.

**Comment by liaxim** [comment]
I was thinking of re-implementing this as a specialization of GVRRenderTexture. Say GVRSceneRenderTexture where you pass the scene to be rendered and you just use the thing as a regular texture otherwise. No new APIs, etc. I will think about your suggestions and come up with something more useful. Thank you.

**Comment by NolaDonato** [comment]
I am excited about this feature because it will clean up the mess in that is shadow mapping. Right now this is hacked into the renderer in a very obtrustive way (mostly because I didn't want to take on reforming the render to texture stuff as you are doing now). There is a separate render texture for each shadow map but they all use the same framebuffer because they are rendered serially. Potentially this could change with Vulkan and we could render them in different threads. I know that many console and PC game engines do this, I am not sure if it is a win on mobile. We also have this thing in the C++ layer called a texture capturer. I am not sure how that fits into the scheme of things.

**Comment by liaxim** [comment]
The texture capturer is a special facility only useful if you use the external renderer shader. In their current form both the external renderer shader and the texture capturer do not belong to this repo. They should be re-implemented differently. We probably should look into generalizing the texture capturer in the future. The external renderer shader is not something that we may even need.

In my opinion you should drop both from your vulkan development branches if they cause too much headache. @thomasflynn will correct me if I am wrong.

**Comment by liaxim** [comment]
Minor change introducing GVRSceneRenderTexture and eliminating the proprietary apis.

**Comment by NolaDonato** [comment]
I tried use this new feature to help konidk on issue #1060. I set up a scene which renders a blurred version of the camera input to a quad and then tried to use that resulting texture. Your example works beautifully. Mine displays nothing when I use the render to texture. I don't think it is a problem with my shader because it seems to work OK if I don't render to a texture first. I will try to include a ZIP file with my test app in this message if possible.
[test.zip](https://github.com/Samsung/GearVRf/files/822911/test.zip)

**Comment by liaxim** [comment]
@NolaDonato I will investigate. Thanks.

**Comment by liaxim** [comment]
Applying the rendered-to-texture to a quad just doesn't work regardless everything else. My sample doesn't work if I use a quad instead of a cube. Makes little sense but that is what it seems.

**Comment by liaxim** [comment]
Rebased

**Comment by liaxim** [comment]
@NolaDonato Got your test app working. No issues with render-to-texture and/or oes textures actually.


Detailed list of changes:

**gaussianblurhorz.fsh:1**
```
#extension GL_OES_EGL_image_external_essl3 : require
```
to
```
#extension GL_OES_EGL_image_external : require
```

**TestMain.java:61**
```
GVRSceneObject blurryCamera = new GVRSceneObject(context, 3.6f, 2.0f, null, GVRMaterial.GVRShaderType.OES.ID);
```
to
```
GVRTexture t = getGVRContext().getAssetLoader().loadTexture(new GVRAndroidResource(getGVRContext(), R.drawable.ic_launcher));
GVRSceneObject blurryCamera = new GVRSceneObject(context, 3.6f, 2.0f, t);
```
Do note that if the quad is created without a texture (any texture) passed to the ctor subsequent attempts to set the texture have no effect. Will be investigating further and I think it may have something to do with issue https://github.com/Samsung/GearVRf/issues/967.

**TestMain.java:113**
```
final GVRSceneObject blurryQuad = new GVRSceneObject(mContext, 1, 1, texture, GVRMaterial.GVRShaderType.OES.ID);
```
to
```
final GVRSceneObject blurryQuad = new GVRSceneObject(mContext, 3.6f, 2.0f, texture, GVRMaterial.GVRShaderType.OES.ID);
```

Since the render-to-texture is not focusing on a particular scene object the scene needs to be treated as if it were the regular main scene. Hence the quad size.

**TestMain.java:120**
```
blurryQuad.getTransform().setPositionZ(-0.01f);
```
to
```
blurryQuad.getTransform().setPositionZ(-2f);
```

Getting culled otherwise.

---

As expected the performance is bad even if the regular camera is shown since the blurry one is getting rendered anyway.

The blurry camera texture is flipped vertically because the GVRSceneRenderTexture is doing it intentionally. May be it shouldn't, will be checking that.

**Comment by liaxim** [comment]
I will be looking into prototyping the component you suggested. It will still be Java-only but will be more in line with your idea.

**Comment by NolaDonato** [comment]
Take a look at this branch to see what I did in C++: https://github.com/NolaDonato/GearVRf/tree/rendertotexture


Thanks so much for fixing the blur app! Now I can help the user with his problem.


-Nola

________________________________

**Comment by liaxim** [comment]
Obsoleted by https://github.com/Samsung/GearVRf/pull/1099

**Pull request closed without merging**
