### PR TITLE
Smaller controller model, laser pointer pick ray

### PR DESCRIPTION
**Pull request by NolaDonato**
Adding updated controller model
1. Made bounding volume smaller
2. Make texture smaller
3. Moved to assets directory
4. Made a .MTL file for the .OBJ

Made controller pick ray red and decay towards the end
1. Add GVRVertexColorShader to use vertex colors in a mesh for lighting
2. Add GVRLineSceneObject construct which takes colors for endpoints
3. Use vertex color shader to make color of controller pick ray get
dimmer towards the end
4. Remove unnecessary draw frame listener in gaze controller

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Looks good. Planning to merge on Wednesday.

**Comment by liaxim** [comment]
Why include gear_vr_controller.obj and the texture if they are not used? The texture is 4MB+..

There are also these:
```
GearVRf/GVRf/Framework/framework/src/main/res/drawable-xhdpi/gear_vr_controller_color_1024.png
GearVRf/GVRf/Framework/framework/src/main/res/raw/gear_vr_controller.obj
```
Should these be removed?

**Comment by NolaDonato** [comment]
I will remove them.

**Comment by roshanch** [comment]
tested with gvr-controller oculus backend, works fine.

**Pull request merged**
