### PR TITLE
rebuild shader if texture added later

### PR DESCRIPTION
**Pull request by NolaDonato**
This patch propagates the dirty bits which indicate a new texture has
been added to the RenderPass and RenderData so the shader can be
recreated in this case. It fixes a bug in the 3D cursor sample with the
animated cursor.

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
gvr-controls: some of the textures are missing
gvr-3d-cursorsimple: some of the other textures of the red cube are missing

**Comment by NolaDonato** [comment]
What textures are wrong in gvr-controls? I have compared it with the maint_v3.x version and it looks the same.

**Comment by liaxim** [comment]
In my tests the sky and the fence were missing - all black. Will git clean -fdx and retest.

**Comment by liaxim** [comment]
Not reproducing anymore after git clean -fdx. Will merge on Friday.

**Pull request merged**
