### PR TITLE
Port to Oculus 0.6.1 and VrAppSettings updated

### PR DESCRIPTION
**Pull request by chenchao1407**
1. To build GVRF this time, you may need to at least import VrAppFrameWork,
LibOVRKernal, VrAppSupport/VrModel into your workspace

2. Since oculus changed their parameters in ovrSettings. According changes
are made in VrAppSettings.

3. All samples' xml files get updated.

GearVRf-DCO-1.0-Signed-off-by: Chao Chen

### CODE REVIEW

**Comment by chenchao1407** [comment]
Updated. Build script for ant build added. And also dependencies of VrAppFramework and VrApi removed. Instead, it is asking you to put prebuilt libraries from these two projects into libs folder. The reason for it is because since Oculus closed all java sources from these libraries. There is no need to import them and reference them in Eclipse workspace.

**Comment by thomasflynn** [comment]
I seem to be having problems linking to vrapi.  The vrapi library i found was a .so instead of a .a like the rest.  maybe that's the problem?

**Comment by chenchao1407** [comment]
Not sure, in Android.mk if it is a .a, it will be linked as a static library and use term LOCAL_STATIC_LIBRARIES. If it is a .so, it will be linked as a shared library. Let me see at your side on Monday.

**Comment by chenchao1407** [comment]
@thomasflynn  Did you put VrApi.jar from VrApiPrebuilt and VrAppFramework.jar under libs folder?

**Comment by thomasflynn** [comment]
ok, i'm able to build from eclipse now.  and i can build from the command line.  please prepare and update to the build instructions (http://wiki.gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start#BuildInstruct).  I'll update the wiki when we're ready to push this.

**Comment by chenchao1407** [comment]
Build Instruction:

A. For terminal

1.  To build the Framework, firstly, you need to download oculus mobile sdk 0.6.1 from oculus website, https://developer.oculus.com/downloads/mobile/0.6.1.0/Oculus_Mobile_SDK/. Unzip the file you downloaded with, and rename the folder to ovr_mobile_sdk, then put it into the GearVRf folder, which is at the same level with GVRf.

2.  In ovr_mobile_sdk, please copy ./VrApi/Libs/Android/VrApi.jar and ./VrAppFramework/Libs/Android/VrAppFramework.jar to Framework's libs folder, which locate at GVRf/Framework/libs.


3. Please make sure that you haven't left any stuff from Eclipse build or previous failed build for any reason. In Eclipse, do clean the project and in terminal, try to run build.sh with parameter clean(in Framework folder, run:  ./build.sh clean)

4.   in Framework, run ./build.sh  It can run with optional parameter as debug or release to build with the version(release, debug) you want.

5. The build for framework at terminal is done.

6. To build GVRF app through terminal, please firstly in Eclipse, do clean the project and in terminal, run build.sh with parameter clean to make sure everything is cleaned.

7. Secondly, download an oculus signature file in the following URL:
https://developer.oculus.com/osig/

and then put it into assets folder of GVRF app project.

8. Finally run the following build commands in the root folder of your app project:
android update project -p ./
ant [release/debug]
To run ant, you can either run it with paramter release or debug to choose which version you want to work out.

8. You will see the generated apk in the bin folder and you can run adb install APK_NAME.apk to install it into your phone. 


B. For eclipse, please follow step 1,2,3 above to import prebuilt oculus libraries and clean the stuff firstly. And then, you can directly build the project in workspace without importing any Oculus project.

**Comment by chenchao1407** [comment]
Rebased. Any one who can help check and merge it if there is no issue?

Thanks in advance.

**Comment by chenchao1407** [comment]
Updated to fix a compiling issue

**Comment by jason2kim** [comment]
The release is now published. And, we need to update wiki page,

OLD: "On your local machine, unzip the file and put the unzipped libs folder into your GearVRf app folder 
(for example, /gvrfApp/libs-gvrf/gvrf_exported.jar and /gvrfApp/libs-gvrf/lib/)."

=>NEW: "On your local machine, unzip the file and put the unzipped libs folder into your GearVRf app folder. Also copy the oculus library files, such as VrApi.jar and VrAppFramework.jar, to the same location.
(The folder will look like, /yourapp/libs/gvrf_exported.jar, /yourapp/libs/lib/armeabi-v7a/libgvrf.so, /yourapp/libs/VrApi.jar, and so on)"

**Comment by thomasflynn** [comment]
ok, check the site, have i modified the instructions correctly?

**Comment by jason2kim** [comment]
verified okay.

**Pull request merged**
