### PR TITLE
androidstudio migration: framework

### PR DESCRIPTION
**Pull request by jason2kim**

### CODE REVIEW

**Comment by jason2kim** [comment]
**How to import projects to IDEs:**

**For Eclipse users,**
go to File, Import, then select Existing Android Code Into Workspace -> 
give the path of src\main, 
e.g. {your local path}\GearVRf\GVRf\Framework\framework\src\main, 
{your local path}\GearVRf-Demos\gvr-sample-androidstudio\gvrsample\src\main
, where the ported Eclipse project files are located -> 
Select the project, then click Finish
Copy prebuilt *.jar and *.so into libs/ the same as Developer’s Guide

**For Android Studio users,**
go to File -> Import Project (or Non-Android if first run, depending on Version), or Open Project -> Select the project folder to import, 
e.g. {your local path}\GearVRf-Demos\gvr-sample-androidstudio
Copy prebuilt *.jar and *.so into libs/ the same as Developer’s Guide

**gvr-sample-staticlib**
**gvr-video-staticlib-androidstudio**
refer to https://github.com/Samsung/GearVRf/releases. And, README file inside.

**Note,**
-	gvr-sample-androidstudio will be renamed to gvr-sample when finalizing migration
-	Folder structure
{your local path}\GearVRf\GVRf\Framework
{your local path}\GearVRf\ovr_sdk_mobile
{your local path}\GearVRf-Demos\gvr-sample-androidstudio
-	Build instructions at http://www.gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start#BuildInstruct

**TODO: **
migration of other sample apps, testing and cleaning

**Comment by jason2kim** [comment]
**Android Studio**
1) Download
https://developer.android.com/tools/revisions/studio.html
Android Studio v1.5.1, e.g. android-studio-ide-141.2456560-windows.exe (No SDK tools included)

2) Installing Android Studio
Uninstall old if you have
Follow the instruction: https://developer.android.com/sdk/installing/index.html?pkg=studio

**Comment by jason2kim** [comment]
**Example settings on my Linux machine:**

### Eclipse and Java
export PATH=/usr/lib/jvm/jdk1.7/bin:$PATH
export JAVA_HOME=/usr/lib/jvm/jdk1.7
export ANDROID_JAVA_HOME=/usr/lib/jvm/jdk1.7

export PATH=/home/jasonkim/tools/android-sdk-linux/platform-tools/:$PATH
export PATH=/home/jasonkim/tools/android-sdk-linux/tools/:$PATH
export ANDROID_SDK_HOME=/home/jasonkim/tools/android-sdk-linux/
export ANDROID_HOME=/home/jasonkim/tools/android-sdk-linux/

export PATH=/home/jasonkim/tools/android-ndk-r10d:$PATH
export ANDROID_NDK_HOME=/home/jasonkim/tools/android-ndk-r10d
export ANDROID_NDK=/home/jasonkim/tools/android-ndk-r10d
#

**Comment by thomasflynn** [comment]
it looks like you added a file under a release/ directory (prior releases of gvrf).  not necessary for this commit.

**Comment by liaxim** [comment]
Have verified that Eclipse works and Android Studio does, as long as you literally follow the instructions. If you deviate from the default directory structure things can get hairy to set up right again. Couldn't avoid exporting ANDROID_NDK_HOME and ANDROID_NDK before launching Android Studio.

Questions:

- What about Android Studio 2.0?

- Did you manually add the "framework" module to the sample project? "Manually" in the sense editing the gradle files directly.

- Any chance we may use environment variables for things like the location of the GVRF framework for example?

- We have this Framework/framework path, any chance this might be collapsed?

---
In my opinion when the time is right this should be rebased and merged as soon as possible so we can start working out the kinks.

**Comment by jason2kim** [comment]
Answers,

- It was Android Studio 1.5.1 at the time of this pull request. As of today (April 7), I see new version of 2.0 here: https://developer.android.com/sdk/index.html
- The framework module was auto imported from Android Studio 1.0 then custom edited for our needs. Now, we can import it again in 2.0 to see what it gives differently.
- Dynamic location of GVRf framework: any suggestion would be appreciated
- Module name framework in fold path Framework/framework: any suggestion would be appreciated

**Comment by thomasflynn** [comment]
so, this should be abandoned, right?

**Comment by liaxim** [comment]
I think so.

**Comment by liaxim** [comment]
@jason2kim Are you ok with closing this pull request?

**Comment by jason2kim** [comment]
closing as it went to the new one of #504

**Pull request closed without merging**
