### PR TITLE
Support for Google VR

### PR DESCRIPTION
**Pull request by rahul27**
This commit contains changes to support google vr:

https://github.com/googlevr/gvr-android-sdk.git

The google vr sdk is currently Android Studio only, this patch
deconstructs the v0.8.5 library aar files to support Eclipse.

The framework would now default to Google VR when Oculus is
not present on the device.

Monoscopic can still be used by forcing the mode using the
vr app settings.

The api versions have also been bumped from 19 to 21 to
support this change.

GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by rahul27** [comment]
The pull request may seem big due to a large number of resource files form the deconstructed aar file (to support Eclipse). But going forward when we discontinue Eclipse support [PL715](https://github.com/Samsung/GearVRf/issues/715) I will replace all the files with a single aar file.

**Comment by rahul27** [comment]
I have modified two sample projects to test this change:

gvr-simplesample & grv-simplegallery

https://github.com/gearvrf/GearVRf-Demos/pull/258

Once I get the okay, will go ahead an change the other samples as well.

**Comment by thomasflynn** [comment]
@rongguodong, please review ;-)

**Comment by rahul27** [comment]
:laughing:

**Comment by liaxim** [comment]
This can't be merged before the common base is extracted. Then we will have to update it to separate out the Google backend. Doesn't seem much.

If you ask me don't even bother with Eclipse. Provide instructions how to use it if people want to. It is not our problem to solve. This will reduce the changes to their core.

Don't know how big the binaries are but still shouldn't be getting into git.

**Comment by rahul27** [comment]
Will wait for your changes to be merged in.

**Comment by liaxim** [comment]
Needs rebase

**Comment by rahul27** [comment]
Looks like https://github.com/Samsung/GearVRf/pull/671 has broken the Eclipse build. @liaxim could you confirm?

I guess it is okay for me to remove the Eclipse support files from this pull request.

**Comment by liaxim** [comment]
It is a very small change to add one more source folder, namely backends/oculus. I think I saw this change somewhere in @roshanch 's pull requests. I rather not make it because it will force him to rebase again..

**Pull request closed without merging**
