### PR TITLE
Asset loader: expose events, fix opacity export

### PR DESCRIPTION
**Pull request by NolaDonato**
Modified asset loader to check filename prefix to determine volume type:
"sd:" indicates SD card, "http:" and "https:" indicate URL, otherwise
assets directory.

Expose asset event handler for users to handle asset loading events

Make Jassimp export opacity correctly (addresses issue in PR #617)

### CODE REVIEW

**Comment by NolaDonato** [comment]
GearVRf-DCO-1.0-Signed-off-by: Nola Donato nola.donato@samsung.com

**Comment by roshanch** [comment]
it addresses issue in PR #617.

**Comment by liaxim** [comment]
@danke-sra Opinions on the asset loading change?

**Comment by liaxim** [comment]
I have noted some problems in the demos pull request: https://github.com/gearvrf/GearVRf-Demos/pull/205. Apart from couple of things with the demo there was a "Could not compile shader" error observed too.

**Comment by liaxim** [comment]
Refers to unmerged x3d classes. This pull request should have been really split at least in two. We can't merge the transparency export fix for totally unrelated reasons.

**Comment by NolaDonato** [comment]
I will split these. I messed up and included X3D stuff :-( My bad.

**Comment by NolaDonato** [comment]
Cleaned this one up and resubmitted as PR #658

**Pull request closed without merging**
