### PR TITLE
[maint_v3.x] input manager refactor, fix npe in gaze, fix #1627

### PR DESCRIPTION
**Pull request by liaxim**
- merge inputmanager and inputmanagerimpl, expose interface instead
- fix npe in gaze cursor controller due to the recent scanDevices/scanControllers change
- fix #1627 

---
GearVRf-DCO-1.0-Signed-off-by: Mihail Marinov <m.marinov@samsung.com>

### CODE REVIEW

**Comment by NolaDonato** [comment]
The problem with setting the scene to NULL is that, if that cursor controller is reactivated, there is no longer a scene and it doesn't do picking anymore. This case can be caused by removing the batteries from the Gear controller. It will switch to the Gaze controller. Putting the batteries back in causes it to switch back to the Gear controller which no longer has a scene.

**Comment by liaxim** [comment]
Fixed the controller activation after reconnect by setting the main scene; commit 
8b19081. Seems more appropriate fix and also precautionary. Immersivepedia had problems because an unused controller instance was doing its own picking on the scene - one specific reason it is better to null out the scene, just in case.

**Comment by ragner** [comment]
It looks good to me.

**Comment by liaxim** [comment]
Thank you @ragner for reviewing. Planning to merge on Tuesday.

**Pull request merged**
