### PR TITLE
Adding special shader for X3D content

### PR DESCRIPTION
**Pull request by NolaDonato**
This shader still needs work. It does not produce correct results when there are no lights (need clarification on what it should do).

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
@mwitchwilliams How does the new shader work for you?

**Comment by mwitchwilliams** [comment]
Debugging a different issue right now, but will get to this after that.

**Comment by liaxim** [comment]
Planning to merge on Friday.

@mwitchwilliams What should happen if a Material with only emissiveColor is used in a scene with x3d lights? In my tests I get mostly white objects.

**Comment by mwitchwilliams** [comment]
I get the same results as you. In the first scene, there are no lights, and it looks correct. The second scene has a &lt;PointLight&gt; and &lt;DirectionalLight&gt;
But I don't think this is an emissiveColor issue. There is a default diffuseColor on each material of (.8, .8, .8), and that is what is reacting with the lights.
screenshot_20180228-134201
screenshot_20180228-133804
Should I post this as an issue?

**Comment by liaxim** [comment]
@mwitchwilliams Does x3d specify what should happen in the aforementioned case? If not, then it is undefined behavior and can be anything. @NolaDonato Any suggestions?

**Comment by bohuang3d** [comment]
http://x3dgraphics.com/examples/X3dForWebAuthors/Chapter05AppearanceMaterialTextures/EmissiveColorIndex.html

This example has material
<Material diffuseColor='1 0 0' emissiveColor='0 0 1' specularColor='0 1 0'/>

For me, only the emissive blue shows up on the sphere and diffuse/specular seem ignored

**Comment by mwitchwilliams** [comment]
Bo, that is correct.  With no lights (note the &lt;NavigationInto&gt; headlight is false) only emissive color should show up.  Thanks for confirmation.

**Comment by liaxim** [comment]
Tried with the InstantReality player. Lights and only emissive color yields the same result as no lights and only emissive color. Seems rather reasonable. Will file an issue for it.

**Comment by liaxim** [comment]
Planning to merge on Monday

**Comment by mwitchwilliams** [comment]
And I get similar results to Mihail using FreeWRL and X3Dom.
When diffuseColor=(0 0 0) - the X3D default diffuseColor is (.8 .8 .8) - FreeWRL caps the cummulative lights at (1 1 1), and GearVR does not appear to do that.
I couldn't find a specific line in the X3D spec so I emailed to a few authors to get confirmation.
I can add some X3D demo's and screen shots after Mihail posts the issue.

**Comment by liaxim** [comment]
Needs rebase

**Comment by mwitchwilliams** [comment]
Issues implementing /x3d_vertex.vsh shader.  Getting a crash when setting this, even if setting to a 3x3 identity matrix (i.e. no settings from the TextureTransform).

**Comment by liaxim** [comment]
@mwitchwilliams Will wait for your verification first.

**Comment by mwitchwilliams** [comment]
Changed X3D &lt;TextureTransform&gt; code that uses the new texture_matrrix shader and all worked.
screenshot_20180313-090133

upper left: &lt;TextureTransform translation='.3 .2'/&gt;
upper right: &lt;TextureTransform scale='3 2'/&gt;>
center: &lt;TextureTransform center='-.5 -.5' rotation='.785' scale='2 2'/&gt;
lower left: &lt;TextureTransform center='-.5 -.5' rotation='.785'/&gt;
lower right: &lt;TextureTransform center='0 0' rotation='.785'/&gt;
Note: lower right has center set to default (0,0), meaning its texture rotation will be around the (0,0) u,v texture corrdinate

[textrue transform demo.zip](https://github.com/Samsung/GearVRf/files/1807774/textrue.transform.demo.zip)
original texture map:
texture_rotation_testpattern

**Comment by liaxim** [comment]
Planning to merge on Wednesday

**Pull request merged**
