### PR TITLE
Add loadModel, loadScene variants with import settings

### PR DESCRIPTION
**Pull request by NolaDonato**
Adds the ability to specify import settings for loading scene and models
asynchronously. This replaces pull request #1213.

GearVRF DCO signed off by: Nola Donato nola.donato@samsung.com

### CODE REVIEW

**Comment by liaxim** [comment]
Looks good. Will merge on Wednesday.

**Comment by liaxim** [comment]
This was not merged. @NolaDonato Do you not need these changes anymore?

**Comment by NolaDonato** [comment]
Oh no, I thought it had been merged. I will try to get the branch back.

**Comment by NolaDonato** [comment]
I recovered the changes and opened PR #1263

**Pull request closed without merging**
