### PR TITLE
Allocate proper number of texture coordinates for cylinder

### PR DESCRIPTION
**Pull request by Vittalbabu**
Allocate proper number of texture coordinates for cylinder

### CODE REVIEW

**Comment by liaxim** [comment]
Looks good to me. Will merge in the afternoon.

**Comment by thomasflynn** [comment]
Good catch.  +1

**Comment by thomasflynn** [comment]
Perhaps ahould double-check sphere and cube as well.

**Comment by Vittalbabu** [comment]
@thomasflynn The other two cases are fine.

**Pull request merged**
