### PR TITLE
Collision filtering

### PR DESCRIPTION
**Pull request by ragner**
Add GVRCollisionMatrix to collision filtering.

It is based on https://docs.unity3d.com/Manual/LayerBasedCollision.html

GearVRf-DCO-1.0-Signed-off-by: Ragner Magalhaes <ragner.n@samsung.com>
GearVRf-DCO-1.0-Signed-off-by: JulianaFigueira <juliana.f@samsung.com>

### CODE REVIEW

**Comment by ragner** [comment]
Hi all,
I am working in a game that depends of this branch.
It is at https://github.com/ragner/GearVRf-Demos/commits/bullet_sample

and it is based on https://github.com/ragner/GearVRf-Demos/blob/43e1f04778d62bb4e0a5f79bf460e51d05bdebd2/gvr-simplephysics/doc/GVRF_UX_1.0.pdf

But after update the framework to  ovr_sdk_mobile_1.0.4
the game is not rendering the ground anymore. I need help to figure out what is happening.
Does anybody could help me with this issue?

**Comment by liaxim** [comment]
Will check it out

**Comment by liaxim** [comment]
Hi. Rebase your tree on top of the latest master. You are missing 29cb81b2a2a89e907ca49ef81c14ce8167fc8de1 specifically.

**Comment by ragner** [comment]
Wow,
@liaxim  thank you! It is working now.

**Comment by ragner** [comment]
@liaxim  Oh, sorry! I saw the ground once but it after restart the app I can't see anymore.

**Comment by liaxim** [comment]
As usual, after the rebase, please git clean -fdx the framework and rebuild the app. Let's see whether it still doesn't work after that.

**Comment by liaxim** [comment]
Actually for me nothing was showing up initially. The floor is still missing, I see that.

**Comment by liaxim** [comment]
In MainHelper.createGround, after ``groundObject.getRenderData().getMaterial().setTexture("diffuseTexture", texture);`` add ``groundObject.getRenderData().getMaterial().setMainTexture(texture);``. I will have to look into it more but should get your floor back.

**Comment by ragner** [comment]
@liaxim, thank you! setMainTexture fixed the issue

**Comment by liaxim** [comment]
Looks good to me. Sample works fine. @NolaDonato ?

**Comment by liaxim** [comment]
Will merge in the afternoon

**Pull request merged**
