### PR TITLE
GVRTextViewSceneObject: Add REALTIME as a new frequency

### PR DESCRIPTION
**Pull request by danke-sra**
The GVRTextViewSceneObject is only refreshed at the specified frequency if
anything has changed.

### CODE REVIEW

**Comment by ragner** [comment]
Sorry, but in my opinion,
we could keep improving the GVRTextView to simplify the use of it and keep GVRTextViewSceneObject  deprecated.

**Comment by danke-sra** [comment]
OK. I will check with others about the de-deprecation. I also prefer GVRTextView because it is lighter.

**Comment by liaxim** [comment]
@ragner 

We keep falling back to the GVRTextViewSceneObject because it is just more straightforward and easy to use. This is the only reason; I am not fond of it either but was basically forced to use it in certain situations.

As long as the construction is a two-phase thing for GVRViewSceneObjects we will have to keep the GVRTextViewSceneObject around. Also I think we might have to view a textWidget somewhat differently than any-android-view (we may switch to an implementation that is not based on Android views for text for example). In a way the GVRViewSceneObject and GVRTextViewSceneObject are complementary, not competing with each other.

I personally think the de-deprecation is reasonable considering that for text specifically we keep using the deprecated one more frequently.

**Comment by liaxim** [comment]
Overall the code looks good to me. @ragner Since you voiced your concern I will wait for us all to come to an agreement before merging it.

**Comment by rahul27** [comment]
Think it would be cleaner to switch out the internals of one and replace it with the other (whichever is better). Having two ways to create a textview is not ideal.

**Comment by liaxim** [comment]
More or less tried exactly that. We had apps that deadlocked (GLSurfaceView gets callbacks on the UI thread and obtains locks that its GL thread locks on too) if you just start waiting on the UI thread while on the GL thread which a swap like the suggested would lead to. Nowadays we can create everything off the GL thread but not all apps take advantage of that and onInit is still happening on the GL thread. Once we hide the GL thread from the apps things will be much easier.

**Comment by ragner** [comment]
@liaxim  I agree that the use of GVRTextViewSceneObject is easier than GVRViewSceneObject.

With the merge of https://github.com/Samsung/GearVRf/pull/468 is possible to improve GVRViewSceneObject/GVRTextView to simplify its construction to one phase too.

**Comment by liaxim** [comment]
@ragner Are you ok with merging this the way it is?

**Comment by ragner** [comment]
Yes, it is ok.

**Pull request merged**
