### PR TITLE
Update the daydream library to v1.30.0

### PR DESCRIPTION
**Pull request by rahul27**
GearVRf-DCO-1.0-Signed-off-by: Rahul Rudradevan
r.rudradevan@samsung.com

### CODE REVIEW

**Comment by rahul27** [comment]
Looks like just bumping the version number worked from the few samples I tried. Will try a few more tomorrow just to be sure.

**Comment by liaxim** [comment]
@rahul27 How about enabling 64bit build support for Daydream with this update?

**Comment by rahul27** [comment]
Daydream supports 64 bit. All you will have to do is get rid of the `exclude 'lib/arm64-v8a/libgvr.so'` packaging option from the gradle file. I can do it once you the 64 bit oculus change goes through.

**Comment by rahul27** [comment]
This PR is ready for review. Will make the 64 bit change once all the other changes go through.

**Comment by liaxim** [comment]
Works well. Will merge Tuesday morning.

**Pull request merged**
