### PR TITLE
(in progress) Expose getBoundingVolume Java API

### PR DESCRIPTION
**Pull request by liaxim**
Tom, is this something like what you have in mind in issue https://github.com/Samsung/GearVRf/issues/541?

### CODE REVIEW

**Comment by thomasflynn** [comment]
that may work.  though people may also choose to explicitly set the bounding volume as well.

**Comment by thomasflynn** [comment]
oh, and you have this on just the mesh.  at the c++ level, each scene object has a bounding volume as well.

**Comment by liaxim** [comment]
Updated to expose relevant APIs at the GVRSceneObject level.

**Comment by thomasflynn** [comment]
this looks good, though the javadoc needs more than a 'todo'.  i may merge this and fix the javadoc myself.

**Pull request merged**
