### PR TITLE
gradle version

### PR DESCRIPTION
**Pull request by pnemonic78**
Android gradle build tools plugin version 3.0.1 and build tools 26.0.3

### CODE REVIEW

**Comment by thomasflynn** [comment]
@NolaDonato can you check if this works on your machine?

**Comment by NolaDonato** [comment]
It does not work on my machine. I did "Invalidate Caches & Restart" in Android Studio. I did git clean -fdx in the Framework directory. I installed build tools 26.0.2. I still get:

Gradle 'Framework' project refresh failed
Error:Cannot set the value of read-only property 'outputFile' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=debug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl. 

I am not sure which build.gradle it comes from because it doesn't say.

**Comment by pnemonic78** [comment]
@NolaDonato I think you compiled the _GearVRf-Demos_ project instead.

There is no outputFile in any GearVRf gradle file, but there is in GearVRf-Demos "common.gradle":
`output.outputFileName = System.getProperty("appName") + ".apk"`
and VRHackathons:
```
            output.outputFile = new File(
                    output.outputFile.parent,
                     rootProject.name + ".apk")

```

**Comment by NolaDonato** [comment]
If I don't build any demos, just the Framework, it builds for me. I have no way to test since demos don't build.

**Comment by thomasflynn** [comment]
ok, i was mostly concerned with whether the framework built for you.  as pointed out, the Demos repo is a different issue.  Thanks for checking.

**Pull request merged**
